### ISSUE TITLE
Expected ssh pubkey format in KeyParser.java is too strict

### ISSUE THREAD

**Issue by fpunktk** [wolpi/prim-ftpd#101]
In versions after 4.5, I wasn't able to use ssh pubkeys anymore. The error message said that the key could not be read. 
Today I decided to have a look at the code and found out that you are expecting a very strict key format in https://github.com/wolpi/prim-ftpd/blob/f82dcfee433537a90a9316753a327b136314d29b/pftpd-pojo-lib/src/main/java/org/primftpd/pojo/KeyParser.java#L71
I expects exactly three parts, separated by space. But an ssh pubkey can have a comment containing several spaces. Mine did, this check failed and the misleading error was, that it could not be read. 
In my opinion the check should be `if (parts.length >= 2)`.

**Comment by wolpi** [comment]
I switched from using a library to own impl because of #61 and #70. And yes, you are right, I'm going to change this.

**Comment by fpunktk** [comment]
thank you :-)
and quite a useful app, thanks for keeping it up to date :-)
