### ISSUE TITLE
Allow customizable announced device name

### ISSUE THREAD

**Issue by sopos** [wolpi/prim-ftpd#102]
While the device is announced by bonjour it would be nice to be able to define the showed name. If there are more devices in the network it is hard to distinguish between them.

**Comment by wolpi** [comment]
last time I checked it was not possible to change name, see #69.

**Comment by sopos** [comment]
but I think that what I see is not a devive host name. I see 'primitive ftpd' in Caja/Nautilus. So I guess that the application is able to somehow pass the name as the device itself does not know anything about primitive ftps.

**Comment by wolpi** [comment]
>  I see 'primitive ftpd' 

Yes, that can be easily changed. Going to add it in next version.
