### ISSUE TITLE
Create separate log files for different sessions

### ISSUE THREAD

**Issue by Larivact** [wolpi/prim-ftpd#105]
It's hard to debug when the log gets appended to the same file each startup.

**Comment by wolpi** [comment]
Currently it is appended to avoid lost of intresting logs by accident. An option could be to use a timestamp in filename. But then it may happen that too many files are created. That could be avoided by keeping maybe 5 files.

I'm going to check how much work that is.

**Comment by wolpi** [comment]
3 files are kept
