### ISSUE TITLE
Access permissions through Linux sshfs

### ISSUE THREAD

**Issue by busybit** [wolpi/prim-ftpd#106]
When I mount through Linux sshfs the mount works without errors, but uid=daemon, gid=daemon and dir ist not readable:
d--x--x--x  1 daemon daemon     0 Jan  3  1970 mnt

What's going wrong here?

**Comment by wolpi** [comment]
Yes, that looks weird 😭 .

Basically I can tell you that original Linux-permissions are not accessible via java api thus the app just shows dummy permissions when accessed with other clients. But that does not explain this behavior.

Can you share more details?
How do you mount, on commandline, via fstab, via some automounter?
What is your complete commandline, or config file?
Which Linux distro?
Which sshfs package?
Have you tried other clients? Does it work better with them?

**Comment by busybit** [comment]
> How do you mount, on commandline, via fstab, via some automounter?
I tried both, automount (autofs) and mount on commandline.
This is the mount line in autofs:
`Handy    -fstype=fuse,allow_other,default_permissions,port=2121,uid=1000,gid=1000:sshfs\#jochen@192.168.178.38\:/`
Same mount options on commandline.

> Which Linux distro?
Debian Jessie

> Which sshfs package?
Debian sshfs

> Have you tried other clients?
I don't know other clients for Debian Jessie.

Maybe the problem has something to do with LineageOS or the format of the sd card?
The sd card was formatted with exfat on stock Android 6.0.1 on Moto G4 play. The firmware was later replaced with LineageOS 14.1

The permission problems not only exist with sshfs but also with normal ftp protocol. When I try to put files or create diretories I get a "permission denied".

**Comment by licaon-kter** [comment]
I'm not able to write (via S/FTP) on the SD card either, isn't this an Android limitation?

**Comment by busybit** [comment]
Maybe this is the problem:
http://www.lineageosrom.com/2017/02/fix-file-manager-cant-access-sd-card-on.html
I will try it this evening.

**Comment by busybit** [comment]
Removing .android_secure made no difference.
But I'm sure it has something to do with permissions on Android. Logging in with adb shell I find the following permissions:
`drwxrwx--x 1 root sdcard_rw    0 1970-01-01 01:00 7AE2-2A04
drwx--x--x 4 root sdcard_rw 4096 1970-03-14 02:47 emulated
drwxr-xr-x 2 root root        60 1970-01-11 16:42 self
`
7AE2-2A04 is my sd card. Root and group sdcard_rw has all permissions. "Other" has strange permissions, no r, only x. The same strange permissions I see in sshfs. Under what user and group das prim-ftpd run?
ps states that the ftp server runs as user u0_a95, but there is no /etc/passwd file on Android. I don't know how to find the group for that user. Every app runs with a different user. Very strange.

I have no experience with android, only standard Linux. Is there a way I can change the permissions for the sd card mount?

**Comment by busybit** [comment]
I now tried remote manager from ES File Explorer. That works without problems.

**Comment by wolpi** [comment]
Oh, it is about a sdcard. Well, yes, sdcards cannot be used with this app. Long story short: since android 4.4 apps must use a different API to access sdcards. See #31, #51, #65.

**Comment by busybit** [comment]
I found a working solution. One has to format the sd card as internal memory, then migrate data to sd card. After that it is accessible via prim-ftpd. But one thing is important: you have to mount it using the correct path (that depends on your android system), mine is /storage/emulated/0. Mounting the root directory or some other non accessible directory will not work. Android even does not let you navigate to the correct folder. That's really strange and is not normal Linux/Unix behaviour.

**Comment by wolpi** [comment]
Welcome to the weird world of Android storage management :wink:

**Comment by wolpi** [comment]
as #31 is closed this should be done as well
