### ISSUE TITLE
[wish] supply secured transfer

### ISSUE THREAD

**Issue by promeneur** [wolpi/prim-ftpd#11]
it woul be a good thing to have secured transfer .

can you add authentication and encrypting ?

thanks in advance

**Comment by xphnx** [comment]
This feature would be great¡¡

**Comment by wolpi** [comment]
hi,

today I got a first version running, yay!
:)
It needs some more work before being ready to be released.
Currently I have a test-certificate commited. To make transfers really secure it is necessary to generate a certificate on the device.

Can you build and test it on your own ?

regards

**Comment by xphnx** [comment]
Who is the recipient of this message? I have no problem building and testing the new changes. If you need testers just let me get the source code. Regards.

**Comment by wolpi** [comment]
> Who is the recipient of this message? 

Whoever feels addressed :)

> If you need testers just let me get the source code

Yes, please do some testing. I did already a lot of improvements since that last post here. The sftp part is mostly finished. Next part is android5 sdcard handling. There will be some more text changes.

**Comment by wolpi** [comment]
a new version including sftp will be released at beginning of may

enjoy!

**Comment by xphnx** [comment]
Great!!
