### ISSUE TITLE
Filesystem (SD or internal) only readable after Update to tfpd 5.0

### ISSUE THREAD

**Issue by klausmaus** [wolpi/prim-ftpd#111]
Filesystem (SD or internal) only readable after Update to tfpd 5.0 on my Galaxy S8.

Same Problem with "Gutes, altes Dateisystem" and "SAF"

**Comment by klausmaus** [comment]
Cross Check, manually Installation of ftpd 4.10 apk works with write permit.

**Comment by wolpi** [comment]
Could you post logs for both storage types, please?

**Comment by klausmaus** [comment]
I have enabled LOG in File, but I can not find the LOG (.csv) file.

Where is the LOG-File?

**Comment by klausmaus** [comment]
Log:
Error trying copy 'filte.txt' to the Nexus using altes Dateisystem:

[prim-ftpd-log-2017-11-06-08-38-24(Error writing FileTxt FileTxt exists after copy but is empty, Altes dateisystem).txt](https://github.com/wolpi/prim-ftpd/files/1445354/prim-ftpd-log-2017-11-06-08-38-24.Error.writing.FileTxt.FileTxt.exists.after.copy.but.is.empty.Altes.dateisystem.txt)

**Comment by klausmaus** [comment]
Log for SAF:

Log not possible because ftpd crashes after selecting 'in file' log. (if SAF also selected)
Then data of the app must be deleted, otherwise endless loop, reproducible.

**Comment by wolpi** [comment]
which sftp client do you use?

**Comment by klausmaus** [comment]
I use Netdrive in win10

Works Perfect with ftpd 4.10 with Nexus 7, S8, 

All devices does not work with ftpd 5

**Comment by wolpi** [comment]
I've created a test version to see if it fixes your issue. Could you please test it? If you report it's ok I will release it as 5.1.

https://www.dropbox.com/s/420j1e9n0l5ejnj/primitiveFTPd-5.1-SNAPSHOT.apk?dl=0

**Comment by klausmaus** [comment]
I like to do that, but unfortunately not until tomorrow because I'm on business Trip today.

**Comment by wolpi** [comment]
Could you test to create a file in a sub directory, too, please?

e.g. `/storage/emulated/0/test/File.txt`

> I like to do that, but unfortunately not until tomorrow because I'm on business Trip today.

Alright, looking forward to it 😄

**Comment by klausmaus** [comment]
Yes

**Comment by klausmaus** [comment]
Test done - everything works!

Copy file, create folder, delete okay

Thank you - und einen schönen Tag aus Hamburg

**Comment by wolpi** [comment]
Release is on it's way, thanks for helping 🎉
