### ISSUE TITLE
F-Droid release?

### ISSUE THREAD

**Issue by alexpdp7** [wolpi/prim-ftpd#113]
Could you do one? I really want SD card access on my Kindle Fire without installing the Play Store

**Comment by licaon-kter** [comment]
F-Droid release will update in the next few days.

**Comment by Tony-il-Capo** [comment]
I'm also waiting for the update on F-Droid for testing the [this](https://github.com/wolpi/prim-ftpd/commit/bbdb94ddb49f679bfe821d5bb45d39034e8c9468), but it seems the last build has failed
[F-Droid Build Log](https://f-droid.org/wiki/page/org.primftpd/lastbuild_26)

**Comment by wolpi** [comment]
Obviously f-droid changed it's policy and fails builds containing jar files. That was the case for this app for years. Now I changed it to build jar on the fly.
