### ISSUE TITLE
About Translation

### ISSUE THREAD

**Issue by Sak94664** [wolpi/prim-ftpd#115]
Why not set up a translation entrance and let people translate it.(sorry for my poor english^_^)

**Comment by wolpi** [comment]
Currently existing translations have been contributed by users via GitHub Pullrequests 😄.

Can you give me a link?

**Comment by licaon-kter** [comment]
Transifex, Crowdin and Weblate are ok, and free for open-source projects.

**Comment by wolpi** [comment]
Going to check them
