### ISSUE TITLE
support for ssh-ed25519 keys

### ISSUE THREAD

**Issue by leongrdic** [wolpi/prim-ftpd#116]
is there any chance you'll be adding support for ed-25519 keys in `authorized_keys`?

love the app btw, appreciate the work :)

**Comment by wolpi** [comment]
Yes, there is a chance 😉. Probably early next year.

**Comment by wolpi** [comment]
It seems bad.
You might know that this app does not implement protocols nor crypto itself. For protocols it uses [apache mina](https://mina.apache.org) their ssh library uses crypo of JVM and [bouncycastle](https://bouncycastle.org/).

None of them currently supports ed25519.

That means work must be done on those libraries first.
Unfortunatley we cannot use latest version of mina ssh as they require java 7 but on android we are stuck on java 6 (see #100). So it would be necessary to put work in an old version of mina ssh.

**Comment by concatime** [comment]
Is there any news on this issue?

**Comment by wolpi** [comment]
nope, no news.
But contributions are welcome :wink:

**Comment by eddyhub** [comment]
Bouncy Castle release 1.61 is now available: ..._Support has been added to the provider for the Ed25519 and_...: https://bouncycastle.org/latest_releases.html

It seems the next release of Apache MINA (SSHD) will be able to support ed25519: https://gitbox.apache.org/repos/asf?p=mina-sshd.git;a=commit;h=f0acc71f0fc55523940d1de04b98c5df081b6c59

**Comment by takase1121** [comment]
Really hope if ed25519 works. Its my favourite key encryption method and makes my key files small and nice

**Comment by TomBPotochek** [comment]
I think MINA already supports ed25519. Is there any update on this issue?

**Comment by wolpi** [comment]
as we are now able again to publish releases on google play this is one of those things to work on next

**Comment by wolpi** [comment]
finally here it is
release is on it's way to app stores
