### ISSUE TITLE
sd card access problem

### ISSUE THREAD

**Issue by leongrdic** [wolpi/prim-ftpd#117]
i just cant seem to get access to my sd card over primitive ftpd.

i tried two methods:
- root (my phone is rooted) - the sd card directory lists but i have no write permission and can't upload files or change them; log: https://pastebin.com/j6DAgmVG
- saf (and selecting the sd card as the path) - i cant even get the listing of sd card directory, i get: `550 No such directory`; log: https://pastebin.com/LrMAXEZG

the phone is A3 2016 (SM-A310F) and it's running Android 7.0

**Comment by wolpi** [comment]
Thanks for sharing logs. It'll take some days to figure out what goes wrong.

**Comment by leongrdic** [comment]
sure, thanks for your time

**Comment by wolpi** [comment]
> root

You log shows that the app uses command `'chmod 0777 "/storage/1286-4697"'` to make directory writable but on upload it receives `Permission denied` anyway.

Some things you can try to narrow it down:

- Can you create new directories with this app on sdcard?
- Can you upload files in non-sdcard directories which would not be accessible without root?
- Can you create new files on sdcard with an `adb` root shell (e.g. with `touch`)?
- Can you upload files in subdirectories of sdcard?


> saf

The server receives a command to switch to directory `/storage/1286-4697` (probably default directory in client?). In case of SAF your sdcard would be just `/`. Server responds that requested dir does not exist and it seems your client does not display a proper error message.

**Comment by wolpi** [comment]
> Can you create new files on sdcard with an adb root shell (e.g. with touch)?

I changed code to do this, create new files with `touch` as that is run explicitly as `root`. Afterwards a `FileInputStream` is opened with usual app permissions (as said in #55 it is not possible to run java code as `root`, only external binaries can be run as `root`). Hope that fixes your issue.
