### ISSUE TITLE
SAF write failed bad descriptor 

### ISSUE THREAD

**Issue by cesarth** [wolpi/prim-ftpd#118]
Hi, I'm using an AcuarisX5 mobile.
I can start the server and connect, but when I transfer to the mobile long files (longer than about 2Mb) the transfer fails.

I'm using sftp and SAF. (I've tried with  "Plain old system" too and it does not even create the file in the remote folder).
The error message "SAF write failed bad descriptor" appears when I try to transfer with "scp" command line tool. It does not work when I transfer the files with winscp( version 5.9.4 ).

Am I doing something wrong?

Thanks,

César

**Comment by wolpi** [comment]
> but when I transfer to the mobile long files (longer than about 2Mb) the transfer fails.

That seems like a bug

> I'm using sftp and SAF.

That is important information

I'll have to investigate

**Comment by cesarth** [comment]
Thank you.
 "Never increase, beyond what is necessary, the number of entities required to explain anything" --- William of Ockham (1285-1349) "Para qué repetir los errores antiguos habiendo tantos errores nuevos que cometer?" --- Bertrand Russel "en nuestro consumismo, nos hemos convertido en máquinas de cosumirnos a nosotros mismos." --- Vider "Me lo contaron y lo olvidé, lo vi y lo entendí, lo hice y lo aprendí." --- Confucio "El tiempo es el mejor maestro, desgraciadamente mata a todos sus alumnos"

      De: wolpi <notifications@github.com>
 Para: wolpi/prim-ftpd <prim-ftpd@noreply.github.com> 
CC: cesarth <cesar_tejeda_her@yahoo.es>; Author <author@noreply.github.com>
 Enviado: Jueves 21 de diciembre de 2017 23:15
 Asunto: Re: [wolpi/prim-ftpd] SAF write failed bad descriptor (#118)
   

but when I transfer to the mobile long files (longer than about 2Mb) the transfer fails.
That seems like a bug
I'm using sftp and SAF.
That is important informationI'll have to investigate—

**Comment by wolpi** [comment]
In this code path a bad android API method was used which caused this weird 2 mb limit. Another API method is now in use and the issue is gone.
