### ISSUE TITLE
Can't delete files from droid

### ISSUE THREAD

**Issue by dzg** [wolpi/prim-ftpd#119]
I'm connecting from Mac to droid; looking at DCIM folder.

But I can't delete any files on droid side. Get permissions error. Tried FTP and SFTP.

Any idea why?

thanks!

**Comment by wolpi** [comment]
Which storage type to you use: filesystem, root, saf, saf read only?
Is your DCIM folder located on external sd-card?

**Comment by dzg** [comment]
>  filesystem, root, saf, saf read only?

Sorry, no idea what that means

> Is your DCIM folder located on external sd-card?

Yes it is.

**Comment by wolpi** [comment]
>>  filesystem, root, saf, saf read only?

>Sorry, no idea what that means

Which version of the app do you use? Since 5.0 you have to choose between those on main screen.



>>    Is your DCIM folder located on external sd-card?

>Yes it is.

Since Android 4.4 external sd-cards are read only when accessed with a generic file management app.  Google invented saf (storage access framework) for that. Thats why this app lets you choose.

**Comment by dzg** [comment]
Oh! I'm on v4.10
Let me try getting the new version. Thanks!

**Comment by wolpi** [comment]
issue cleanup
