### ISSUE TITLE
Root access issue.

### ISSUE THREAD

**Issue by manuelteillet** [wolpi/prim-ftpd#126]
I'm using primitive ftpd on a rooted Marshmallow Sony Z3 compact.
When I access ftp using Plain old filesystem, I access /storage/emulated/0 correctly. But when I use Root mode, I can't access anything.

Here is a log showing the problem : https://pastebin.com/QXB0Rvnq

I tried the busybox issue from #122 but ls seems to work ok for me.

If you need any other info, just ask me.

Thanks

**Comment by wolpi** [comment]
Thanks for the log!
I need some time to figure out what goes wrong...

**Comment by wolpi** [comment]
> I tried the busybox issue from #122 but ls seems to work ok for me.

Yes, the log indicates that `ls` command cannot be run on your device. I've changed logging to make that better visible.
