### ISSUE TITLE
App crash when choose collect logs in textfile without "storage" permission

### ISSUE THREAD

**Issue by CatKasha** [wolpi/prim-ftpd#128]
App crash when choose collect logs in textfile without "storage" permission

How to reproduce:
1. Reinstall app or clear data or just disable "storage" permission for Primitive FTPd
2. Open Primitive FTPd, go to settings, set collect logs in textfile
3. Tap on back button (phisical/virtual or button in app)
4. Get crash

Primitive FTPd - 5.6 from F-Droid

**Comment by wolpi** [comment]
Oh yes, that needs to be fixed 😇
