### ISSUE TITLE
3 icons since version 5.5

### ISSUE THREAD

**Issue by motatuc** [wolpi/prim-ftpd#129]
Hello.

First of all, thanks for the great app!
With version 5.5 prim-ftpd installs in total 3 icons/shortcuts in the starter.
Personally I don't want to have 3 icons for one app - are there plans to make that optional?

Best
m

**Comment by wolpi** [comment]
They have been added as users asked for them. Meanwhile I heard from several people they don't like it. One of those icons can be turned into a preference ("start server with UI"). I intend to do so for next version. I did not in first place as there are already so many preferences.

**Comment by fazlerabbi37** [comment]
have been using the app for sometime but the 3 icon from last update is a bit upsetting. is it possible to add an option inside the main app enabling which will create the new icons if the user choose to do so? by doing that people who need them can press a button and have 3 icons and people who don't need them will have a clean one icon for that app.

**Comment by MaDill** [comment]
I also prefere one icon per app and not several for some subfunctions. There should be an option to disable it or configure the default behaviour.

**Comment by wolpi** [comment]
those icons are gone now
