### ISSUE TITLE
primitive ftpd is affected by a bug on certain Custom ROMs

### ISSUE THREAD

**Issue by STPKITT** [wolpi/prim-ftpd#130]
Hello,
using a Samsung Galaxy Grand DUOS GT-I9082 running LineageOS 13.0 6.0.1_r79 from July 2017 I discovered that "primitive ftpd" is affected by the bug treated in the following links. In those links you can see that the whole problem is fixed on recent Custom ROMs. Trouble is that a lot of devices are stuck on older ROM releases so "primitive ftpd" development should do the necessary steps to avoid it like the developers on the app "Conversations" did (look at the last link).

https://issuetracker.google.com/issues/64434571

https://jira.lineageos.org/browse/BUGBASH-1052

https://gitlab.com/fdroid/fdroiddata/issues/979

https://github.com/siacs/Conversations/issues/2785

Thanks and greetings!

**Comment by wolpi** [comment]
Seems to be simple enough, going to update tools for next version

**Comment by STPKITT** [comment]
Awesome! Thank you very much in the name of all old school device users :-)

**Comment by wolpi** [comment]
has been changed
