### ISSUE TITLE
Server dies

### ISSUE THREAD

**Issue by hurzl** [wolpi/prim-ftpd#133]
I have to restart it nearly every time I need it. Can the server probably be restarted automatically?

**Comment by Tony-il-Capo** [comment]
What do you mean? Server stops after leaving UI? Do you have the Run in Foreground option enabled? Restrictive OS kill the server (or any other background app) if not running with foreground priority.

**Comment by hurzl** [comment]
Ok this seems to fix it, I didn't know that option (new?), and  "foreground" seems a bit misleading as it is not really running in the foreground now ...

**Comment by Tony-il-Capo** [comment]
> and "foreground" seems a bit misleading as it is not really running in the foreground now ...

Yeah, Android terms really, means apps/services run with high 'priority/importance' (even when in background!) and OS  should not terminate them.

**Comment by hurzl** [comment]
Why not set this as the default as you really don't want to service to be stopped?

**Comment by wolpi** [comment]
> Why not set this as the default 

From todays point of view that would make sense. I have to check docs and api levels to see wheather that is possible.

**Comment by wolpi** [comment]
forground is default now
