### ISSUE TITLE
Can’t access directory problem

### ISSUE THREAD

**Issue by frk3737** [wolpi/prim-ftpd#135]
i think super user(rooted) mode of storage type has a bug causes message like ‘Error Code 450’. if not it’s not a bug and can fix myself, would you like help me fix the problem??

**Comment by wolpi** [comment]
Can you share logs?
That would help a lot to figure out what goes wrong.

**Comment by frk3737** [comment]
it's the file

**Comment by frk3737** [comment]
[prim-ftpd-log-2018-03-29-22-57-36.zip](https://github.com/wolpi/prim-ftpd/files/1860405/prim-ftpd-log-2018-03-29-22-57-36.zip)
it's the file

**Comment by wolpi** [comment]
It says it tries to run command `ls -lAd "/storage/6255-DD47` which fails. You can try to run it manually on a shell and see what happens. Probably your system does not support option `-A` as in #122.

**Comment by frk3737** [comment]
The case is pretty similiar or same to me, but the solution always doesn’t react about problem. ahh.. TT anything else to do for? (used 6.0.1, s5)

**Comment by wolpi** [comment]
This time I'm really going to change code to avoid `ls -A`.
Where you able to run that command in a shell?

**Comment by wolpi** [comment]
has been changed, let's see if it really works :wink:
