### ISSUE TITLE
multiple SAF folder with different names/access

### ISSUE THREAD

**Issue by ElTopo** [wolpi/prim-ftpd#136]
Hello,

Is it possible to add multiple-SAF-folder support, so that I can add several SAF folders, and assign them different names (under /, sort of like virtual folders) and different access (Read/Read+Write)?

Thanks.

**Comment by wolpi** [comment]
Well, I totally understand the wish for it. But my time is limited, it will take time.

**Comment by wolpi** [comment]
Finally there will be support for virtual folders to have access to all storage types at once
