### ISSUE TITLE
server can't be set to use, exclude ips or ranges

### ISSUE THREAD

**Issue by D4rkH0rs3** [wolpi/prim-ftpd#140]
feature request:
I'm using your beautiful tool as a hack to modify the sdcard from the termux command line and would like to set the server to only talk to 127.0.0.1
I can easilly imagine use cases where you would only want the server to talk to 192.168.* or block somewhere known for its hackers.

thank you for listening
and more generally thank you for a great tool.

**Comment by wolpi** [comment]
> I'm using your beautiful tool as a hack to modify the sdcard from the termux command line

That's an interesting usecase :laughing: 

> where you would only want the server to talk to 192.168.*

Yes, makes sense. I'll look into it.

> and more generally thank you for a great tool.

Happy that you like it :tada:

**Comment by wolpi** [comment]
A preference to set a pattern for allowed IPs have been added.
