### ISSUE TITLE
HTTP Server

### ISSUE THREAD

**Issue by aaferrari** [wolpi/prim-ftpd#142]
When trying to access an address like http://192.168.1.103:12345/ and instead the page never finishes loading or shows this error:
```
220 Service ready for new user.
530 Access denied.
530 Access denied.
530 Access denied.
530 Access denied.
530 Access denied.
```
I think it could be used to add an HTTP server in the application. It would be enough for it to be something similar to [SimpleHTTPServer](https://play.google.com/store/apps/details?id=jp.ubi.common.http.server) and in terms of which library to use or how to implement such functionality, [this](https://stackoverflow.com/questions/6329468/how-to-create-a-http-server-in-android) could be a good starting point.
I suggest this because Chrome (and probably most of its forks) do not support FTP protocol and therefore only work in Firefox (or some Gecko based browsers), which greatly limits at the users who are just looking for a simple/quick way to share files.

**Comment by wolpi** [comment]
Funny to ask for http in a ftp app :laughing: 

Anyway I'm going to look into this.

Some things to consider or check:
* This app is heavily based on FileSystem abstraction of apache mina libraries. A http server needs to be integrated with this.
* Use configured password for http basic auth?
* Enforce basic auth?
* How to design preferences to configure which servers shall be launched?

I guess next thing users ask for will be https. And aftwerwards Let's encrypt :smile:

**Comment by licaon-kter** [comment]
But why? Use https://github.com/marcosdiez/shareviahttp

**Comment by aaferrari** [comment]
I understand that it seems like a strange request but I thought it would be more practical to have an app that does everything instead of installing two or more applications with similar functionalities.
Anyway, if the idea is discarded, there is still to see how to respond to an HTTP request made by the user (maybe it can be done with a redirect or show an error page).

**Comment by wolpi** [comment]
there will be no http in this app
