### ISSUE TITLE
Feature request: make lockout options configurable

### ISSUE THREAD

**Issue by PaddyMac** [wolpi/prim-ftpd#143]
Apparently Primitive FTPd locks out an ip address temporarily after 3 failed login attempts. But neither the number of failed attempts before banning nor the length of time for the ban is user-configurable. This is really frustrating when you're just using it on the LAN to transfer files between the phone and desktop, but you start getting "connection refused" messages inexplicably.

Also, I tried turning on the log to a text file, but the name and location of the text file is not stated nor configurable, so I couldn't find it. Please make this configurable.

**Comment by wolpi** [comment]
This is probably default behavior of used libraries, I'm going to check it.

**Comment by wolpi** [comment]
So far I could not find a reason for that lockout behavior. Changes for #140 might affect it.

What protocol do you use (ftp, sftp, both)?
Which client?
Which authentication method?
Can you describe in more detail when/how a lockout happens?

**Comment by wolpi** [comment]
issue cleanup
