### ISSUE TITLE
Feature request: add pause/restart button in notification

### ISSUE THREAD

**Issue by SuppaMan150** [wolpi/prim-ftpd#144]
Would it not be useful if there was a button in the notification that allow to pause and restart the server quickly without reopening the application?
For those like me who use the start at boot function, have the server always active and often change wifi network it would be useful to be able to pause and restart the service quickly.

Thank you

**Comment by wolpi** [comment]
Do I get you right?
You don't want to just restart server but stop it for some time (say one hour), keep notification and start server again?

**Comment by SuppaMan150** [comment]
Exactly, You got that right.
