### ISSUE TITLE
Add option to shutdown after some time of idling.

### ISSUE THREAD

**Issue by lambdaupb** [wolpi/prim-ftpd#146]
I sometimes forget to disable the FTP server again, which has the side-effect of preventing my screen to turn off after the display timeout.

It would be a nice option to be able to auto-shutdown the server after some time without connections.

This also is a security plus, in case the server is anonymous or has a weak password.

**Comment by wolpi** [comment]
I'm going to look into it

**Comment by lambdaupb** [comment]
For the FtpServer it is possible to get the idle status using a modified FtpStatistics implementation.

```java
import org.apache.ftpserver.impl.DefaultFtpStatistics;
import org.apache.ftpserver.impl.FtpIoSession;

import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicLong;


public class LastUsageFtpStatistics extends DefaultFtpStatistics {
    private AtomicLong lastConnectionClose = new AtomicLong(System.nanoTime());

    @Override
    public synchronized void setCloseConnection(FtpIoSession session) {
        super.setCloseConnection(session);

        this.lastConnectionClose.set(System.nanoTime());
    }

    public long getLastActivityWasMillisecondsAgo() {
        if(this.getCurrentConnectionNumber() > 0) {
            return 0;
        } else {
            return TimeUnit.NANOSECONDS.toMillis(System.nanoTime() - lastConnectionClose.get());
        }
    }
}
```

which is then injected to the FtpServerContext:

```java
		// do start server
		ftpServer = (DefaultFtpServer) serverFactory.createServer();
        LastUsageFtpStatistics lastUsageFtpStatistics = new LastUsageFtpStatistics();
        ((DefaultFtpServerContext)ftpServer.getServerContext()).setFtpStatistics(lastUsageFtpStatistics);
```

`System.nanoTime()` is used since it is guaranteed to be monotonic, so immune to clock changes.


I had some fun poking around, feel free to ignore.

**Comment by wolpi** [comment]
Happy hacking :wink: 
You can turn it in a pull request, that would make you a contributor.
There is still a mechanism needed to query lastConnectionClose and trigger a server stop event. And of course something similar for sftp. I can take care of these.

**Comment by wolpi** [comment]
Did you notice `dataConConfigFactory.setIdleTime()`?

**Comment by lambdaupb** [comment]
I just looked into it, but that only sets a timeout for how long a connection can be open without actions from the client.

My goal is to shutdown the whole app after some time nobody connecting to the server.

**Comment by wolpi** [comment]
Hmm, I think this would require another background service which periodically checks `getLastActivityWasMillisecondsAgo()` and issues `server stop` when timeout is reached.

**Comment by wolpi** [comment]
There is a preference to configure idle timeout

**Comment by pby5u** [comment]
Hi,

Maybe I misunderstand that feature. Does it actually mean that the server is stopped after time X or does it only mean that the connection is terminated after time X? 

I set to idle timeout to 1 minute, still the server keeps running. If this feature is only intended to kill the connection but not the server, how about another option to actually kill the server after idling for time X?
