### ISSUE TITLE
Save As (Overwrite File)

### ISSUE THREAD

**Issue by ekorn** [wolpi/prim-ftpd#149]
When I use the Share button in Android prim-ftp offers me a "save-as" Function, which is great and very useful. But it would be handy to replace a existing file. At the moment every "share" call create a new file.

**Comment by wolpi** [comment]
There are cases where android passes in a filename. In such cases that name can be used.

**Comment by wolpi** [comment]
> There are cases where android passes in a filename. In such cases that name can be used.

Actually that is already present, but it seems to not work in all cases. It checks whether filename exists already and adds a number to filename to make it unique.

You want to stop that behavior?

Maybe there could be a preference.

**Comment by ekorn** [comment]
Sorry I have been on vacation for a while.
My use case is a e-book reader that support custom standby pictures saved as suspend.jpg. It would be very handy to 
* open a photo or use OsmAnd Map
* make a screenshot 
* save it as suspend picture

So the Screenshot tool will or may will not give a filename but in any case I would like to be able to choose a file and replace it.

**Comment by wolpi** [comment]
OK, thanks for clarifying. I'm going to see how to do it best.

**Comment by wolpi** [comment]
Now it lists directories and files. If a directory is selected a filename will be generated (or taken from passed data). If a file is chosen that one is overwritten.
