### ISSUE TITLE
Support for SSHFS

### ISSUE THREAD

**Issue by ericzolf** [wolpi/prim-ftpd#151]
Hi,

it would be really nice to have primitive FTPd extended enough to support SSHFS. Currently mounting is possible, I was also able to create a directory but creating a file, either with `touch file1` or with `echo content > file1` wasn't possible. Writing into an existing file is possible e.g. with `echo content > fileexists` but appending seems to work but actually overwrites the whole content e.g. `echo addtlcontent >> fileexists`. `cp file1 fileexists` works but `mv file1 fileexists` does not work, `mv file1 newfile` (where newfile doesn't exist, i.e. a rename) works though.

SSHFS should be available on any Linux, e.g. on Fedora as fuse-sshfs, or from https://github.com/libfuse/sshfs

All this works with an OpenSSH server running on another Android device, so it's a limitation of the server, not of the SSHFS implementation. There is only one exception: `touch file` complains that it can't set the date, but that's minimal.

Thanks, Eric

**Comment by wolpi** [comment]
I'm going to look into it.
Can you provide logs with exceptions?

**Comment by ericzolf** [comment]
Hi,

I prepared three files and called twice the same script (see code below, I can't attach it), once on a normal file system and once on the SSHFS file system, the result logs are attached below:

- [prim-ftpd-log-2018-08-04-07-53-19.csv.gz](https://github.com/wolpi/prim-ftpd/files/2259233/prim-ftpd-log-2018-08-04-07-53-19.csv.gz) - I've replaced the user and password with "myuser" and "mypassword".
- [test_normal.log](https://github.com/wolpi/prim-ftpd/files/2259234/test_normal.log)
- [test_sshfs.log](https://github.com/wolpi/prim-ftpd/files/2259235/test_sshfs.log)

And here the script used twice:

```bash
date
head -n-0 test?.txt
set -x
touch test4.txt
echo test55555 > test5.txt
cat test5.txt
echo replace333 > test3.txt
cat test3.txt
echo append333 >> test3.txt
cat test3.txt
cp test1.txt test3.txt
cat test3.txt
mv test2.txt test3.txt
cat test3.txt
cp test1.txt testA.txt
cat testA.txt
mv test1.txt testB.txt
cat testB.txt
set +x
echo === FINISH ===
ls -l
head -n-0 test?.txt
date
```

The timestamps should be aligned between PC and Android. Android is 8.1 btw. Let me know if I can provide more information.

**Comment by wolpi** [comment]
Thanks!
Those logs don't contain exceptions as I expected but anyway. I'm going to take care of this.

**Comment by wolpi** [comment]
I cannot reproduce the errors. All those things are working well for me. Which storage type do you use?

**Comment by wolpi** [comment]
issue cleanup
