### ISSUE TITLE
"Permission denied" while copying certain files from /data/data

### ISSUE THREAD

**Issue by finefoot** [wolpi/prim-ftpd#153]
When I connect to prim-ftpd SFTP with Storage type "Super user" with Filezilla and browse to `/data/data/com.whatsapp/databases`, I can list the files and folders just fine. However, if I try to copy `msgstore.db`, I get error "Permission denied". If I use my File manager to copy the file to another folder, first - and copy it from there, everything works fine.

Thank you very much in advance. :+1:

**Comment by wolpi** [comment]
Another case where android behaves weird. Can you share two things to help find out more detail:
- logs containing the error
- open a shell and show us the output of `ls -l` on that file
?

**Comment by emmi474** [comment]
Thank you for replying!

> logs containing the error

Where do I get these logs?

> open a shell and show us the output of `ls -l` on that file

What kind of shell do you mean? I do have Termux installed. Can I use that?

**Comment by wolpi** [comment]
By default logs are disabled. There are two options in preferences: use android system log or create an own log file. android log ist ok when YouTube are familiar with android developer tools. Otherwise the log file ist better. It created in default home directory. Actually another file ist created at each server start with timestap in it's name.



Termux ist fine as long as it has permission to access that file. Would be great to get output of whole directory to see if file in question has other attributes than the others.

**Comment by emmi474** [comment]
> Otherwise the log file ist better. It is created in default home directory

I'm sorry. Where is this log file supposed to be? I went to FTP Server Preferences > Log and selected Log to Textfile. Then I started the server and tried to copy the file. After the error occurred, I stopped the server and looked for a log file but couldn't find any.

> Would be great to get output of whole directory to see if file in question has other attributes than the others.

I did not forget about the directory listing you requested and will post it soon. However, what I found out by now is that

* Concerning files which I can copy from `/data/data` seem to be limited to files from `/data/data/org.primftpd`. I cannot copy any files from `/data/data/com.whatsapp` or other apps.

* I had the same problem with Termux, too. `cp` would return "Permission denied" if I tried to copy from `/data/data/com.whatsapp` or any other app folder in `/data/data` other than `/data/data/com.termux`. `ls` however worked just fine. If I use the `tsu` package in Termux (so `tsudo cp ...`) I can copy all files without problems.

Can you reproduce the issue or can you copy files from `/data/data` with your phone?

**Comment by wolpi** [comment]
Sorry, log file ist not created at server start but at app start. Therefore there is an exit menu entry. The location is different on devices, often it is `/sdcard/emulated/0`.


Protecting `/data/data` is part of androids security concept to isolate apps from each other. Each app has it's own folder there an can just access that one. To access the others the app must use root mechanisms.

**Comment by emmi474** [comment]
> Sorry, log file ist not created at server start but at app start. Therefore there is an exit menu entry

No, I'm sorry, I couldn't find any log file. Restarted the phone, restarted the app, verified the "Log to Textfile" setting. Nothing. :thinking: 

However, I tried `sudo adb logcat --pid=<pid>` and I hope this helps: https://gist.githubusercontent.com/emmi474/b648cb995906e9c70fa5a4e481b46d2e/raw/b1b048e43e16c194eeda28bc2ec546b1f8c0c38f/logcat-primftpd

It contains a `ls` directory listing, too.

> Each app has it's own folder there an can just access that one. To access the others the app must use root mechanisms.

Yes, I know about the security measures around `/data/data`. But why can I list the folder but not copy the files - even with root access? Doesn't the issue I'm describing exist on your phone?

**Comment by wolpi** [comment]
The log ist great, exactly what I wanted. It shows that everything should be fine but android refuses access.

Currently I don't have a rooted device available so I cannot test.

AFAIK devices behave different regarding those android specific secutity measures, and often behave quite weird.

Another topic where this applies is access to sdcard and "storage access framework". Here are lots of closed issues about that.

You said you can copy with a filemanager? Which one? If it is open source I might get an idea what else could be done from it's code.

Another thing comes to my mind: maybe the file ist locked because WhatsApp (or it's background service) is running?

**Comment by emmi474** [comment]
> You said you can copy with a filemanager? Which one? If it is open source I might get an idea what else could be done from it's code.

It's https://github.com/TeamAmaze/AmazeFileManager

> Another thing comes to my mind: maybe the file ist locked because WhatsApp (or it's background service) is running?

Possible, yet very unlikely, no? Why would the File manager succeed with copying the file then?

**Comment by emmi474** [comment]
> As you might know it is not possible on android to run java code of an app as root but launch linux commands as external processes with root priveledges.

Did not know that, thanks. A lot of things make sense now.

> Another thing I could do is to copy files to a tmp location and download them from there.

Yes, this should be okay as a work-around. However, for big files it's really inefficient. Hmm :thinking: 

Some ideas:

* How do you read the requested files with Java? Could you maybe use `dd` (within a superuser process with granted root privileges) or something like that to provide the file's binary data to your Java read-in method?

* So, as far as I understand, your app has user-rights and is only able to spawn subprocesses with superuser-rights. Can you somehow (re)start your whole app as root which would make your Java methods run as root?

**Comment by wolpi** [comment]
`dd` is a good idea. Going to experiment with it.

I tried some other things to read data from other processes but it all failed (files were read partly, streams aborted). Thus I ended up with the chmod approach. What other options are there to read a file through another process (avoiding java.io.File)?

**Comment by wolpi** [comment]
`dd` works quite well. I just had to add a short delay before starting to read it's outputstream.
