### ISSUE TITLE
v5.10 crashes when you try to open the settings

### ISSUE THREAD

**Issue by Dook1** [wolpi/prim-ftpd#155]
With v5.09 - all ok.

**Comment by wolpi** [comment]
One change related to settings is introduction of categories.
Which android version and device do you use?
Can you provide logs?
That would be super helpful!

**Comment by Dook1** [comment]
4.0.4 Sony st21i2
[Log_2018-10-12_01-15-54.txt](https://github.com/wolpi/prim-ftpd/files/2470914/Log_2018-10-12_01-15-54.txt)

**Comment by wolpi** [comment]
has been fixed
