### ISSUE TITLE
5.10 crash

### ISSUE THREAD

**Issue by FX9590** [wolpi/prim-ftpd#156]
Device: Xiaomi MIX 2S
API Level: SDK 28

Log collectived by prim-ftpd: 
https://mega.nz/#!odIF2aLD!HnikUgzWdIzftDkoG053gx3JgMWl6oJk8R1-3ivinyQ
https://mega.nz/#!kZJhjShI!Usg9rSFgza5nJTdn5151MBCOwZP2uHLkhhPm-OvO9n0

Appearance：Crash when click the "Start Sever" button. Setting works well.

I've tried to clear the data and reinstall prim-ftpd, but it dosen't work.

Need any further info?

**Comment by FX9590** [comment]
By the way, prim-ftpd works well on my LG G5 with mokee MK71.2.

**Comment by wolpi** [comment]
has been fixed

**Comment by wolpi** [comment]
Enjoy :tada:
