### ISSUE TITLE
Crypto Provider changes in Android 9

### ISSUE THREAD

**Issue by wolpi** [wolpi/prim-ftpd#157]
https://android-developers.googleblog.com/2018/03/cryptography-changes-in-android-p.html

This causes issues with sftp.

**Comment by licaon-kter** [comment]
You might need to use conscrypt, eg: https://github.com/siacs/Conversations/search?q=conscrypt&type=Commits

**Comment by wolpi** [comment]
going to check it

**Comment by iadeelzafar** [comment]
@wolpi Can you please share your e-mail? I had some questions related to a project on FTP. Your guidance would be really helpful for me.
Apologies for commenting here.

**Comment by wolpi** [comment]
@iadeelzafar you can find it e.g. on google play page of this app. Usually I prefer to discuss stuff here on GitHub. Of course it is better to create own issues instead of hijacking others :wink:

**Comment by wolpi** [comment]
Just adding conscrypt didn't help. Google changed the way how java security provider API behaves. In our case apache mina sshd interacts with that API. Seems like it will be necessary to copy it's code and modify it in this app. Similar as it is done for slf4j already.

**Comment by wolpi** [comment]
Version 6.0 is on it's way to app stores
