### ISSUE TITLE
Weblate problems

### ISSUE THREAD

**Issue by mirbuf** [wolpi/prim-ftpd#158]
Hi,
I want to report problems with your Weblate installation. I cannot register a new user, I could only login via github account auth. Once logged in, I cannot add a new email address or change mine. I cannot even change password or issue a contact message.
Anyway, while you solve Weblate related problems, I did a complete Italian translation for FTPd. Have a look at it.

**Comment by wolpi** [comment]
Those problems are present as there is currently no mail server.

>  I did a complete Italian translation for FTPd

Wow, thanks!
It has just been merged :smile: :+1:

**Comment by wolpi** [comment]
mail sending has been configured in meantime
