### ISSUE TITLE
Always hangs when download transfer is nearly finished (ls output without link count)

### ISSUE THREAD

**Issue by mirbuf** [wolpi/prim-ftpd#159]
Whenever I start a transfer from Device to PC, it hangs at 85-99%, depending on the size. Every single time. The opposite instead works (PC -> Device). I'd like to solve this problem. I had a look at the logs and nothing evident came to my eyes. My sensation is: transfer is done with buffer blocks, and when the buffer is fully filled, it is transfered regularly. The last block to be transfered will always be partially filled, and this hangs the server (maybe a condition like testing EOF isn't working as expected on my device, maybe another approach can be tested, like comparing transfered size with original filesize). The problem happens also with small files (i.e. size is smaller than transfer block). Contact me if you want me to test some debugging enabled version on my device.

**Comment by wolpi** [comment]
Could you provide logs anyway?

Two important things to be known:
- which protocol do you use (ftp/sftp)?
- which storage provider (filesystem, root, SAF, read only SAF)?

Sounds like an issue of upstream libraries ...

**Comment by mirbuf** [comment]
Log provided. Removed sensitive data (username, password, and some files list, leaving only those files involved in transfer testing).

1) Protocols: sftp works, ftp doesn't work
2) Storage:
- filesystem works, but hangs while downloading last block (had to stop ftp, thus generating an exception on ftp server)
- root doesn't work (can't find directory, even if it exists),
- SAF hangs during file listing
- RO SAF works but hangs while downloading last block

[prim-ftpd-log-2018-10-16-09-33-24.zip](https://github.com/wolpi/prim-ftpd/files/2482125/prim-ftpd-log-2018-10-16-09-33-24.zip)

**Comment by wolpi** [comment]
thanks for logs, figuring this out will take some time

**Comment by wolpi** [comment]
> SAF hangs during file listing

When there are many files in one directory SAF is known to be slow.

> root doesn't work (can't find directory, even if it exists),

Logs show that the `ls` command of your android device produces other output than expected (it omits link count). I'm going to work on this.

The other two things (hangs while downloading last block, ftp doesn't work) cannot be reproduced by me.

**Comment by mirbuf** [comment]
> The other two things (hangs while downloading last block, ftp doesn't work) cannot be reproduced by me.

Do you want me to test some beta version with full-debug enabled logging of the send/receive inner routine to try to nail down where the problem lies?

**Comment by wolpi** [comment]
Well, this app does not implement protocols on it's own. It uses libraries from apache mina. I am not familiar with that library code on such a deep level.

I suggest you wait for next version which contains a fix for your specific problem with root mode and try that.
