### ISSUE TITLE
sshfs fails reset by peer

### ISSUE THREAD

**Issue by melonius** [wolpi/prim-ftpd#160]
I read #64 #83 #71 but they do not work for me

version 5.10 on fairphone2
symptoms:
sshfs -p 1234 user@192.168.1.131:/storage/emulated/0 ~/mnt/fp2/  
       read: Connection reset by peer
on server; The public key to authenticate can not be read.
there is no public key on /storage/emulated/0/.ssh

in the first attempt the application has stopped.
I have tried with and without public key , and with anonymous login.

How can I find the fault?
may be i have disable file writing?

**Comment by wolpi** [comment]
As you can see in #151 there are issues with sshfs.

> on server; The public key to authenticate can not be read.

How have you configured public key?
Can you access with some other sftp client and public key auth?

**Comment by melonius** [comment]
Thanks wolpi.
I've configured without public key

In the end I was able to connect but I do not know what I have done.
It seems that there is something that randomly prevents it and I do not see anything in the logs.

access with sshfs is slow.

I've tried sshelper and I have access by sshfs faster

Tell me if I can help in any way

**Comment by wolpi** [comment]
> access with sshfs is slow.

Do you still have logging enabled?
Logging slows things down as messages of all loglevels are processed.

**Comment by wolpi** [comment]
issue cleanup
