### ISSUE TITLE
"550 No such directory" in superuser mode

### ISSUE THREAD

**Issue by Dook1** [wolpi/prim-ftpd#161]
In superuser mode:
```
257 "/mnt/sdcard" is current directory.
CWD /mnt/sdcard/
550 No such directory.
```
In normal mode -no problem.
[prim-ftpd-log-2018-10-15-00-46-44.log](https://github.com/wolpi/prim-ftpd/files/2476914/prim-ftpd-log-2018-10-15-00-46-44.log)

**Comment by wolpi** [comment]
hmm, this needs some investigation

**Comment by wolpi** [comment]
It is an issue as in #159: the `ls` command produces unexpected output. A fix is in progress.
