### ISSUE TITLE
Corrupt file received

### ISSUE THREAD

**Issue by aario** [wolpi/prim-ftpd#162]
In super user mode, received jpeg file is corrupt.

- Phone HTC 10.
- Operating system is LineageOS 7.1.2. Rooted.
- Primitive FTPD version is 5.10 downloaded from f-droid.
- Downloaded file with Filezilla 3.33.0 on Debian Sid.

**Comment by wolpi** [comment]
Did this error happen with previous version?
There have been changes in this area, see #153

**Comment by wolpi** [comment]
issue cleanup
