### ISSUE TITLE
5.11 requires generating key frequently

### ISSUE THREAD

**Issue by FX9590** [wolpi/prim-ftpd#165]
Androide Version: Android Pie  
Device: Xiaomi MIX 2S  
It shows that public key could not be read.
(I have to give the screenshot later for link failure.)  
Log: https://mega.nz/#!hdIgQYQZ!Dytrtx7Uyj1VCTcTmuCsbccGmhjK0SmPZcfuuMDnKIs  
  
I've got no idea about weather it's bug, though, it didn't occur to me before this time. And that's why i posed a issue here.

**Comment by FX9590** [comment]
![](https://i.imgur.com/fI0oP5E.jpg)

**Comment by wolpi** [comment]
Well, this error message (and exceptions in log) are not about key generating (generation of ssh server key, necessary for sftp at all). They are about reading key for public key auth. That is optional and must be configured. You have to place that key in a certain file.

Do you want to use public key auth?
Did public key auth work with older versions?
Are you able to use sftp with password?

**Comment by FX9590** [comment]
It seems like "public key authentication" was wrongly enabled.
And it's definitely my fault, i'm sorry about that.
Thanks for your reply.

**Comment by wolpi** [comment]
It's great when issues just disapear ☺️
