### ISSUE TITLE
Ask for a new key every time it start

### ISSUE THREAD

**Issue by FX9590** [wolpi/prim-ftpd#169]
Device: Moto Z2 Force Nash
OS: LineageOS 15.1-20181228-Nightly-Nash Android 8.1
Every time i reboot the phone, ftpd will ask for a new key.
choosing either option generate or cancel has no effect on it correct work.
Log was attached below, and the suffix should be csv.

[prim-ftpd-log-2018-12-30-00-37-22.txt](https://github.com/wolpi/prim-ftpd/files/2716556/prim-ftpd-log-2018-12-30-00-37-22.txt)

**Comment by FX9590** [comment]
1. Sure. If it didn't, ftpd couldn't work when i choose cancel.

2. After you mentioned, I took care of it. Yes, restarting ftpd also will causes that.
By the way, it doesn't happen every time when i reboot my phone or ftpd, just a little frequently. It's my miss.

3. I've got no idea about that. it showed up weeks ago when i using Factory rom. because of reasons i didn't report it. Unluckily, i haven't got a log file on Factory ROM. I'm using Mokee now.

I'll provide a log on Mokee later. Hope it will be helpful.

What's the meaning of your last two sentences? Apart form log, you need key file too?

**Comment by FX9590** [comment]
[prim-ftpd-log-2018-12-31-13-51-43.txt](https://github.com/wolpi/prim-ftpd/files/2717782/prim-ftpd-log-2018-12-31-13-51-43.txt)

**Comment by FX9590** [comment]
Device: xiaomi mix 2s Polaris. OS: MIUI 10 8.12.27 Android 9.0 I tried it on my xiaomi mix 2s, and got the same problem. Log file was attached below. Hope it will be helpful.

**Comment by wolpi** [comment]
Logs still don't contain an error. It is still not clear what exactly happens :cry: 

> What's the meaning of your last two sentences?

Well, it is an short explanation how things work. Intended as a starting point to figure out what goes wrong.

> Apart form log, you need key file too?

Nope, I don't need your key.


Basically I wonder if key files are removed or if they are present but cannot be read. As there are no errors in logs I guess it's the first issue. Then I wonder how or by whom they are removed. Could it be a vendor specific change to android, that no files, created by apps on their own, are allowed in private data directory?

**Comment by FX9590** [comment]
> Logs still don't contain an error. It is still not clear what exactly happens
https://mega.nz/#!kJBTlShD!1Uuc0Zprn6HGZV-SuhnR72hNTRqTY3vtdp9J6vJQPeU
It's a video recorded when it happened. the problem really exists. you could see key really exists below.
If log serves couldn't get those error, did you get any idea?

> Then I wonder how or by whom they are removed.
"/data/data/org.primftpd/filses/" have two files, pftpd-priv.pk8 and pftpd-pub.bin. they are successfully created.
When generating a new key, hash value of files will change too.
I check the permission of them too, and it's 660.
they are not removed, and creating and modifying key are both work well.

> Could it be a vendor specific change to android, that no files, created by apps on their own, are allowed in private data directory?
Private data directory should be guaranteed for apps, and the problem happened on MIUI10, Mokee, Lineageos, and Motorola factory rom; I don't think it should be a vendor specific change.

The problem happened on my both phones, it shouldn't be rare. However, there is no other one report the same issue. it's strange.

**Comment by wolpi** [comment]
While tracing code to add above logging I saw there should be a log message `calcPubkeyFingerprints()` in any case. But I cannot find it in your latest log file.

Are we miss understanding each other?

**Comment by wolpi** [comment]
issue cleanup

**Comment by spec1re** [comment]
Device: Nvidia Shield TV 2017 16 GB
OS: Android 8.1 Nvidia Experience 7.2.3

Same boot, new key on reboot thus autostart not working.

Noo **org.primftpd** folder in **/storage/emulated/0/Android/data**, so no logs sorry.

**Comment by FX9590** [comment]
@spec1re 
you could enable "log to textfile", and it will be in /storage.

**Comment by spec1re** [comment]
Okay, will have look and report back.

**Comment by spec1re** [comment]
There you go.

[prim-ftpd-log-2019-04-19-18-51-40.log](https://github.com/wolpi/prim-ftpd/files/3098795/prim-ftpd-log-2019-04-19-18-51-40.log)
[prim-ftpd-log-2019-04-19-18-53-25.log](https://github.com/wolpi/prim-ftpd/files/3098796/prim-ftpd-log-2019-04-19-18-53-25.log)

**Comment by wolpi** [comment]
Thanks for your logs!

It is still not clear where this behavior comes from :sob: 
Could be that it is related to async tasks used to show key fingerprints. I'm going to add some more logging to better understand it.
Would be great if you could share logs again after you got new app version. Might take one week or a little longer until you get it.

**Comment by spec1re** [comment]
Sure, no problem. 

Maybe a dumb question, where are those keys stored? It looks like it must be somewhere temporary or just Oreo specific?

**Comment by wolpi** [comment]
Key files are stored in "app private data directory". That is usually located under `/data/data/<app id>` and not accessible by users. Android stores app preferences there, too.

Of course the question here is if key files are removed or still present. Logs shall tell us ...

**Comment by wolpi** [comment]
release is on it's way to app stores

**Comment by spec1re** [comment]
Its fixed since 5.15, for me.

Thanks.

**Comment by wolpi** [comment]
While looking through code for places where logging would be helpful I found a suspicious location and changed it. Obviously that was the bug :laughing: 

Thanks for reporting back :+1:

**Comment by FX9590** [comment]
> While looking through code for places where logging would be helpful I found a suspicious location and changed it. Obviously that was the bug 😆
> 
> Thanks for reporting back 👍

What should I say to express my gratitude in English?
Thanks for your services?

**Comment by wolpi** [comment]
❤️ 🎉 👍 😃
