### ISSUE TITLE
Starting servers by widget does not work reliably

### ISSUE THREAD

**Issue by wolpi** [wolpi/prim-ftpd#174]
When no activities have run yet and touching widget nothing happens. Instead server should be launched. Works fine after activities have been run.

**Comment by wolpi** [comment]
That was caused as widget was initialized by UI code

**Comment by wolpi** [comment]
still not working reliably :sob:

**Comment by phuyuk** [comment]
The widget has always been (and continues to be) hit and miss for me. Usually it works. Sometimes, it will toggle the server on, but then won't toggle the server off. Sometimes, the widget is just dead, altogether. Launching the app generally restores widget operation. 5.17 did not resolve the issue.

**Comment by wolpi** [comment]
So far the widget has been working when activity was present in background. It didn't work when activity was not started.

Now that has been solved.
