### ISSUE TITLE
No subdirectories when in super user mode

### ISSUE THREAD

**Issue by HJarausch** [wolpi/prim-ftpd#175]
Running primitive ftpd in 'Super user' mode I can't see nor cd to any subfolder of the
initial folder.
This doesn't happen if I use SAF but this is dead slow on changing / listing folders (transfer is fast though)
I'm using version 5.16.
Many thanks for a hint,
Helmut

**Comment by wolpi** [comment]
Same applies as in your other issue:
Serverside logs would be great!

Your device is rooted, right?
