### ISSUE TITLE
read only SAF can't access L2 subfolders on external storage

### ISSUE THREAD

**Issue by GDXN** [wolpi/prim-ftpd#177]
System Huawei P9lite (Android 7) + 128GB Samsung Evo+
PC client Filezilla

**Comment by wolpi** [comment]
Hmm, i'm quite sure that has been working once. Need to check it. That code area is hard to work with and will take time ...

**Comment by Poomex** [comment]
Same problem here with Android 9 on Xiaomi Redmi Note 7.

**Comment by wolpi** [comment]
Should be fixed in next version
