### ISSUE TITLE
Automatic disconnection of sftp session after 10 mn

### ISSUE THREAD

**Issue by LoQuercynol** [wolpi/prim-ftpd#179]
Hello, after opening a sftp user session, I'm automatically disconnected after 10 mn of transferring a big file, so that it's impossible to transfer it. I've got the message : "org.apache.sshd.server.session.ServerSession - Disconnecting : User session has timed out idling after 600000 ms"
It seems to come from a default value in mina-sshd/ServerSession.java : "private int idleTimeoutMs = 10 * 60 * 1000;   // 10 minutes in milliseconds".
I've found here that this default value can be overriden with "sshServer.getProperties().put(SshServer.IDLE_TIMEOUT, idleTimeoutMs)" (http://mail-archives.apache.org/mod_mbox/mina-dev/201108.mbox/%3C1357177497.7027.1314700297817.JavaMail.tomcat@hel.zones.apache.org%3E).
Would it be possible to change or disable this automatic disconnection delay ?
Thanks.

**Comment by wolpi** [comment]
I'll have a look at it, will take some time ...

**Comment by wolpi** [comment]
The existing preference to configure idle timeout is now used for sftp, too. Now it has default value 0 which disables idle timeout.
