### ISSUE TITLE
Can it work in 4G mobile network?

### ISSUE THREAD

**Issue by Rioders** [wolpi/prim-ftpd#183]
My phone can get pubilc IPv6 address in WIFI and 4G. In my test, it worked in WIFI, but didn't work in 4G. I don't think the ISP has blocked the IPv6's ports of 4G. 

Is the android's firewall rules in *wlan* interface different with *ccmni* interface?

My phone is Android 9.

**Comment by wolpi** [comment]
AFAIK most (all?) ISPs for mobile configure their networks with large NATs. So basically mobile devices are not reachable over the internet. But can reach out.

You could test with network analysis tools like traceroute or nmap.

**Comment by Rioders** [comment]
Thanks for your reply. Thanks for your prim-ftpd. It works in my phone's 4G IPv6 network.

I know the ISPs for mobile usually configures private IPv4 which cannot be directly accessed from outside. 

My ISP for mobile LTE started to configure pubilc IPv6 address, then I want to try sharing files with FTP/SFTP server in Android devices.

I don't know why it didn't work last time. But now it works well. So I think there are not special firewall rules limiting the *ccmni* interface in Android.
