### ISSUE TITLE
not listening IPv4

### ISSUE THREAD

**Issue by OmlineEditor** [wolpi/prim-ftpd#185]
the program does not listen and does not work on IPv4 protocol (no tcp).
Listens only on IPv6 port (only tcp6). Where could the problem be?

Phone: Redmi Note 7 (LineageOS 16.0 (Android 9.0))

netstat -lptun | grep ftp
tcp6       0      0 :::12377   :::*  LISTEN    3483/org.primftpd

------------ Log ------------
 "2019-11-30 10:34:57.9";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"onResume()";"";
"2019-11-30 10:34:57.9";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"displayServersState()";"";
"2019-11-30 10:34:57.9";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"checkServicesRunning()";"";
"2019-11-30 10:34:57.9";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"updateButtonStates()";"";
"2019-11-30 10:34:57.9";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"network connectivity changed, data str: 'null', action: 'android.net.conn.CONNECTIVITY_CHANGE'";"";
"2019-11-30 10:34:59.5";"TRACE";"org.primftpd.PrimitiveFtpdActivity";"genKeysAndShowProgressDiag()";"";
"2019-11-30 10:34:59.5";"TRACE";"org.primftpd.ui.GenKeysAsyncTask";"GenKeysAsyncTask()";"";
"2019-11-30 10:34:59.5";"DEBUG";"org.primftpd.ui.GenKeysAsyncTask";"generating key";"";
"2019-11-30 10:34:59.5";"TRACE";"org.primftpd.ui.GenKeysAsyncTask";"num of existing files: '0'";"";
"2019-11-30 10:34:59.7";"TRACE";"org.primftpd.ui.GenKeysAsyncTask";"onPostExecute()";"";
"2019-11-30 10:34:59.7";"TRACE";"org.primftpd.util.KeyFingerprintProvider";"calcPubkeyFingerprints()";"";
"2019-11-30 10:34:59.7";"TRACE";"org.primftpd.PrimitiveFtpdActivity";"handleStart()";"";
"2019-11-30 10:34:59.7";"TRACE";"org.primftpd.PrimitiveFtpdActivity";"hasPermission()";"";
"2019-11-30 10:34:59.7";"TRACE";"org.primftpd.PrimitiveFtpdActivity";"isKeyPresent() -> true";"";
"2019-11-30 10:34:59.7";"DEBUG";"org.primftpd.services.SshServerService";"onStartCommand()";"";
"2019-11-30 10:34:59.7";"DEBUG";"org.primftpd.services.ServerServiceHandler";"handleMessage()";"";
"2019-11-30 10:34:59.7";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"handling event, offset: 1575142499765 ms";"";
"2019-11-30 10:34:59.7";"DEBUG";"org.primftpd.services.ServerServiceHandler";"starting sftp-ssh server";"";
"2019-11-30 10:34:59.7";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"displayServersState()";"";
"2019-11-30 10:34:59.7";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"checkServicesRunning()";"";
"2019-11-30 10:34:59.7";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"updateButtonStates()";"";
"2019-11-30 10:34:59.7";"INFO";"org.apache.sshd.common.util.SecurityUtils";"BouncyCastle already registered as a JCE provider";"";
"2019-11-30 10:34:59.7";"DEBUG";"org.primftpd.services.FtpServerService";"onStartCommand()";"";
"2019-11-30 10:34:59.7";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"ignoring event, offset: 7 ms";"";
"2019-11-30 10:34:59.7";"DEBUG";"org.primftpd.services.ServerServiceHandler";"handleMessage()";"";
"2019-11-30 10:34:59.7";"DEBUG";"org.primftpd.services.ServerServiceHandler";"starting ftp server";"";
"2019-11-30 10:34:59.8";"DEBUG";"org.apache.ftpserver.impl.DefaultFtpServerContext";"Intializing shared thread pool executor with max threads of 10";"";
"2019-11-30 10:34:59.8";"DEBUG";"org.primftpd.services.ServerServiceHandler";"acquiring wake lock (sftp-ssh)";"";
"2019-11-30 10:34:59.8";"INFO";"org.apache.ftpserver.impl.DefaultFtpServer";"FTP server started";"";
"2019-11-30 10:34:59.8";"DEBUG";"org.primftpd.services.ServerServiceHandler";"wake lock already taken (ftp)";"";
"2019-11-30 10:34:59.8";"DEBUG";"org.primftpd.util.IpAddressProvider";"addr: '/fe80::3c55:b7ff:fe6e:b0ec%dummy0', iface name: 'dummy0', disp name: 'dummy0', loopback: '...";"";
"2019-11-30 10:34:59.8";"DEBUG";"org.primftpd.util.IpAddressProvider";"Skipping IPv6 address 'fe80::3c55:b7ff:fe6e:b0ec%dummy0'";"";
"2019-11-30 10:34:59.8";"DEBUG";"org.primftpd.util.IpAddressProvider";"addr: '/::1', iface name: 'lo', disp name: 'lo', loopback: 'true'";"";
"2019-11-30 10:34:59.8";"DEBUG";"org.primftpd.util.IpAddressProvider";"addr: '/127.0.0.1', iface name: 'lo', disp name: 'lo', loopback: 'true'";"";
"2019-11-30 10:34:59.8";"DEBUG";"org.primftpd.util.IpAddressProvider";"addr: '/fe80::2a16:7fff:fee2:b36a%wlan0', iface name: 'wlan0', disp name: 'wlan0', loopback: 'false'";"";
"2019-11-30 10:34:59.8";"DEBUG";"org.primftpd.util.IpAddressProvider";"Skipping IPv6 address 'fe80::2a16:7fff:fee2:b36a%wlan0'";"";
"2019-11-30 10:34:59.8";"DEBUG";"org.primftpd.util.IpAddressProvider";"addr: '/192.168.1.7', iface name: 'wlan0', disp name: 'wlan0', loopback: 'false'";"";
"2019-11-30 10:34:59.8";"DEBUG";"org.primftpd.util.IpAddressProvider";"addr: '/fe80::3c55:b7ff:fe6e:b0ec%dummy0', iface name: 'dummy0', disp name: 'dummy0', loopback: '...";"";
"2019-11-30 10:34:59.8";"DEBUG";"org.primftpd.util.IpAddressProvider";"Skipping IPv6 address 'fe80::3c55:b7ff:fe6e:b0ec%dummy0'";"";
"2019-11-30 10:34:59.8";"DEBUG";"org.primftpd.util.IpAddressProvider";"addr: '/::1', iface name: 'lo', disp name: 'lo', loopback: 'true'";"";
"2019-11-30 10:34:59.8";"DEBUG";"org.primftpd.util.IpAddressProvider";"addr: '/127.0.0.1', iface name: 'lo', disp name: 'lo', loopback: 'true'";"";
"2019-11-30 10:34:59.8";"DEBUG";"org.primftpd.util.IpAddressProvider";"addr: '/fe80::2a16:7fff:fee2:b36a%wlan0', iface name: 'wlan0', disp name: 'wlan0', loopback: 'false'";"";
"2019-11-30 10:34:59.8";"DEBUG";"org.primftpd.util.IpAddressProvider";"Skipping IPv6 address 'fe80::2a16:7fff:fee2:b36a%wlan0'";"";
"2019-11-30 10:34:59.8";"DEBUG";"org.primftpd.util.IpAddressProvider";"addr: '/192.168.1.7', iface name: 'wlan0', disp name: 'wlan0', loopback: 'false'";"";
"2019-11-30 10:34:59.8";"DEBUG";"org.primftpd.remotecontrol.TaskerReceiver";"sending tasker RequestQueryCondition";"";
"2019-11-30 10:34:59.8";"DEBUG";"org.primftpd.remotecontrol.TaskerReceiver";"sending tasker RequestQueryCondition";"";
"2019-11-30 10:35:06.7";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"onPause()";"";
"2019-11-30 10:39:01.5";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"onStart()";"";
"2019-11-30 10:39:01.5";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"loadPrefs()";"";
"2019-11-30 10:39:01.5";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"got anonymousLogin: false";"";
"2019-11-30 10:39:01.5";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"got userName: delete";"";
"2019-11-30 10:39:01.5";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"got password: delete...";"";
"2019-11-30 10:39:01.5";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"got startDir: /storage/emulated/0";"";
"2019-11-30 10:39:01.5";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"got announce: false";"";
"2019-11-30 10:39:01.5";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"got announceName: primitiveNote";"";
"2019-11-30 10:39:01.5";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"got wakelock: true";"";
"2019-11-30 10:39:01.5";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"got pubKeyAuth: false";"";
"2019-11-30 10:39:01.5";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"got 'which server': ALL";"";
"2019-11-30 10:39:01.5";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"got ftpPassivePorts: null";"";
"2019-11-30 10:39:01.5";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"got idleTimeout: null";"";
"2019-11-30 10:39:01.5";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"got 'port': 12355";"";
"2019-11-30 10:39:01.5";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"got 'secure port': 12377";"";
"2019-11-30 10:39:01.5";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"got showConnectionInfo: true";"";
"2019-11-30 10:39:01.5";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"got 'StorageType': PLAIN";"";
"2019-11-30 10:39:01.5";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"got safUrl: ";"";
"2019-11-30 10:39:01.5";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"got allowedIpsPattern: ";"";
"2019-11-30 10:39:01.5";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"got 'logging': NONE";"";
"2019-11-30 10:41:11.4";"DEBUG";"org.primftpd.services.FtpServerService";"onDestroy()";"";
"2019-11-30 10:41:11.4";"DEBUG";"org.primftpd.services.ServerServiceHandler";"handleMessage()";"";
"2019-11-30 10:41:11.4";"DEBUG";"org.primftpd.services.ServerServiceHandler";"stopping ftp server";"";
"2019-11-30 10:41:11.4";"DEBUG";"org.apache.ftpserver.impl.DefaultFtpServerContext";"Shutting down the thread pool executor";"";
"2019-11-30 10:41:11.4";"DEBUG";"org.primftpd.services.ServerServiceHandler";"releasing wake lock (ftp)";"";
"2019-11-30 10:41:11.4";"DEBUG";"org.primftpd.services.ServerServiceHandler";"stopSelf (ftp)";"";
"2019-11-30 10:41:11.4";"DEBUG";"org.primftpd.remotecontrol.TaskerReceiver";"sending tasker RequestQueryCondition";"";
"2019-11-30 10:41:11.4";"DEBUG";"org.primftpd.services.SshServerService";"onDestroy()";"";
"2019-11-30 10:41:11.4";"DEBUG";"org.primftpd.services.ServerServiceHandler";"handleMessage()";"";
"2019-11-30 10:41:11.4";"DEBUG";"org.primftpd.services.ServerServiceHandler";"stopping sftp-ssh server";"";
"2019-11-30 10:41:11.4";"DEBUG";"org.apache.sshd.SshServer";"Closing SshServer[a4b3f19] gracefully";"";
"2019-11-30 10:41:11.4";"DEBUG";"org.apache.sshd.common.io.mina.MinaServiceFactory";"Closing org.apache.sshd.common.io.mina.MinaServiceFactory@131d4ec gracefully";"";
"2019-11-30 10:41:11.4";"DEBUG";"org.apache.sshd.common.io.mina.MinaServiceFactory";"org.apache.sshd.common.io.mina.MinaServiceFactory@131d4ec closed";"";
"2019-11-30 10:41:11.4";"DEBUG";"org.apache.sshd.SshServer";"SshServer[a4b3f19] closed";"";
"2019-11-30 10:41:11.4";"DEBUG";"org.primftpd.services.ServerServiceHandler";"wake lock already released (sftp-ssh)";"";
"2019-11-30 10:41:11.4";"DEBUG";"org.primftpd.services.ServerServiceHandler";"stopSelf (sftp-ssh)";"";
"2019-11-30 10:41:11.4";"DEBUG";"org.primftpd.remotecontrol.TaskerReceiver";"sending tasker RequestQueryCondition";"";
"2019-11-30 10:41:13.8";"DEBUG";"org.primftpd.remotecontrol.TaskerReceiver";"sending tasker RequestQueryCondition";"";
"2019-11-30 10:41:13.8";"DEBUG";"org.primftpd.remotecontrol.TaskerReceiver";"sending tasker RequestQueryCondition";"";
"2019-11-30 10:46:51.3";"DEBUG";"org.primftpd.remotecontrol.TaskerReceiver";"sending tasker RequestQueryCondition";"";

**Comment by wolpi** [comment]
hmm, this sounds weird.
The only suspicious thing in log is that ftp server is started before preferences are read. The app provides a lot of mechanisms to start server. Which one are you using?

Your netstat output shows sftp port only, not ftp port. That might be related.

I see no indication why ipv4 would not work.

**Comment by OmlineEditor** [comment]
I open the program and press start. In the settings it is indicated that launch both servers. the program says ftp also works. but this is not so. 
where could the problem be?
maybe something changed in the android 9th version. I checked on the 6th version of android everything works there. but on version 9 the android does not work. I saw a lot of reviews on google play that in the new versions of the 9th and 10th, many programs stopped working.

**Comment by wolpi** [comment]
Please report back if version 6.0 solves this issue for you

**Comment by OmlineEditor** [comment]
> Please report back if version 6.0 solves this issue for you

I am waiting for a program update on the site: https://f-droid.org/ru/packages/org.primftpd/
not yet updated, 2 days have passed. please wait a little longer.

**Comment by wolpi** [comment]
It often takes some days until new versions show up on fdroid. Here is a short description how their process works:
https://f-droid.org/en/docs/FAQ_-_App_Developers/#ive-published-a-new-release-why-is-it-not-in-the-repository

**Comment by OmlineEditor** [comment]
> It often takes some days until new versions show up on fdroid. 

they can't compile the 6.0 version. there are errors:
https://f-droid.org/wiki/page/org.primftpd/lastbuild_44

**Comment by wolpi** [comment]
argh, that was messed up :sob: 

I've pushed a fix which should show up as version 6.0.1 in f-droid

**Comment by OmlineEditor** [comment]
> I've pushed a fix which should show up as version 6.0.1 in f-droid

failed on server for org.primftpd:6.0.1'
https://f-droid.org/wiki/page/org.primftpd/lastbuild_45

**Comment by wolpi** [comment]
The reason lies in fdroid scanner.py:
https://gitlab.com/fdroid/fdroidserver/blob/master/fdroidserver/scanner.py
It checks gradle files with regexes. With yesterdays change was gradle code outcommented but the regexes still find it :sob: 
I adjusted files of mina ftp-server some more to pass hat scanner.

**Comment by OmlineEditor** [comment]
> The reason lies in fdroid scanner.py:

the scanner does not see the new version 6.0.2 sees only 6.0.1
https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/org.primftpd.yml
![601](https://user-images.githubusercontent.com/13348933/73189365-55655d80-4135-11ea-95ca-258c1d5500dc.JPG)

**Comment by wolpi** [comment]
seems like fdroid has found new version in meantime but is not providing it to download, yet

**Comment by OmlineEditor** [comment]
the program has been updated. I set it up and checked it out. The program does not listen to IPv4. but now I can connect with the phone. This is strange, there is no connection and there is no wiretapping on IPv4 but the program started working, looking at the traffic all connections through IPv6 but I do not have IPv6. Very strange but everything started working. You can close the ticket.

**Comment by wolpi** [comment]
Unbelievable that new version is finally available on f-droid :laughing: 

Happy that it works for you :tada: 
Even when it's still mysterious :dizzy_face: 

If you would like to dig deeper and figure out what is going on you can share screenshots as well as server-side and client-side logs. But I'm closing this for now.

And thanks for reporting back :+1: . Some people never respond :-1:
