### ISSUE TITLE
Stopped listening(?) after Moto security upgrade

### ISSUE THREAD

**Issue by Jacktar42** [wolpi/prim-ftpd#186]
Prim-ftpd version 5.16 and 5.17 (fresh download)
Android 8.0.0, Android security patch level Nov 1, 2019 (new security patch)
Phone: Moto E5 Play
Client: FileZilla on Win7
Using only IPv4, anonymous ftp (not sftp)

For many months everything had been working fine. Now connection attempts time out. Maybe the recent security patch caused it? It's not possible to remove the security patch, so I can't be sure.

I tried the default ftp port 12345 and also ftp port 3720 (my original).

I would be happy to try any other diagnostics.

![screenshot_prim-ftpd5 17](https://user-images.githubusercontent.com/58481809/70879064-eb279d80-1f78-11ea-83ca-0641c34ed400.png)

Log:
"2019-12-15 06:03:30.0";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"onResume()";"";
"2019-12-15 06:03:30.0";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"displayServersState()";"";
"2019-12-15 06:03:30.0";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"checkServicesRunning()";"";
"2019-12-15 06:03:30.0";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"updateButtonStates()";"";
"2019-12-15 06:03:30.1";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"network connectivity changed, data str: 'null', action: 'android.net.conn.CONNECTIVITY_CHANGE'";"";
"2019-12-15 06:03:40.6";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"onOptionsItemSelected()";"";
"2019-12-15 06:03:40.6";"TRACE";"org.primftpd.PrimitiveFtpdActivity";"handlePrefs()";"";
"2019-12-15 06:03:40.6";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"onPause()";"";
"2019-12-15 06:03:40.6";"DEBUG";"org.primftpd.prefs.FtpPrefsFragment";"onCreate()";"";
"2019-12-15 06:03:40.7";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"onSharedPreferenceChanged(), key: showStartStopNotificationPref";"";
"2019-12-15 06:03:40.7";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"onSharedPreferenceChanged(), key: securePortPref";"";
"2019-12-15 06:03:40.7";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"onSharedPreferenceChanged(), key: pubKeyAuthPref";"";
"2019-12-15 06:03:40.7";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"onSharedPreferenceChanged(), key: anonymousLoginPref";"";
"2019-12-15 06:03:40.7";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"onSharedPreferenceChanged(), key: userNamePref";"";
"2019-12-15 06:03:40.7";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"onSharedPreferenceChanged(), key: showConnectionInfoInNotificationPref";"";
"2019-12-15 06:03:40.7";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"onSharedPreferenceChanged(), key: whichServerToStartPref";"";
"2019-12-15 06:03:40.7";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"onSharedPreferenceChanged(), key: portPref";"";
"2019-12-15 06:03:40.7";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"onSharedPreferenceChanged(), key: wakelockPref";"";
"2019-12-15 06:03:40.7";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"onSharedPreferenceChanged(), key: themePref";"";
"2019-12-15 06:03:40.7";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"onSharedPreferenceChanged(), key: loggingPref";"";
"2019-12-15 06:03:40.7";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"onSharedPreferenceChanged(), key: announcePref";"";
"2019-12-15 06:03:40.7";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"onSharedPreferenceChanged(), key: startOnOpenPref";"";
"2019-12-15 06:03:40.7";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"onSharedPreferenceChanged(), key: announceNamePref";"";
"2019-12-15 06:03:40.7";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"onSharedPreferenceChanged(), key: startOnBootPref";"";
"2019-12-15 06:03:44.6";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"onSharedPreferenceChanged(), key: anonymousLoginPref";"";
"2019-12-15 06:05:18.3";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"onStart()";"";
"2019-12-15 06:05:18.3";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"loadPrefs()";"";
"2019-12-15 06:05:18.3";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"got anonymousLogin: true";"";
"2019-12-15 06:05:18.3";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"got userName: user";"";
"2019-12-15 06:05:18.3";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"got password: null";"";
"2019-12-15 06:05:18.3";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"got startDir: /storage/emulated/0";"";
"2019-12-15 06:05:18.4";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"got announce: false";"";
"2019-12-15 06:05:18.4";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"got announceName: primitive ftpd";"";
"2019-12-15 06:05:18.4";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"got wakelock: true";"";
"2019-12-15 06:05:18.4";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"got pubKeyAuth: false";"";
"2019-12-15 06:05:18.4";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"got 'which server': ALL";"";
"2019-12-15 06:05:18.4";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"got ftpPassivePorts: null";"";
"2019-12-15 06:05:18.4";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"got idleTimeout: null";"";
"2019-12-15 06:05:18.4";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"got 'port': 12345";"";
"2019-12-15 06:05:18.4";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"got 'secure port': 1234";"";
"2019-12-15 06:05:18.4";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"got showConnectionInfo: true";"";
"2019-12-15 06:05:18.4";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"got 'StorageType': PLAIN";"";
"2019-12-15 06:05:18.4";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"got safUrl: ";"";
"2019-12-15 06:05:18.4";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"got allowedIpsPattern: ";"";
"2019-12-15 06:05:18.4";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"got 'logging': NONE";"";

**Comment by wolpi** [comment]
You log shows no indications of error. It does not even show how server starts. You may want to post more extensive logs. When looking at other issues you notice that there seem to be problems with recent android versions.

**Comment by wolpi** [comment]
Please report back if version 6.0 solves this issue for you
