### ISSUE TITLE
Doesn't talk back

### ISSUE THREAD

**Issue by jidanni** [wolpi/prim-ftpd#187]
$ ftp 192.168.43.1 12345
Connected to 192.168.43.1.
220 Service ready for new user.
Name (192.168.43.1:jidanni): anonymous
331 Guest login okay, send your complete e-mail address as password.
Password:
230 User logged in, proceed.
Remote system type is UNIX.
ftp> ls
200 Command PORT okay.
150 File status okay; about to open data connection.
^Cftp: accept: Interrupted system call

receive aborted
waiting for remote to finish abort
425 Can't open data connection.
501 Invalid character in command
ftp> pwd
257 "/storage/emulated/0" is current directory.
ftp> dir
200 Command PORT okay.
150 File status okay; about to open data connection.

Android 8.

**Comment by jidanni** [comment]
OK maybe I needed to do
nft flush ruleset
not sure.

**Comment by wolpi** [comment]
If you still have issues you might post server logs in order to help you
