### ISSUE TITLE
Can apps add character encoding settings?

### ISSUE THREAD

**Issue by OPTS-22** [wolpi/prim-ftpd#193]
Hello, this FTP server is very powerful, but if you can add more character encoding settings, such as KOI8-R, GBK, BIG5, ISO,Provides selectable character encoding settings, Many users in other countries have some errors using their language on the FTP server

**Comment by wolpi** [comment]
Well, this app transfers files in binary mode only. So all encodings should work. Can you provide a concrede example what it not working for you?

**Comment by OPTS-22** [comment]
501 Invalid character in command when transmitting non-English when using windows IE FTP client
and some other FTP clients will have messy code file names, but I have tried some of the better FTP clients and this does not happen,I think it s okay to use it like this.
If you need to open the FTP server for a long time, in addition to keeping the phone's screen always awake, are there other ways to keep the phone on standby and use FTP ?

**Comment by wolpi** [comment]
Well, server cannot fix bad clients :smile: 

> are there other ways to keep the phone on standby and use FTP ?

I don't think so. When device goes to sleep it stops most/some network connections. You are able to recieve calls and messages but running a server and waiting for clients to connect does not work.
