### ISSUE TITLE
http and https support. feature.

### ISSUE THREAD

**Issue by DI555** [wolpi/prim-ftpd#195]
I would like to ask about one great feature! It's http and https support. We may saw it since along ago on mozilla's ftp servers, for example,- so can be possible to go in by a browser using http(s) and see an emulation of ftp view!
When the start dir. with it's full structure can be accessible by http and https!
In a case when the big G plans to drop ftp support at all in it's browser,- accessing by http(s) will be very usefull!

**Comment by wolpi** [comment]
This has been discussed before: #142.

There are many ftp and sftp clients out there. No need to care what big g does.

I won't be working on http support on my own. But I would be happy to review contributions :wink:
