### ISSUE TITLE
Write acces to SD card on Android 10 not working 

### ISSUE THREAD

**Issue by gksucher** [wolpi/prim-ftpd#199]
Hello,
I've set up the ftp server on two different Android 10 phones. 
Before the update from 9 to 10 I was able to modify files by FTP (with setting simple file plain old filesystem) on the SCcard.
After the update this is not possible anymore. Writing to the internal storage is still possible.

br
Gk

**Comment by wolpi** [comment]
Google started with android 4.4 to restrict access to sd-card with plain old filesystem api. And they invented SAF as new way to access sd-card. But device manufacturers and custom roms handle this differently. Obviously you got devices which did not include this change. With android 10 there are even more restrictions regarding filesystem access. See #181 for some discussion.

-> SAF is there for you

**Comment by wolpi** [comment]
closing this as there has been no response in 3 month
