### ISSUE TITLE
Main screen looks cluttered

### ISSUE THREAD

**Issue by wp9015362** [wolpi/prim-ftpd#20]
Hello @wolpi ,

thank you for this great open source app.

It's really useful.

But the main screen looks quite cluttered, because:

It's basically full of text. There is no bold font for the headlines and almost no space between the sections.

I have made a mock-up for an improvement. I'm not really a professional designer at the moment, so I made it with LibreOffice Writer :laughing:. Anyway, here is what it looks like (please also see the notes below the images):

**Server(s) stopped:**

![Image](https://cloud.githubusercontent.com/assets/7558360/8765191/6d561cc2-2e02-11e5-8e1b-8067db338334.png)

**Server(s) running:**

![Image](https://cloud.githubusercontent.com/assets/7558360/8765201/82c59e84-2e02-11e5-9fe0-03a7639b78b8.png)

Notes about this mock-up:

- Toolbar: The start (play) button has been removed and has been moved from the toolbar to the mainscreen (see below). Also the settings icon has been changed from a wrench icon to a gear icon. 
- The start/stop button is now on the main screen. It says "Start server(s)" when the servers are stopped and says "Stop server(s)" when the servers are running.
- The "Running server(s)" section says "None (Press start button to run)" when no server is running. And when server(s) are running it only shows the servers which are actually running. Currently primitive ftpd even shows servers which are not running. IMHO it should only show servers which are running. The port of each server is shown in brackets, so, for example "SFTP (Port 22)".
- The "Username" section shows the username.
- The "Host IPs" section shows the hosts IPs. To save space and to make it look more tidy, it simply lists the IPs and mentions the network interfaces in brackets.
- The "Key fingerprints" section shows four buttons. The "(Re-Generate)" button does (re-)generate the key fingerprints. The "Show MD5" button would open a pop-up which shows the MD5. The "Show SHA1" button would open a pop-up which shows the SHA1. The "Show SHA256" button would open a pop-up which shows the SHA256.

Yeah, that's it.

IMHO it looks much more tidy and cleaner like this.

Any chance you could change primitive ftpd to look more like this?

It would be much appreciated.

Regards

**Comment by wolpi** [comment]
> Toolbar: The start (play) button has been removed and has been moved from the toolbar to the mainscreen (see below).

The UI was like that in the version for android 2. As I adapted android 4 APIs (especially the action bar) I remvoed the big button and added just an icon to the action bar.


> Also the settings icon has been changed from a wrench icon to a gear icon.

Currently I use the android system preferences icon for that. And that is a wrench.


> The "Key fingerprints" section shows four buttons

I prefer to have fingerprints visible at any time without need to press  a button first. On all devices I have seen there was enough space for that.


I will have a look at the other suggestions. In particular to change the layout of sections.

**Comment by wp9015362** [comment]
> @wolpi wrote:
> 
> On all devices I have seen there was enough space for that.

Regarding enough space:

Android allows to configure the system font size.

I have my system font size set to maximum and when primitive ftpd displays a network interface with a long IPv6 address, the IPv6 address does not fit on the screen and is cut off (i.e. is not fully visible).

When reducing the system font size from maximum to to medium, the IPv6 address fits on the screen again and is not cut off.

So, when you redesign the UI, it would be nice if you would bear in mind that users might have their system font size increased.

Regards

**Comment by wolpi** [comment]
Over the weekend I did some work on these issues. Here is a screenshot how it looks right now in light theme (theme can be chosen via preference, see #21)


![prim-ftpd-screenshot-sections-light](https://cloud.githubusercontent.com/assets/1812560/8895555/fe76da3e-33de-11e5-855a-af945971a5c2.jpg)

**Comment by wp9015362** [comment]
Thanks a lot!

That already looks much better!

Both the sections as well as the new light theme!

Some more suggestions though:

IMHO the protocols should be written in capital letters (i.e. FTP / SFTP, not ftp / sftp).

Also, the stop button in primitive ftpd actually is a pause button (two pipes). Since the server states also say "stopped" and not "paused", the pause button should be changed to a proper stop button (i.e. a square) IMHO.

PS:

Just curious: Will the new version which includes those changes be available via the Google Play Store anytime soon :wink:?

Regards

**Comment by wp9015362** [comment]
PPS:

This might be nitpicking now, but, while being at it:

IMHO there probably should be a bit more space between the toolbar and the "IP Address (Network Interface)" heading. Just like there is some space between the "IP Address (Network Interface)" section and the "Protocol / Port / State" heading and so on. Just saying :wink:.

**Comment by wolpi** [comment]
Alright will do some more adjustments. I posted the screenshot to get feedback before releasing it. Release will happen maybe in one or two weeks. Depends on how much time I find to do the other remaining changes.

**Comment by wolpi** [comment]
So I did some more of your suggestions and published it today. May take some hours or even days until it is distributed.

**Comment by wp9015362** [comment]
Actually I already received the update via the Google Play Store.

Thanks a lot :wink: .

**Comment by wolpi** [comment]
:smile: :+1:
