### ISSUE TITLE
error with lftp client (compression issue)

### ISSUE THREAD

**Issue by lrodri** [wolpi/prim-ftpd#200]
when run lftp client and have activate anonymous session in the server 

ie:

  `~$ lftp 192.168.0.101:12345`
  `lftp 192.168.0.101:~> ls`
  `ls: Error fatal: zlib inflate error: incorrect header check`
  
with ftp or mozilla clients work fine.

My box is Debian 10
lftp version 4.8.4
primitive ftp  6.2 (code 48)

thanks in advance

**Comment by wolpi** [comment]
Seems like lftp expects data to be compressed but server does not compress. Let's see when I find time to look into this.

**Comment by wolpi** [comment]
as compression causes errors it has been disabled
