### ISSUE TITLE
[Idea] File sharing via (s)ftp

### ISSUE THREAD

**Issue by takase1121** [wolpi/prim-ftpd#201]
The idea is to let user share file(s) via the share file option, and then the app set up a "virtual folder" containing the file(s) so that they can be downloaded with a ftp client. It may be stupid but it would work great when a directory have a lot of files and I only need to share a few files. Indexing with SAF is still slow so I think that it will be neat.

**Comment by wolpi** [comment]
You might know that this app can already be used to share files. Currently they are stored in internal storage, in a path you choose.
As soon as virtual folders are available (see #136) we can think about making it more comfortable.

**Comment by wolpi** [comment]
I've implemented a first try of this. Calling it Quick Share. For now just one file is supported. May be extended in future. That was done without general virtual folders support.
