### ISSUE TITLE
can't resume from break-point and transfer issues

### ISSUE THREAD

**Issue by HENudie038** [wolpi/prim-ftpd#203]
My device is xiaomi mi 6(sagit) with lineage os 17.1 and redmi note 7 (lavender) with miui 12 based on android 10.The client is nplayer on ipad os 13 and solid file explorer on my android devices.When I use ftps passive old filesystem mode(also ftp passive&active & sftp saf mode), drag playback progress bar in nplayer will stucked,the ftp server still uploading.When I use ftps passive&active saf read-only mode,the nplayer poped up "transfered a partial file" window. When I use sftp old filesystem mode, the nplayer poped up "failed opening remote file" window. 
When I use sftp saf read-only mode,the nplayer can't load any folders.
The issus on solid file explorer were writed in the file name of logs.
here are the logs 
https://shhuemapxhnd-my.sharepoint.com/:u:/g/personal/dnspisjmd_shhuemapxhnd_onmicrosoft_com/EQBB72RnDQJGpe5sUd7_RS4BxDUOPi0zRYP1FNBOYsU6yw

**Comment by wolpi** [comment]
Phew, that are quite some logs for lots of different cases.

By looking at some of them it seems to come down to these topics:
* SAF seems to be a general issue on your device :sob: 
* It seems like you try to access filesystem root (in Logfile it says: `changeWorkingDirectory(/)`). Usually you don't have permission to do that
* What does "break-point" mean? You want to transfer a file not in whole but from somewhere in the middle? In Logs your filenames are that long that interesting part gets cut off (e.g. `[[Nekomoe kissaten&VCB-Studio] HELLO WORLD [Ma10p_1080p][x265_flac].mkv] createInputStream(offset...`, interesting would be to see value of offset parameter, log linie before suggests it would be 107733). Well, downloading a file from somewhere in the middle is currently not supported.

**Comment by HENudie038** [comment]
I'm using ftpd as streaming media server.Only ftp active old file-system mode on nplayer works well,I can move to any time point in the video and play smoothly.But in other modes,when I drag the playback progress bar,it will stucked in that time point,the ftp server seems re-upload the video from the head of the video.

**Comment by wolpi** [comment]
I adjusted the other storage types so they should behave the same as plain old filesystem
