### ISSUE TITLE
Prevent changes to keys

### ISSUE THREAD

**Issue by OmlineEditor** [wolpi/prim-ftpd#204]
Sometimes when I start I am told that I need to change the keys. I don't want to change my keys. If there is a change of keys I will need to check them again and the programs will say when connecting that the keys have changed and there is a chance that hackers will eavesdrop on the connection.

I ask you to add the ability to disable key changes and make them permanent.

**Comment by wolpi** [comment]
There are only two cases where the app asks you to generate new key:

- When you hit the small refresh icon next to key fingerprints. It's the purpose to generate a new key of that icon.
- When you want to start sftp server and there is no key present.

Sounds to me that there are android bugs on your device that prevent the app from reading it's key. As the app cannot read it, it asks you to generate a new one. There have been reports about such behavior before. I fear there is not much I can do for you.

**Comment by OmlineEditor** [comment]
> Sounds to me that there are android bugs on your device that prevent the app from reading it's key. As the app cannot read it, it asks you to generate a new one. There have been reports about such behavior before. I fear there is not much I can do for you.

Everything works fine, but sometimes the described case occurs when the program asks to generate a key. There is a suspicion that the program does not work correctly if you run it without Internet access (everything is turned off wifi is turned off. 3G is also disabled) and then connect to the Internet.

**Comment by wolpi** [comment]
> if you run it without Internet access

I could not reproduce that

**Comment by OmlineEditor** [comment]
perhaps there is another condition, I do not know because I have it happens spontaneously.

**Comment by berhem-taher** [comment]
i could reproduce this way (tested on multiple devices):
1. Apply these settings:
    - Start on open: true.
    - Server(s) to be started: "SFTP only" or "FTP and SFTP"
    - Anonymous Login: true.
    - Password: is set.
    - Everything else's Default.
    - Generate keys
2. Close the app, and remove it from the recent apps.
3. Open the app, it will ask to generate new keys. If you accept _Server starts_
4. Close the app, and remove it from the recent apps.
5. Open the app, it will ask you again.
Here it is.
Reapeat step 4. & 5.
@OmlineEditor , can you confirm this?

**Comment by wolpi** [comment]
There was a bug when 'start on open' ist set that caused re-generation of keys on each start
