### ISSUE TITLE
Big files corruption

### ISSUE THREAD

**Issue by Hikari-no-Tenshi** [wolpi/prim-ftpd#206]
For some time (don't know exactly when it started) when i downloading big files (faced it with files size more than 50MB) from Android Phone to Windows PC files appears corrupted.
I've tried different FTP clients and tried to disable Antivirus on PC. Tried binary and text transfer type.

**Comment by wolpi** [comment]
I've not been able to reproduce this.
Can you share logs?
From client and server?

**Comment by Hikari-no-Tenshi** [comment]
Few days i have no issues in transferring files.
Don't know what happened. This issue suddenly appeared and now suddenly disappeared.
Before i had tried different things (disable firewall and antivirus, changing FTP Client, text and binary transfer, keep screen on) but big files was always corrupted.
If this issue will back again i will post logs.

**Comment by wolpi** [comment]
Okay, for now I'm closing this
