### ISSUE TITLE
Quick Settings Tile Security Enhancement

### ISSUE THREAD

**Issue by berhem-taher** [wolpi/prim-ftpd#208]
I was thinking to have an option to require the device to be unlocked to start/stop the server through the quick setttings service.

This may benefit by preventing unwanted state changes by people other than the user, or by accedintal touches on the lock screen.

Excuse my java, Java is not my mother tongue.
Here's some of what needs to be changed, i'll try to implement the rest of it:

```Java
@Override
    public void onClick() {
        logger.debug("onClick");
        super.onClick();

        if(isLocked()){
            unlockAndRun(
                new Runnable(){
                    @Override
                    public void run() {
                        toggle();
                    }
                }
            );
        }
        updateTile();
    }
    private void toggle(){
        boolean isActive = isActive();
        if(isActive) {
            // Stop service if it is already running.
            ServicesStartStopUtil.stopServers(this);
        } else {
            // Start FTP service.
            ServicesStartStopUtil.startServers(this);
        }
    }
```

**Comment by wolpi** [comment]
Oh yes, that absolutely makes sense. There are surly some users who love current behavior, to be able to start/stop server when screen is locked. I will add a preference for that when you are finished. Would you like to turn this into a pull request?

**Comment by berhem-taher** [comment]
I added a preference and its stuff.
Tell me what needs to be made/fixed.

**Comment by wolpi** [comment]
It's great now :smile:
