### ISSUE TITLE
Please add a light theme

### ISSUE THREAD

**Issue by wp9015362** [wolpi/prim-ftpd#21]
Hello,

currently primitive ftpd only has a dark theme.

Would there be any chance you could also add a light theme?

It would be much appreciated.

Regards

**Comment by wolpi** [comment]
As you can see on the generated comments I implemented this ;)

Actually it was a little tricky as android has bugs when the theme of PreferencesActivity is changed programmatically.

**Comment by wp9015362** [comment]
Thank you very much.

The light theme looks a lot better than the dark theme IMHO.

As such I would suggest to make primitve ftpd default to the light theme.

But just saying :wink:.
