### ISSUE TITLE
Website downloader file naming issues

### ISSUE THREAD

**Issue by HT-7** [wolpi/prim-ftpd#214]
Primitive FTPd has a convenient integrated basic website downloader, but it has a few issues.

The name seems to be selected from the name of the current subpage (after the slash), without URL parameters.

However, there is nothing after the slash if there is a home page or there are **only** URL parameters.

Error:
> could not download: length=0, index=-1

Another problem is:

When downloading the page a second time (i.e. because it has updated), then the existing HTML file will be overwritten.

Overwriting by default is a poor behaviour (not programmer's fault but default in UNIX, as far as I know, thus only a result of neglect), which has caused me to lose my backed up log by 3C Battery Monitor Widget (file name: `bmw_history.txt`).

I suggest that, if the file name exists, rename the new files to `example(1).html`, `example(2).html`, and continuing.

Google Chrome for Android allows MHTML downloading, but not in Incognito mode. Mozilla Firefox for Android allows PDF downloading, but PDF is not quite a website format (better than nothing, obviously).

**Comment by wolpi** [comment]
Interesting that you found this feature :smile:. I added it some time ago when download features of browsers did not work as I needed for a specific site. That code is surly not perfect. I just made it work for my specific case back then.

As you can see by referenced commit: There was already some code in this app to generate unique filenames. I refactored it to be usable for this case, too.

Can you share your URL which didn't work?

**Comment by HT-7** [comment]
> Can you share your URL which didn't work?

* https://example.org/
* https://example.org/?no&text&before&first_question_mark&example=1

**Comment by wolpi** [comment]
Should work fine now. If no filename can be derived from URL a timestamp is used as filename.
