### ISSUE TITLE
Suggestion: Specific folder sharing

### ISSUE THREAD

**Issue by Javanmardi** [wolpi/prim-ftpd#221]
I suggest a specific folder sharing method in which the user can choose the target folder to share. The current method shares the whole internal storage or SD-Card (in SAF option) which is totally fine in a private networks but it is a disaster in a public area when the user wants to grant access to a specific file (a picture or video) to a groups of people.
This would allow a safe and secure connection between the host and clients.

**Comment by wolpi** [comment]
There are already two ways to achieve that:
* With SAF you can choose a folder. Only it's content (files and subfolders) are shared. You don't need to share whole sd-card.
* Single files can be shared via 'quick share' available in android's sharing system.

**Comment by Javanmardi** [comment]
I'm afraid it's quiet true however I could not confirm that based on the documentation. I believe I should have read the SAF documentations.
I suggest the current "Android Storage Access Framework" option displays the target folder as a tag to prevent redundant confirmation by the user. In that manner the user won't need to check the folder in the future.
Also single file sharing does not provide any information on the program's main interface [or I didn't find it] about which file is being shared at hand. It just notify on a notification bubbles which does not last very long.
I must confess the text log files do provide these information but a simple current task table would be much nicer.

**Comment by wolpi** [comment]
> I suggest the current "Android Storage Access Framework" option displays the target folder as a tag to prevent redundant confirmation by the user.

Well, the app shows all information it gets from android. That is a SAF URL starting with content://. Selected directory is visible as part of path of that URL. That is how android works :neutral_face:


> Also single file sharing does not provide any information on the program's main interface

Yes, there is currently no information displayed about that. I'll have a look how/if something can be done about it.

**Comment by Javanmardi** [comment]
> Well, the app shows all information it gets from android. That is a SAF URL starting with content://. Selected directory is visible as part of path of that URL. That is how android works 😐

Oh boy, Android is the worst in addressing a folder. It's like `content://com.android...`. It's even worst than Windows! However, I believe there was a way to mask the address therefore when it refers to `content://com.android.externalstorage.documents/tree/SOME_CODE` it just translates it to `External Storage` or `SD Card`. The only problem is it I couldn't find it!

> Yes, there is currently no information displayed about that. I'll have a look how/if something can be done about it.

Thanks! Can't wait to try it!

**Comment by wolpi** [comment]
Release will be available soon
