### ISSUE TITLE
Version 6.6 SFTP connection problems 

### ISSUE THREAD

**Issue by ms0087** [wolpi/prim-ftpd#223]
Hi,

the new version 6.6 doesn't connect with my PC via SFTP, the login-informations ("Anmeldeinformationen" in my FTP-client) are not acceptet. I had to go back to 6.5 (using the backup) and it works again.

I am using Lineage 17.1 on Samsung S4 and Windows 10 (with an old version of WS_FTP).

Best regards
Martin

**Comment by wolpi** [comment]
Which protocol do you use (ftp oder sftp)?
Which auth mechanism do you use (username/password, anonymous or public key)?
Can you share logs and screenshots of client and server?

**Comment by ms0087** [comment]
Am Dienstag, 22. Dezember 2020, 12:48 Uhr, schrieb wolpi:

> Which protocol do you use (ftp oder sftp)?
> Which auth mechanism do you use (username/password, anonymous or public key)?
> Can you share logs and screenshots of client and server?

I use SFTP with username and password.

I attach logs and screenshots of server and client. The complete client's message is:
"Anmeldefehler

Der Server hat Ihre Anmeldeinformationen zurückgewiesen. Geben Sie Ihren
Benutzernamen und Ihr Kennwort noch einmal ein und klicken Sie auf OK, um noch
einmal einen Verbindungsaufbau zu versuchen.

Aktivieren Sie die Option Anmeldeinformationen speichern, um die
Anmeldeinformationen für Ihren Server zu aktualisieren und zu speichern."

Best regards

Martin

**Comment by monolifed** [comment]
I have the same issue. I am trying to connect to the android device from linux but it keeps asking password.
I am using user/password with sftp only. It was running smoothly with 6.5 until the latest google play update to 6.6.
I switched to fdroid version (since it is still at 6.5) as a work around.

**Comment by bluebrother** [comment]
I've been running into the same issue. sftp only, username/password auth. F-Droid now also has 6.6, but still allows installing the older 6.5.

Output snippets below from running `sftp -vvv` (no relevant differences spotted for the rest of the output). Seems something with the response for the keyboard-interactive is off? At least for 6.5 the response is packet type 52, while with 6.6 it's 51.

### With 6.5 (F-Droid version)

    Password authentication
    debug2: input_userauth_info_req: num_prompts 1
    Password: 
    debug3: send packet: type 61
    debug3: receive packet: type 52
    debug1: Authentication succeeded (keyboard-interactive).
    Authenticated to 192.168.11.236 ([192.168.11.236]:2222).

### With 6.6 (Google Play version, but also seen it with F-Droid)

    Password authentication
    debug2: input_userauth_info_req: num_prompts 1
    Password: 
    debug3: send packet: type 61
    debug3: receive packet: type 51
    debug1: Authentications that can continue: password,keyboard-interactive
    debug2: userauth_kbdint
    debug3: send packet: type 50
    debug2: we sent a keyboard-interactive packet, wait for reply
    debug3: receive packet: type 60
    debug2: input_userauth_info_req
    Password authentication
    debug2: input_userauth_info_req: num_prompts 1
    (...)

**Comment by klausmaus** [comment]
Same Problem connecing sftp and if i connecting ftp, i see a empty folder only

**Comment by wolpi** [comment]
Has been fixed, a new version will be available shortly

**Comment by klausmaus** [comment]
I have tested the fix, work fine!

**Comment by wolpi** [comment]
good to hear :smile:
