### ISSUE TITLE
Root mode file transfer results in 0 byte files

### ISSUE THREAD

**Issue by Sora3100** [wolpi/prim-ftpd#224]
Plain old filesystem seems to be working as expected, however with Super user mode, file listing works properly, but any file I attempt to transfer just results in 0 bytes.
My phone is Xperia Z5 Compact running stock 7.1.1 
[Log](https://github.com/wolpi/prim-ftpd/files/5759140/prim-ftpd-log-2021-01-01-16-53-49.zip)
Also, happy new years!

This may be the cause?
dd exit code:   '127', error stream: '/system/bin/sh: dd if=/storage/emulated/0/recovery.img:   not f...

**Comment by wolpi** [comment]
Happy new year :tada: 

This is a bad situation. Obviously there is some issue with invoking `dd` command. But we cannot see full error message :sob:. Code has been changed to improve logging. That will be included in next version.

Can you open a shell on your phone and invoke that command interactively?

**Comment by Sora3100** [comment]
This is the result:
![Screenshot_20210106-125139](https://user-images.githubusercontent.com/18172557/103765856-28484d00-501e-11eb-892a-51cb2e652f0c.png)

**Comment by wolpi** [comment]
Ok, so that works. 
What are the outputs of these commands?
* `which dd`
* `which sh`
* `ls -lh /system/bin/sh`
* `ls -lh /storage/emulated/0/recovery.img`
* `ls -lh $(which dd)`

**Comment by Sora3100** [comment]
<img src="https://user-images.githubusercontent.com/18172557/103823770-05945380-5073-11eb-9f95-20737d55247f.png" width="240" height="426">

**Comment by wolpi** [comment]
On your device `dd` is a link to `toolbox`, on others it is a link to `toybox`. That is a difference I noticed.

Here is a test build in which `dd` is called with absolute path. Can you test it? Just rename to .apk.

[primitiveFTPd-6.8-SNAPSHOT.zip](https://github.com/wolpi/prim-ftpd/files/5778433/primitiveFTPd-6.8-SNAPSHOT.zip)

**Comment by Sora3100** [comment]
[Log](https://github.com/wolpi/prim-ftpd/files/5778477/prim-ftpd-log-2021-01-06-23-23-23.zip)
Same problem.

**Comment by wolpi** [comment]
hhhmmm, could be related to the way to parameters to external processes are handled. As you might know `dd` is invoked via `su -c`. Currently the whole `dd` command, including it's parameters is passed as one string to `su -c`. Here is another test build that changes that. Here parameters of `dd` are passed as separate strings to `su -c`.


[primitiveFTPd-6.8-SNAPSHOT.zip](https://github.com/wolpi/prim-ftpd/files/5791875/primitiveFTPd-6.8-SNAPSHOT.zip)

**Comment by Sora3100** [comment]
That fixes it, it now works properly. Thanks!

**Comment by wolpi** [comment]
Ok, that change will be included in next version. I hope it does not cause issues with other devices (thinking of toolbox vs toybox)

**Comment by nestedone** [comment]
Hi, I meet this problem using version 6.7 and 6.8. Here're my log and some tests with v6.8. 
[Screenshot_2021-07-25-13-25-38-404_jackpal androidterm](https://user-images.githubusercontent.com/54736166/126899969-5ce2ac68-6023-47cd-9915-6311b6e78467.jpg)
[prim-ftpd-log-2021-07-25-20-49-54.zip](https://github.com/wolpi/prim-ftpd/files/6873918/prim-ftpd-log-2021-07-25-20-49-54.zip)

Find this in the log:
dd exit code: '1', error stream: 'Unknown id: if=/storage/emulated/0/0myroom/test.txt

**Comment by wolpi** [comment]
I've added logging to see what dd command is created exactly. Hopefully that helps to figure out what is going on here.
