### ISSUE TITLE
[Observation] Sending intent to StartServerAndExitActivity / StopServerAndExitActivity shows a flashing UI.

### ISSUE THREAD

**Issue by hedwinkoning-tomtom** [wolpi/prim-ftpd#229]
This week I ran into an issue that when I sent a intent to StartServerAndExitActivity I shaw a flashing UI. Never saw this before. It is not clear to me where this is coming from. I saw both on Android 10 and 11 so does not seem to relate to the android version. Only thing I could think of is a change in the androidx libraries. 

Not sure if this is caused by the Samsung system software, I only have samsung device so can't tell.

For now I added a Theme.NoDisplay to StartServerAndExitActivity and StopServerAndExitActivity in the manifest but am not sure if this solves it. 

Anyone else seen this also or knows if a theme needs to added specifically?

**Comment by wolpi** [comment]
I've seen this flash some times. E.g. in simulator this happens frequently. Using Theme.NoDisplay is something I can try to see if it helps.

**Comment by wolpi** [comment]
Theme.NoDisplay  has been added to master to avoid that flash
