### ISSUE TITLE
Icon on main screen toolbar?

### ISSUE THREAD

**Issue by wp9015362** [wolpi/prim-ftpd#23]
Hello,

I noticed that on the [Google Play Store screenshots](https://play.google.com/store/apps/details?id=org.primftpd), the primitive ftpd main screen toolbar shows the primitive ftpd icon, see:

![Image](https://cloud.githubusercontent.com/assets/7558360/8765313/93167cbe-2e06-11e5-97e2-9bcd26790699.png)

However, I have primitive ftpd installed and it does not show the icon on the main screen toolbar.

Tested on LG G2 running latest LG stock ROM (Android 5.0.2 Lollipop).

I'm just wondering:

Is this normal (i.e. the Google Play Store simply shows some older screenshots)?

Or is it a bug?

Regards

**Comment by wolpi** [comment]
Hmm. Might be an issues with some devices. On the other hand: I don't upate the screenshots on each release, so it might be that they are outdated. I'll have a look at it.

**Comment by wolpi** [comment]
That icon should be there. It is present on my devices and in android simulator for android 4 and 5. That seems to be an issue with LG costumizations in android 5 :(

**Comment by wp9015362** [comment]
Well, I don't think it's caused by the LG ROM.

Because on the very same ROM, I am running some other apps which do show their icon in their toolbar.

TextSecure for example shows it's icon in the toolbar:

https://github.com/WhisperSystems/TextSecure
https://play.google.com/store/apps/details?id=org.thoughtcrime.securesms

And that's just one example.

**Comment by wolpi** [comment]
Well, as I said before: the icon shows up everywhere I have tested. I could imagine that the LG ROM expects another resolution or something like that. As I cannot reproduce it it is hard to do something about it.

**Comment by wolpi** [comment]
I had a short look at the TextSecure repo. They provide the icon in two more resolutions. I added them as well and hope it makes the icon show up on your device :pray:

**Comment by wp9015362** [comment]
@wolpi :

Yeah, I saw it:

https://github.com/wolpi/prim-ftpd/commit/b55c7e02657ed3250931689efa80f618cd33a4f6

But unfortunately the icon still does not show up in the toolbar in primitive ftpd version 3.2.

Since the file is called "ic_launcher.png":

The icon does show up in the launcher and everywhere else.

But it's not showing up on the main screen toolbar. I mean the toolbar where the play/pause icon and the wrench icon for the settings is.

By the way:

The TextSecure icon that is being used for the launcher is not the same icon that is being used in the TextSecure main screen toolbar (at least it does not have the same color):

https://play.google.com/store/apps/details?id=org.thoughtcrime.securesms

So maybe they are actually using two different icons. Or they do the main screen toolbar icon completely different. Don't know.

Regards

**Comment by wp9015362** [comment]
PS:

@wolpi :

I just noticed that there are new screenshots of primitive ftpd on the Google Play Store, see:

https://play.google.com/store/apps/details?id=org.primftpd

Have you added those screenshots?

Because on those screenshots the icon on the main screen toolbar is also missing :wink:.

See:

https://lh3.googleusercontent.com/RwUUkqgkHhU_aRUrvndLQvV3F9LgJxdmTcfvw8PETud4qWcVHBDYwAADUxKDeqxV2w=h900
https://lh3.googleusercontent.com/Lh5CoEzayy3VaGST1xX_dG2JoijxTS46APSPnLsU2ymmYdeuV4V-6hJJl0jj7GdaGw=h900

:wink:

Regards

**Comment by wp9015362** [comment]
PPS:

@wolpi :

Apart from the screenshots which show that the icon is missing, there are still some more screenshots on the Google Play Store which do show the icon.

But the whole theme in those screenshots seems to look different.

Maybe in Android 4.x the icon is showing up but on Android 5.x it does not and has a completely different theme with different colors?

Why do the themes differ in Android 4.x and Android 5.x?

It doesn't have to be that way.

For example:

When I was still running Android 4.4.2 on my LG G2, TextSecure still did have the Material Design theme.

So the Material Design has to be available on Android 4.x as well.

But it seems like primitive ftpd only uses Material Design on Android 5.x and also doesn't seem to show the mainscreen toolbar icon on Android 5.x.

At least judging by those screenshots from the Google Play Store.

Regards

**Comment by wolpi** [comment]
:laughing: 
OK so it is just the material design stuff.

Currently I stick to android defaults for this. That means hollo-design on android 4 and material-design on android 5. And per default material design does not show the icon in the action bar.

So I can have a look at these things:
- how to use material design with android 4 (not sure anymore but I think android does not provide it but the app must do it manually)
- how to put an icon in action bar with material design

**Comment by wp9015362** [comment]
I would suggest a third option:

- Maybe just leave everything as is and resolve the issue

:wink:

At the end of the day, not even the official Google Material Design apps like Gmail, YouTube, Hangouts etc. show an icon/logo in their toolbar.

So if primitive ftpd does not show an icon/logo in the toolbar with Material Design either, that would probably just be fine AFAICT.

So maybe just leave it as is and resolve.

But thanks for having looked into it.

Regards

**Comment by wolpi** [comment]
> Maybe just leave everything as is and resolve the issue

Yay, sticking to defaults is great :joy:

I guess this is a lesson in communication and misunderstanding :stuck_out_tongue_closed_eyes:

Will have a look at it anyway. Just out of coriosity.

**Comment by wolpi** [comment]
As discussed in #28: icon will not be shown.
