### ISSUE TITLE
[FR] Add Read-only mode to plain old file system 

### ISSUE THREAD

**Issue by NightMachinary** [wolpi/prim-ftpd#230]
The read-only SAF mode doesn’t work for me. Can you add an option to make the plain old file system mode read-only?

I also don’t understand why setting a custom directory as the root of the ftp server should require Android APIs?

Thank you very much!

**Comment by NightMachinary** [comment]
This FR is a subset of https://github.com/wolpi/prim-ftpd/issues/217 . Feel free to close it.

**Comment by wolpi** [comment]
Well, yes, with #217 this is already worked on
