### ISSUE TITLE
[v6.7] SFTP connexion still opened after having  pressed "stop" !

### ISSUE THREAD

**Issue by mmtsuchi** [wolpi/prim-ftpd#231]
Hello,
To reproduce the bug : 
1) start Primitive FTPD on android 
1.1) set SFTP only with custom user,  port 1234 (or whatever you like) and password (****)
anonymous connexion = false
password presence = true
Auth. public key = false

2) On linux, start a sftp client : 
`sftp sftp://user@192.168.1.49:1234
OpenSSH_8.2p1 Ubuntu-4ubuntu0.2, OpenSSL 1.1.1f  31 Mar 2020
Password authentication
Password: 
Authenticated to 192.168.1.49 ([192.168.1.49]:1234).
Connected to 192.168.1.49.`

**Stop the Primitive sftp server by pressing the "stop" button.

SFTP commands still continue to work ! :**
`sftp> ls
Android                          DCIM                             LOST.DIR                         System Volume Information
`

_Client action log still show messages._

**Comment by wolpi** [comment]
should be fixed
