### ISSUE TITLE
Unable to start SFTP-server: "UserAuthFactories not set" although authorized_keys file in place

### ISSUE THREAD

**Issue by johays** [wolpi/prim-ftpd#232]
### Unable to start SFTP-server: "UserAuthFactories not set" although authorized_keys file in place

**Error-messages:**

- "_Public key for key authentication could not be read. Check logs._"
- "_Server could not be started! Error message:UserAuthFactories not set_"

**Android version:** 5.1.1
**Install-method:** F-droid
**Installed version of prim-ftp:** 6.7

**Steps to reproduce:**

- Fresh install from F-droid repository
- Create .ssh folder in /storage/emulated/0/Android/data/org.primftpd/files/.ssh
- Copy pub-key file from computer to .ssh-folder on phone, rename to "authorized_keys"
- Start SFTP-server in app

Does Prim-FTP only support very specific key-formats? If so, how should I form my ssh-keygen command to make a functional keypair and afterwards export the pub-key to an authorized_keys file?
(SSH works on my machine, I use it all the time, the keypair is fine)

content authorized_keys file:
_ssh-rsa [REDACTED, 4096 BIT KEYSTRING]== user@machine_

**Comment by wolpi** [comment]
Hhhhmmm, this should work.

There is likely an exception in log which should tell us what goes wrong. Can you share it?

**Comment by johays** [comment]
Here's the log:

`"2021-04-07 01:57:07.2";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"onCreateOptionsMenu()";"";
"2021-04-07 01:57:07.2";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"displayServersState()";"";
"2021-04-07 01:57:07.2";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"checkServicesRunning()";"";
"2021-04-07 01:57:07.2";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"updateButtonStates()";"";
"2021-04-07 01:57:07.3";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"onResume()";"";
"2021-04-07 01:57:07.3";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"displayServersState()";"";
"2021-04-07 01:57:07.3";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"checkServicesRunning()";"";
"2021-04-07 01:57:07.3";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"updateButtonStates()";"";
"2021-04-07 01:57:07.4";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"network connectivity changed, data str: 'null', action: 'android.net.conn.CONNECTIVITY_CHANGE'";"";
"2021-04-07 01:57:08.8";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"onOptionsItemSelected()";"";
"2021-04-07 01:57:08.8";"TRACE";"org.primftpd.PrimitiveFtpdActivity";"handlePrefs()";"";
"2021-04-07 01:57:08.8";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"onPause()";"";
"2021-04-07 01:57:08.8";"DEBUG";"org.primftpd.prefs.FtpPrefsFragment";"onCreate()";"";
"2021-04-07 01:57:17.4";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"onStart()";"";
"2021-04-07 01:57:17.4";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"loadPrefs()";"";
"2021-04-07 01:57:17.4";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"got anonymousLogin: false";"";
"2021-04-07 01:57:17.4";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"got userName: user";"";
"2021-04-07 01:57:17.4";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"got password: null";"";
"2021-04-07 01:57:17.4";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"got startDir: /storage/emulated/0";"";
"2021-04-07 01:57:17.4";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"got announce: false";"";
"2021-04-07 01:57:17.4";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"got announceName: primitive ftpd";"";
"2021-04-07 01:57:17.4";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"got wakelock: true";"";
"2021-04-07 01:57:17.4";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"got pubKeyAuth: true";"";
"2021-04-07 01:57:17.4";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"got 'which server': SFTP";"";
"2021-04-07 01:57:17.4";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"got ftpPassivePorts: 5678";"";
"2021-04-07 01:57:17.5";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"got idleTimeout: 0";"";
"2021-04-07 01:57:17.5";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"got 'port': 12345";"";
"2021-04-07 01:57:17.5";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"got 'secure port': 1234";"";
"2021-04-07 01:57:17.5";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"got showConnectionInfo: true";"";
"2021-04-07 01:57:17.5";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"got 'StorageType': PLAIN";"";
"2021-04-07 01:57:17.5";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"got safUrl: ";"";
"2021-04-07 01:57:17.5";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"got allowedIpsPattern: ";"";
"2021-04-07 01:57:17.5";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"got 'logging': TEXT";"";
"2021-04-07 01:57:17.5";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"onResume()";"";
"2021-04-07 01:57:17.5";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"displayServersState()";"";
"2021-04-07 01:57:17.5";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"checkServicesRunning()";"";
"2021-04-07 01:57:17.5";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"updateButtonStates()";"";
"2021-04-07 01:57:17.5";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"network connectivity changed, data str: 'null', action: 'android.net.conn.CONNECTIVITY_CHANGE'";"";
"2021-04-07 01:57:19.4";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"onOptionsItemSelected()";"";
"2021-04-07 01:57:19.4";"TRACE";"org.primftpd.PrimitiveFtpdActivity";"handleStart()";"";
"2021-04-07 01:57:19.4";"TRACE";"org.primftpd.util.ServicesStartStopUtil";"startServers()";"";
"2021-04-07 01:57:19.4";"TRACE";"org.primftpd.PrimitiveFtpdActivity";"isKeyPresent() -> true";"";
"2021-04-07 01:57:19.4";"DEBUG";"org.primftpd.util.ServicesStartStopUtil";"going to start sshd";"";
"2021-04-07 01:57:19.5";"DEBUG";"org.primftpd.services.SshServerService";"onStartCommand()";"";
"2021-04-07 01:57:19.5";"DEBUG";"org.primftpd.services.ServerServiceHandler";"handleMessage()";"";
"2021-04-07 01:57:19.5";"DEBUG";"org.primftpd.services.ServerServiceHandler";"starting sftp-ssh server";"";
"2021-04-07 01:57:19.5";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"got ServerStateChangedEvent";"";
"2021-04-07 01:57:19.5";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"handling event 'org.primftpd.events.ServerStateChangedEvent', offset: 1617753439520 ms";"";
"2021-04-07 01:57:19.5";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"displayServersState()";"";
"2021-04-07 01:57:19.5";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"checkServicesRunning()";"";
"2021-04-07 01:57:19.5";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"updateButtonStates()";"";
"2021-04-07 01:57:19.5";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"posting ServerInfoRequestEvent";"";
"2021-04-07 01:57:19.5";"DEBUG";"org.primftpd.services.SshServerService";"got ServerInfoRequestEvent";"";
"2021-04-07 01:57:19.5";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"got ServerInfoResponseEvent, quickShareFilename: null";"";
"2021-04-07 01:57:19.5";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"handling event 'org.primftpd.events.ServerInfoResponseEvent', offset: 31 ms";"";
"2021-04-07 01:57:19.5";"TRACE";"org.apache.sshd.common.util.SecurityUtils";"getCipher(AES/CTR/NoPadding) -> javax.crypto.Cipher";"";
"2021-04-07 01:57:19.5";"TRACE";"org.apache.sshd.common.util.SecurityUtils";"getCipher(AES/CTR/NoPadding) -> javax.crypto.Cipher";"";
"2021-04-07 01:57:19.5";"TRACE";"org.apache.sshd.common.util.SecurityUtils";"getCipher(AES/CTR/NoPadding) -> javax.crypto.Cipher";"";
"2021-04-07 01:57:19.5";"TRACE";"org.apache.sshd.common.util.SecurityUtils";"getCipher(RC4) -> javax.crypto.Cipher";"";
"2021-04-07 01:57:19.5";"TRACE";"org.apache.sshd.common.util.SecurityUtils";"getCipher(RC4) -> javax.crypto.Cipher";"";
"2021-04-07 01:57:19.5";"TRACE";"org.apache.sshd.common.util.SecurityUtils";"getCipher(AES/CBC/NoPadding) -> javax.crypto.Cipher";"";
"2021-04-07 01:57:19.5";"TRACE";"org.apache.sshd.common.util.SecurityUtils";"getCipher(DESede/CBC/NoPadding) -> javax.crypto.Cipher";"";
"2021-04-07 01:57:19.5";"TRACE";"org.apache.sshd.common.util.SecurityUtils";"getCipher(Blowfish/CBC/NoPadding) -> javax.crypto.Cipher";"";
"2021-04-07 01:57:19.6";"TRACE";"org.apache.sshd.common.util.SecurityUtils";"getCipher(AES/CBC/NoPadding) -> javax.crypto.Cipher";"";
"2021-04-07 01:57:19.6";"TRACE";"org.apache.sshd.common.util.SecurityUtils";"getCipher(AES/CBC/NoPadding) -> javax.crypto.Cipher";"";
"2021-04-07 01:57:19.6";"INFO";"org.primftpd.services.SshServerService";"loaded 0 keys for public key auth";"";
"2021-04-07 01:57:19.7";"ERROR";"org.primftpd.services.SshServerService";"could not start server";"java.lang.IllegalArgumentException: UserAuthFactories not set
	org.apache.sshd.SshServer.checkConfig() line: 227
	org.apache.sshd.SshServer.start() line: 273
	org.primftpd.services.SshServerService.launchServer() line: 240
	org.primftpd.services.ServerServiceHandler.handleStart() line: 79
	org.primftpd.services.ServerServiceHandler.handleMessage() line: 59
	android.os.Handler.dispatchMessage() line: 102
	android.os.Looper.loop() line: 135
	android.os.HandlerThread.run() line: 61";
"2021-04-07 01:57:19.7";"DEBUG";"org.primftpd.services.SshServerService";"onDestroy()";"";
"2021-04-07 01:57:19.7";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"got ServerStateChangedEvent";"";
"2021-04-07 01:57:19.7";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"handling event 'org.primftpd.events.ServerStateChangedEvent', offset: 186 ms";"";
"2021-04-07 01:57:19.7";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"displayServersState()";"";
"2021-04-07 01:57:19.7";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"checkServicesRunning()";"";
"2021-04-07 01:57:19.7";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"updateButtonStates()";"";
"2021-04-07 01:57:19.7";"DEBUG";"org.primftpd.services.ServerServiceHandler";"handleMessage()";"";
"2021-04-07 01:57:19.7";"DEBUG";"org.primftpd.services.ServerServiceHandler";"wake lock already released (sftp-ssh)";"";
"2021-04-07 01:57:19.7";"DEBUG";"org.primftpd.services.ServerServiceHandler";"stopSelf (sftp-ssh)";"";
"2021-04-07 01:57:19.7";"TRACE";"org.primftpd.util.ServicesStartStopUtil";"updateNonActivityUI()";"";
"2021-04-07 01:57:19.7";"DEBUG";"org.primftpd.util.ServicesStartStopUtil";"updateWidget()";"";
"2021-04-07 01:57:19.7";"DEBUG";"org.primftpd.util.ServicesStartStopUtil";"removeStatusbarNotification()";"";
"2021-04-07 01:57:19.7";"DEBUG";"org.primftpd.remotecontrol.TaskerReceiver";"sending tasker RequestQueryCondition";"";
"2021-04-07 01:57:23.5";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"onPause()";"";
`

**Comment by wolpi** [comment]
Ok, no exception. It just says: 0 keys loaded.
That probably means file is not found, maybe you have an typo in path?
I just verified that loading keys from 
/storage/emulated/0/Android/data/org.primftpd/files/.ssh/authorized_keys
works.
You could also place your key in this path, if your android version permits it:
/storage/emulated/0/.ssh/authorized_keys
(that is the older path used by this app, in newer android versions we are forced to use the longer one)

**Comment by johays** [comment]
I got it working: the authorized_keys file got corrupted during transfer. I used Signal to transfer the file. 
After copy/pasting the key into a textfile on the device, it resolved the issue. I tested both of the above locations, and both seem to work.
Thank you a lot! 

Closing issue.
