### ISSUE TITLE
Android 11's scoped storage mechanism impedes access to Android/data

### ISSUE THREAD

**Issue by bgamari** [wolpi/prim-ftpd#233]
It appears that Android 11's scoped storage mechanism essentially renders most file management utilities useless by disallowing access to other apps' data (particularly, anything in the `Android/data` directory (e.g. see <https://www.reddit.com/r/android_beta/comments/h8fnol/android_11s_new_file_access_restrictions_scoped/>).

Supposedly Google will soon [allow](https://www.xda-developers.com/android-11-all-files-access-permission-form/) apps to [request](https://support.google.com/googleplay/android-developer/answer/10467955) access to all files. It's not clear how this affects an open-source application like `prim-ftpd` which (at least as far as I know) is primarily distributed via f-droid.

**Comment by wolpi** [comment]
It sounds to me that google controls new permission MANAGE_EXTERNAL_STORAGE just via play store. Apps on f-droid should be able to just use it.

As this app is available on play store, too, I intend to go through google's approval process. Let's see how that turns out. So far I did not receive mail for that.

**Comment by marook** [comment]
I've installed primftpd via f-droid and primftpd can't access files within Android/data directory. My phone runs Android 11.

**Comment by wolpi** [comment]
> primftpd can't access files within Android/data directory

yes, there has no action been taken so far to change that

**Comment by wolpi** [comment]
New version was just released, with new permission MANAGE_EXTERNAL_STORAGE. Google play did not complain so far. Let's see what happens.

**Comment by hedwinkoning** [comment]
The info if have read mentioned that  MANAGE_EXTERNAL_STORAGE is there for file manager type of applications. 
Scoped storage would not work for file manager type of applications.

**Comment by wolpi** [comment]
When apps are built with latest Android SDK (which is mandatory to publish on Play) new restrictions are enforced.That restricts this app heavily.

**Comment by wolpi** [comment]
Version 6.11 is now available in Google Play. For that release I had to explain why this app needs permission MANAGE_EXTERNAL_STORAGE.
Obviously the version went live and restrictions apply :sob:

**Comment by wolpi** [comment]
Added info about permission to readme. I'm closing this now.
