### ISSUE TITLE
Impossible to create folder or files on SD card

### ISSUE THREAD

**Issue by Build-0-Matic** [wolpi/prim-ftpd#235]
I'm having a serious problem on Android 9 (no root).
Prim-FTPD refuses to either create a folder or copy a file to the SD card.
When I copy to the internal memory, there are no problems.
I know it's not the tablet because CX File Explorer does it seamlessly.
FileZilla gives me a `Error:	Critical file transfer error` when I try and copy a file.
When I try and make a folder, I get the following
```
Command:	CWD /storage/EC57-379F/Music
Response:	250 Directory changed to /storage/EC57-379F/Music
Command:	MKD New directory
Response:	550 No permission to create /storage/EC57-379F/Music/New directory.
```

EC57-379F seems to be the formatting ID of the card.

I checked the permissions and it doesn't have Directory Access... I don't know if that's related. But it does have Storage permission.

**Comment by wolpi** [comment]
Which Storage-Type do you use?
For SD card it is important to use SAF.
Android does not allow to access SD card with filesystem API.

**Comment by Build-0-Matic** [comment]
Oh! That's why!
I just tried it and this fixed the problem. I was quite puzzled at first because it didn't show any folders to select from the start...

There should definitely be a bit better info like "Mandatory for SD card access" or something like that... would have saved me from asking a stupid question... 🤔

Thanks

**Comment by wolpi** [comment]
There is already a hint shown that SAF is needed for SD-card. It seems to be present in most languages.

**Comment by Build-0-Matic** [comment]
It was. But I just didn't think it was that important... It probably was a bit like those instructions nobody really reads.
