### ISSUE TITLE
[security] Do not log sensitive information at all

### ISSUE THREAD

**Issue by macias** [wolpi/prim-ftpd#237]
While posting logs for my previous issue I noticed logs contain plain text actual user info, and hashed (?) password. Such data should not be logged at all -- they are pieces of sensitive area and should be always kept secret. Only the fact the user/password is set or not. So the logs should at most read like:

    user: <set>
    password: <none>

**Comment by wolpi** [comment]
Well yes, even hashed password should not be logged.

Can already be avoided by using public key auth and no password at all.
