### ISSUE TITLE
Port 21 for FTP and port 22 for SFTP do not work

### ISSUE THREAD

**Issue by wp9015362** [wolpi/prim-ftpd#24]
Hello,

as far as I understand, the standard port for FTP is port 21 and the standard port for SFTP is port 22.

However, when I try to configure those ports in primitive ftpd, primitive ftpd throws the following error message:

"Port value is invalid. Resetting it to default."

Tested on LG G2 running latest LG stock ROM (Android 5.0.2 Lollipop).

Why is it doing this?

Regards

**Comment by wolpi** [comment]
That is because the linux kernel alows only the root user to open ports below ~1024 (not sure what the exact number is). So in theory it would work when your device is rooted. But many devices are not and I want to avoid app crashes due to linux internal security limitations.

**Comment by GHolk** [comment]
so primitive-ftpd does not support bind to 21,22 port, even if my android is rooted?

**Comment by wolpi** [comment]
Yes, it is not possible to bind to privileged ports. As you might know root on android still means java code is run as simple user. But apps may launch external processes as root and interact with their input-/output-streams. I don't see a way how port binding could be delegated to an external root process.
