### ISSUE TITLE
Network interface not selectable (firewall)

### ISSUE THREAD

**Issue by PietKnot** [wolpi/prim-ftpd#240]
Dear Wolpi,

the FTP-server works fine for me when the no-root firewall (VPN-based) is switched off.  When the firewall is switched op, the UI states the following network interfaces:

192.168,2,16 (wlan0)    - this one works on no firewall operation
10.0.8.1 (tun0)               - this one appears as soon as the firewall is active.

In the No-Root firewall, i do not see any activity and connection-requests are not passed to your app (on elder Android versions, my favorite simple FTP-server from Lutey  -not maintained anymore- did work with active firewall). This problem is also present in other FTP-server apps.

Is this an FTP-server issue, or should it be resolved by the NoRoot firewall (incoming packet)?

**Comment by wolpi** [comment]
Interesting question.
I could check APIs how and if an app could listen to specific interface.
Will take some time.

**Comment by PietKnot** [comment]
Wolpi,

the app that could do that was: https://apkpure.com/ftpserver/lutey.FTPServer

However, this one fails (not maintained anymore) with later Android versions as it also allows to only accept connections on specific Wlan-SSID's  (or "any") bit that check fails nowadays, thus looking for another "simple" one.  Anyhow: you could also specify on which interface it should work.

**Comment by wolpi** [comment]
There is now a preference to define IP address to bind to

**Comment by PietKnot** [comment]
where to download  . . . . update not on the play-store.

**Comment by wolpi** [comment]
There is no release yet that includes that change.
Probably there will be a release next week on f-droid.
With Google Play there are issues right now with newer SDK versions and Google's policies which version must be used and filesystem access. Thus it will take some more time until there will be a new version on Play.

**Comment by wolpi** [comment]
Now this is available on Google Play, too.
See #233 for restrictions in recent versions.
You may use app version 6.10 instead. It is available in f-droid and in GitHub releases.
