### ISSUE TITLE
Bug: Fails to copy data with Japanese letters!

### ISSUE THREAD

**Issue by lexterror** [wolpi/prim-ftpd#241]
Hi,

I'm trying to transfer an album with Japanese letters and it fails to copy!

Thank you!

**Comment by wolpi** [comment]
Hi,

I need more information on this, like:

Which protocol do you use (ftp or sftp)?
Which storage type (e.g. filesystem or SAF)?
Which client do you use?
Where are Japanese letters? In filenames?
Are there exceptions in log?
Can you share logs?
What exactly is the error?

**Comment by lexterror** [comment]
-Plain FTP no security
-I have Android11 with no SDcard (Google Pixel4A)
-AndFTP client Pro
-Japanese letters in filenames

The error is:

Upload failed: h.a.a.a.g.c: IOException caught while copying.

Thank you!

**Comment by lexterror** [comment]
It was andftp  causing the issue. Thank you!
