### ISSUE TITLE
cannot mount with sshfs: read: Connection reset by peer

### ISSUE THREAD

**Issue by eduardosm** [wolpi/prim-ftpd#243]
Trying to use sshfs will fail

```
~$ sshfs user@192.168.11.137:/ -p 1234 ~/mnt/sshfs
read: Connection reset by peer
```

The "Client Action Log" is empty

**Comment by wolpi** [comment]
It works for me.

Which storage type do you use (e.g. filesystem, root, SAF)?

Can you share server-logs?

**Comment by eduardosm** [comment]
I tried both filesystem and read-only SAF.

Here is a log: [prim-ftpd-log-2021-10-17-19-45-52.csv](https://github.com/wolpi/prim-ftpd/files/7360556/prim-ftpd-log-2021-10-17-19-45-52.csv)

**Comment by eduardosm** [comment]
> Try adding `-o HostKeyAlgorithms=+ssh-rsa -o PubkeyAcceptedAlgorithms=+ssh-rsa` to sshfs.

Thank you. Passing these parameters to sshfs did not actually work (it tried to pass them to fuse instead of ssh), but putting them in `ssh_config` worked.

**Comment by wolpi** [comment]
see #244
