### ISSUE TITLE
Is it clean by #log4j ?

### ISSUE THREAD

**Issue by pflegende** [wolpi/prim-ftpd#249]
Please don't be angry, sometimes sensitive data turning around our servers.
We like your tool and it's very useful.
:)

**Comment by wolpi** [comment]
There is no log4j in this app.

Used apache mina libraries use slf4j as logging-API and Android-logging is used as logging-implementation.

It's easy to look at dependencies in gradle files :)

**Comment by pflegende** [comment]
Great!
thx for the hint
:)

will do so in the other tools we use 
so it is very helpfull


merry Xmas
