### ISSUE TITLE
Please add an "About" section

### ISSUE THREAD

**Issue by wp9015362** [wolpi/prim-ftpd#25]
Hello,

would there be any chance you could add an "About" section to primitve ftpd which shows the version number and so on?

Maybe it could be placed at the bottom of the preferences?

Regards

**Comment by wolpi** [comment]
What would you like to see there beside the version number?

**Comment by wp9015362** [comment]
Mainly the version number.

Not sure, but maybe also things like developer information, license information, link to GitHub repo, link to [Google Play Store](https://play.google.com/store/apps/details?id=org.primftpd) for example?

Just some examples.

**Comment by wolpi** [comment]
Displaying the version causes still trouble as android seems to be buggy here. The system class PackageManager behaves not as documented, or I don't get it.

**Comment by wp9015362** [comment]
Well, several other apps, like Firefox:

https://play.google.com/store/apps/details?id=org.mozilla.firefox

or TextSecure for example:

https://github.com/WhisperSystems/TextSecure
https://play.google.com/store/apps/details?id=org.thoughtcrime.securesms

are able to show their version number in the app, so it should be possible.

A lot of apps show their version number directly in the app.

**Comment by wolpi** [comment]
Yes I know that apps do this :) 
I'm not saying it is not possible. I'm just saying the "official way" is not working (-> the before mentioned package manager). 
This is one issue that delays the release.

**Comment by wolpi** [comment]
Stupid me!
The package manager works fine, I just have to use it properly :innocent:

**Comment by wp9015362** [comment]
Thanks. Looks good :wink:.

**Comment by wp9015362** [comment]
@wolpi :

One little thing:

The F-Droid link is a little bit longer than it needs to be.

You are using (probably coming from searching for "ftp"):

https://f-droid.org/repository/browse/?fdfilter=ftp&fdid=org.primftpd

But the direct link would be:

https://f-droid.org/repository/browse/?fdid=org.primftpd

Just saying :wink:.

Regards

**Comment by wp9015362** [comment]
PS:

@wolpi :

Also found some typos :relaxed: :

It says "Licence". Should be "License".

And it says "Github". Should be "GitHub".

:wink:

**Comment by wolpi** [comment]
> It says "Licence". Should be "License".

It is british english :grinning:


But yes, nasty details. Thanks for reporting it.

**Comment by wolpi** [comment]
Fixed
