### ISSUE TITLE
file is corrupted after transferring

### ISSUE THREAD

**Issue by 7kilobytes** [wolpi/prim-ftpd#251]
Greeting everyone.

I was trying to transfer a file using primitive ftpd program and found that the md5 hash is a different from source.
Here is the history from the host:

```
Connected to 192.168.10.159
220 Service ready for new user.
Name (192.168.10.159:int): int
331 User name okay, need password for int.
Password:
230 User logged in, proceed.
Remote system type is UNIX.
ftp> put koler_v1.2.0.apk
227 Entering Passive Mode (192,168,10,159,22,46)
150 File status okay; about to open data connection.
226 Transfer complete.
7588912 bytes sent in 3.97 seconds (1.82 Mbytes/s)
ftp> quit
221 Goodbye.
int@kyler tmp 0 1.59 $ md5sum koler_v1.2.0.apk
c7da2e135c02b72f12fb14a34ee2ad4c  koler_v1.2.0.apk
int@kyler tmp 0 1.78 $
```

and here is the md5sum on the target device after transferring:

```
H4233:/storage/emulated/0/Download $ md5sum koler_v1.2.0.apk
5413227abf2dbf5f42a86b5b0f5f6ece  koler_v1.2.0.apk
H4233:/storage/emulated/0/Download $
```

I am using LOS 18.1 version.
The ftp client information:
```
int@kyler tmp 0 1.78 $ ftp --version
ftp (GNU inetutils) 2.2
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by many authors.
int@kyler tmp 0 1.54 $
```

**Comment by 7kilobytes** [comment]
BTW, I have forgotten to attach adb logcat output:
[primitive_ftpd.log](https://github.com/wolpi/prim-ftpd/files/7773979/primitive_ftpd.log)

**Comment by 7kilobytes** [comment]
I find myself apologizing, but I found that I have used ASCII transfer mode instead of binary one. Hence, this is not an issue.
Thanks

**Comment by wolpi** [comment]
ok, nothing more to say than: merry christmas

**Comment by P650SE** [comment]
Hey, I seem to have the same issue. Is there anywhere I can find the option to switch from ASCII to Binary? I have searched through the settings menu but I can't see this option anywhere.

Latest verson from F-Droid v6.16

**Comment by P650SE** [comment]
Hey, I seem to have the same issue. Is there anywhere I can find the option to switch from ASCII to Binary? I have searched through the settings menu but I can't see this option present.

Latest verson from F-Droid v6.16

**Comment by sp1ff** [comment]
Adding for those who find this via search: *how* do I select ASCII versus binary transfer mode? The daemon doesn't accept the `binary` command.

**Comment by wolpi** [comment]
Why would you want to change transfer mode?
I never saw issues with binary files.

**Comment by sp1ff** [comment]
Right-- I *wanted* binary mode. It wasn't clear to me which mode was being used at the time.
