### ISSUE TITLE
authorized_keys should ignore garbage

### ISSUE THREAD

**Issue by ole-tange** [wolpi/prim-ftpd#254]
I still deal with `ssh1`, so my `authorized_keys` contains lines like:
~~~
2048 65537 272128824450512859085078817734... foo@bar
~~~
This unfortunately makes prim-ftpd ignore the full `authorized_keys`.

It would be nice if it simply ignored the line - preferably with a warning, but that it read the rest of the lines.

**Comment by wolpi** [comment]
oh yes, that makes absoluelty sense
