### ISSUE TITLE
[INFO] Android 12 removes many bouncycastle algo in favor of conscrypt

### ISSUE THREAD

**Issue by hedwinkoning** [wolpi/prim-ftpd#256]
Below information about changes in Android 12 and security. I bumped into this issue because a primftpd running on a phone didn't start because of security exception. This was an older version. Latest seem to work fine for now.

The ticket is not about the security issue but about plans to replace boucycastle with conscript? Like to avoid the next bouncycastle issue when the next android update.  

[BouncyCastle](https://www.bouncycastle.org/) implementation removed

Android 12 removes many BouncyCastle implementations of cryptographic algorithms that were previously deprecated, including all AES algorithms. The system instead uses the [Conscrypt](https://github.com/google/conscrypt) implementations of these algorithms.

This change affects your app if any of the following are true:

    Your app uses 512-bit key sizes. Conscrypt doesn't support this key size. If necessary, update your app's cryptography logic to use different key sizes.

    Your app uses invalid key sizes with [KeyGenerator](https://developer.android.com/reference/javax/crypto/KeyGenerator). Conscrypt's implementation of KeyGenerator performs additional validation on key parameters, compared to BouncyCastle. For example, Conscrypt doesn't allow your app to generate a 64-bit AES key because AES only supports 128-, 192-, and 256-bit keys.

    BouncyCastle allows keys of invalid sizes to be generated, but later fails if these keys are used with a [Cipher](https://developer.android.com/reference/javax/crypto/Cipher). Conscrypt fails earlier.

    You initialize your Galois/Counter Mode (GCM) ciphers using a size other than 12 bytes. Conscrypt's implementation of [GcmParameterSpec](https://developer.android.com/reference/javax/crypto/spec/GCMParameterSpec) requires an initialization of 12 bytes, which NIST recommends.

**Comment by wolpi** [comment]
That was already an issue some time ago as conscrypt was initially introduced in android. That is the reason why code of mina ssh server was copied to this repo to be modified here.
Currently this app brings it's own copy of bouncycastle and avoids usage of java apis which are backed by a crypto provider defined by operating system.

You say the app does not work on android 12?
I'll have to check then ...

**Comment by hedwinkoning** [comment]
> That was already an issue some time ago as conscrypt was initially introduced in android. That is the reason why code of mina ssh server was copied to this repo to be modified here. Currently this app brings it's own copy of bouncycastle and avoids usage of java apis which are backed by a crypto provider defined by operating system.
> 
> You say the app does not work on android 12? I'll have to check then ...

Latest version is working fine. It was an older version that was used that was throwing a security exception hence I was wondering how to prevent this in case of new  android versions. Thnx for explained the reason to take a copy of bouncycastle, assumed that was the reason.

**Comment by wolpi** [comment]
There are no new issues regarding crypto libraries. But new Android filesystem restrictions kick in, see #233 233
