### ISSUE TITLE
Multiple issues with root mode including unable to handle spaces.

### ISSUE THREAD

**Issue by nl255** [wolpi/prim-ftpd#262]
I have noticed that on my moto g stylus (minsk) that superuser mode works fine as long as none of the folders have spaces in them.  If they do have spaces then the contents can't be listed at all and files can't be uploaded to them without using the tmp folder copy option.

Also, if I go to /storage/emulated/0 in filezilla then click on data then it will send me to /data rather than /storage/emulated/0/data and any use of ".." goes back to / rather than the previous directory.

Here is a log for the spaces issue and should also include the problem with ".." as well [prim-ftpd-log-spacesinfoldernames.csv](https://github.com/wolpi/prim-ftpd/files/8498317/prim-ftpd-log-spacesinfoldernames.csv)

**Comment by wolpi** [comment]
>as long as none of the folders have spaces in them

That is interesting. I'll look into it when I find time.


>then click on data then it will send me to /data 

I've seen such behavior in other clients. With filezilla I cannot reproduce it. There is some code present for such cases to support several clients. That is not likely to change. But patches are welcome :wink:

**Comment by nl255** [comment]
A configuration option to always use absolute paths when changing directories might fix the second issue (i.e. if you are in /sdcard/Android/ and then double click on data, have the server do "cd /sdcard/Android/data" instead of just "cd data").

**Comment by wolpi** [comment]
It is up to the client if it uses absolute or relative paths. The server cannot control it. With Filezilla you can force absolute paths by entering them in the address bar.

**Comment by wolpi** [comment]
the path with spaces part is fixed
