### ISSUE TITLE
QuickShare suggestions

### ISSUE THREAD

**Issue by takase1121** [wolpi/prim-ftpd#264]
From #263  I've mentioned that QuickShare should support sharing multiple files.

Other than that, I have a few ideas to improve the feature:

1. Copy files in SD into the SD's data folder - I'm not too sure if this is possible but It'll avoid QuickShare from copying the entire file into Internal storage
2. Use symlinks - I'm pretty sure this is mutually exclusive with (1) since Android requires some magic to access SD files already. It'll also need some C code iirc since the SDK don't expose ways to create symlinks.

Of course, these are nice to have features, they are not _that_ important. It would improve the usability of the feature.

**Comment by wolpi** [comment]
QuickSharing multiple files is now possible.

As you already said, the improvements are nearly impossible due to Android's restrictions in regard of access to filesystem and sd-card as well as accessing share data in different threads.
