### ISSUE TITLE
Announce server option to resolve IP?

### ISSUE THREAD

**Issue by Gibtnix** [wolpi/prim-ftpd#265]
Hello,

first of all, thanks again for this brilliant app! 👍 
It's so useful to access the data and sync devices without needing a cable.

Regarding my actual question: I have the FTP server saved in my FTP client which requires to save the IP of my phone.
Now, moving to a different network where my Android device and a portable client (e.g. a notebook) are both connected, of course the IP is different and I have to use the current IP of the Android device and everything works.

Ideally, I could connect to the Android device instead of the IP by a server name that is resolved dynamically depending on the actual network. In the app's option I noticed the 'announce FTP server in network' option.
I tried to enable this and assign a server name, however the connection by name did not work. I don't know all the technical details but I think for resolving the server name either the networks DNS server has to do the job (or the client device that connects to the server has to do it using its host file, but adjusting the hosts file is even more complicated than changing the IP in the FTP client).

Does this announce server option has something to do with this possibility or is server name resolving hardly possible at all?

Thanks for your time and the great app!

**Comment by wolpi** [comment]
The announce server name option is based on Android's integration of some auto discovery mechanism like bonjour or avahi. This is different form usual name resolution like DNS. Some clients support finding servers based on auto discovery. E.g. Gnome file manager.

**Comment by Gibtnix** [comment]
Alright, thanks for clarifying 👍
