### ISSUE TITLE
Unable to access /storage/emulated/0/Android/data folder

### ISSUE THREAD

**Issue by dfirnewbie** [wolpi/prim-ftpd#266]
Hi,

I can no longer access `/storage/emulated/0/Android/data` folder after upgrading to Android 11.

I've tried changing the permissions as per described, but it's still not working.

The FTP client returns an error:

```
Error:	Unable to open .: permission denied
Error:	Failed to retrieve directory listing
```

Other ways of mounting doesn't work as well...

Edit: unrooted device.

**Comment by wolpi** [comment]
That path is treated as specially critical by Android. It contains private directories of all apps. It might be that the system blocks access to that path even when an app got full permission. You can access the private directory of this app through this app when you use full absolute path:

/storage/emulated/0/Android/data/org.primftpd
