### ISSUE TITLE
Text alignment in version 3.2

### ISSUE THREAD

**Issue by csapdani** [wolpi/prim-ftpd#27]
Please add an option to switch from the centered alignment back to left alignment.

**Comment by wolpi** [comment]
Well I could have expected this. Making changes wished by one user (issue #20) upsets another one :dizzy_face:

I will see what I can do here. May take some weeks or even months as by hobby time is limited.

Just to be clear: I changed the layout as I was not happy with the old one either.

**Comment by wp9015362** [comment]
> @wolpi wrote:
> 
> [...] changes wished by one user [...]
> [...] I changed the layout as I was not happy with the old one either [...]

Technically speaking, this already means it's two users, not one :stuck_out_tongue: .

And @xphnx also wrote "the app has greatly improved" [in his other issue](https://github.com/wolpi/prim-ftpd/issues/28).

So, that's probably even three users already, not just one :stuck_out_tongue:.

**Comment by wolpi** [comment]
OK I'll leave it as is. Keeping 2 layouts around would have been a maintenance burden anyway.
