### ISSUE TITLE
Please enable Discussion.

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [wolpi/prim-ftpd#272]
My rationale is available at "https://github.com/8go/matrix-commander/issues/68#issue-1237645245".

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
(However, in lieu of it, do you mind informing me of whether this software supports FTPS, as "http://f-droid.org/repo/de.qwerty287.ftpclient_7.apk" does?)

**Comment by wolpi** [comment]
Discussions have been enabled.

There willbe no FTPS support as this app supports SFTP.
