### ISSUE TITLE
Ver. 6.13 (59) from F-Droid isn't listed under All Files Access anymore

### ISSUE THREAD

**Issue by EauBureau** [wolpi/prim-ftpd#274]
First can I say a big thank you for this app. Its so useful. I use it **all** the time for transferring stuff to and from my PC. :thumbsup:

I upgraded from the F-Droid version 6.11 (57) to ver. 6.13 (59) and the app isn't listed under the 'All Files Access' list anymore? I'm on Android 11.

**Comment by wolpi** [comment]
This is surprising, I did not expect that.
In main screen there is a new line telling you if app has full storage access. What does it tell you?

**Comment by EauBureau** [comment]
Sorry, I didn't notice that before.
It is "false" and when I hit "Request" I go to a permission page with "Allow access to manage all files" greyed out with a toggle button that I can't toggle on.

**Comment by mowanotm** [comment]
I'm having the same issue. In permission, I can only grant access to media, not access to all files.
In Settings > Apps > Special app access > All files access, primitive ftpd isn't there.
I can grant all file access permission to other file manager or backup apps without problem.

**Comment by wolpi** [comment]
That behavior is enforced by Google Play. Recently I introduced a mechanism to build releases in two variants, one for Google Play with that restriction and a "real" one. F-Droid's build system picked up git tags intended for Google Play. Will be fixed next time.

**Comment by EauBureau** [comment]
Looking forward to it. Thanks.

**Comment by wolpi** [comment]
release has been created, it might take some days until it shows up in f-droid

**Comment by EauBureau** [comment]
Can confirm the issue is now fixed in F-Droid ver 6.14 (60).
Thanks for taking the time to fix this issue. I appreciate it. This app is indispensable.
