### ISSUE TITLE
No start button on the upper-right side

### ISSUE THREAD

**Issue by hzjppkk** [wolpi/prim-ftpd#278]
when it runs on my tv(android 9) there is no button on the upper-right corner, it's all blank.
while it works well with my tvbox (android 4.4)
![2022](https://user-images.githubusercontent.com/22807036/190421920-490940d1-3455-4249-b8af-d3ec203a07ec.jpg)

**Comment by wolpi** [comment]
The buttonsin upper-right corner are called ActionBar. That is generally not present on Android TV. As far as I understand the main reason for that design decision by Google is that most TV devices don't have a touch screen or pointing device but are controlled with a d-pad.

To support Android TV this app has a own launcher Activity which adds buttons to start/stop server and to open preferences in the dark area above texts (and horizontally centered).

It seems in your case the Activity intended for mobile devices is used.

**Comment by hzjppkk** [comment]
Is there any chance I can slove this problem?
Or can I offer some help

**Comment by wolpi** [comment]
You could try to find different ways to open the app. Hopefully Android would use proper Activity then.

**Comment by nom3ad** [comment]
@wolpi  Thank you!
I had the same issue with my android TV,  and I used  `X-plore (com.lonelycatgames.Xplore)`  file manager to list out activities available for org.promftpd.  And I was able to launch `org.primftpd.ui.LeanbackActivity`  from there and it worked!
![image](https://user-images.githubusercontent.com/19239479/191203435-95b3d3e4-9d62-4f70-883c-580f26c9abc8.png)
