### ISSUE TITLE
Server doesn't list root folders

### ISSUE THREAD

**Issue by Sora3100** [wolpi/prim-ftpd#279]
Happens over both FTP/SFTP, old plain filesystem, virtual system, etc
Everything below the root folder does appear, however
I can also manually type in the folder (/saf, /fs, etc), and it works fine
Phone is running Android 11
Client is WinSCP, but I don't think that should make a difference.
[Log](https://github.com/wolpi/prim-ftpd/files/9591997/prim-ftpd-log-2022-09-17-17-02-58.csv)

**Comment by wolpi** [comment]
In your log it seems you use VirtualFolders with SAF pointing to Music. That should work well.
If you use VirtualFolder /fs it forwards you to internal storage not to root folder. WinSCP should show this. But maybe it is a clinet issue that it does not.
Usually Android blocks access to root folder.

**Comment by Sora3100** [comment]
Root may not have been the right word, what I meant are the first folders (aka /fs, /saf, etc)
These do not show (though in the past it used to)
This also happens with just plain old filesystem where the very first folder isnt listed at all.
Everything below /fs, /saf shows as normal
