### ISSUE TITLE
Photo location data (exif) wiped when transferred with prim-ftpd

### ISSUE THREAD

**Issue by jan-et-c** [wolpi/prim-ftpd#280]
Transferred a bunch of images with prim-ftpd and noticed that location data has been wiped.

Android 12 (on OPPO Find X3 Lite)

Steps to reproduce:

1. Take an image and make sure that location data is in it directly on the device
2. Transfer image with prim-ftpd
3. Examine exif data in an appropriate PC app (commandline : exiftool, Gwenview, Digikam or the like)
4. Check location data : Location data wiped / set to zero in my case
5. Transfer same image via USB
6. Repeat step 4 : location data present

After a bit research, i stumbled upon
https://developer.android.com/training/data-storage/shared/media#media-location-permission

**Comment by wolpi** [comment]
Will be added
