### ISSUE TITLE
Material You (MD3) Support?

### ISSUE THREAD

**Issue by Pentaphon** [wolpi/prim-ftpd#281]
Hi, any chance this simple but very useful app could get a design refresh to fit in with Material Design 3 aka Material You? It would really help with the overall look of the app and make it more pleasant to use.

Here's links on what has changed and how to get started. 

https://material.io/blog/start-building-with-material-you
https://m3.material.io/

**Comment by wolpi** [comment]
Do you have ideas for concrete changes?

**Comment by Pentaphon** [comment]
> Do you have ideas for concrete changes?

I just want the UI to look more modern, easier to read, better organized, etc. Maybe a bottom bar UI. Nothing really specific other than that. An app this useful should look and read well and I think MD3 is a must for that.

**Comment by wolpi** [comment]
I would be happy to discuss concrete ideas or proposals.

* How to make it easier to read? Use bigger font?
* How to make it better organized?
* What to put in bottom bar?

**Comment by Pentaphon** [comment]
> * How to make it easier to read? Use bigger font?
Maybe just use the new recommended font for Material Design 3
 
> * How to make it better organized?
Make the setting organized into different sections instead of 1 long section you have to scroll down to see everything.

> * What to put in bottom bar?
All the major sections of the app like the main page, settings, fingerprints, etc. It helps to have everything down by your thumbs instead of up at the top at the dropdown menu on big phones.

**Comment by wolpi** [comment]
Yes, sounds good. I'm going to look at it in next few weeks or months.

**Comment by wolpi** [comment]
With #286 the app uses new default theme, which should be material design 3 on most devices

**Comment by wolpi** [comment]
Introducing a Tabbar seems to be quite some work as existing stuff needs to be re-done. But it might help with Android TV (#257).
Maybe in next version
