### ISSUE TITLE
F-Droid build failed 

### ISSUE THREAD

**Issue by linsui** [wolpi/prim-ftpd#284]
https://monitor.f-droid.org/builds/log/org.primftpd/61#site-footer

https://issuetracker.google.com/issues/184872412 This is an issue of AGP 4.1. Updating AGP to 4.2 or above should fix it. Could you please upgrade the AGP? Thanks!

**Comment by wolpi** [comment]
I'll have to check. Updating tools might cause other issues in this project.

**Comment by linsui** [comment]
Thanks!

**Comment by wolpi** [comment]
I'm closing this now. Let's see what happens in f-droid on next release.

**Comment by linsui** [comment]
I'll update the commit. Thanks!
