### ISSUE TITLE
System default theme

### ISSUE THREAD

**Issue by xmha97** [wolpi/prim-ftpd#286]
Please add the system default theme.
![Screenshot_2022-10-31-17-07-15-592_org.primftpd.jpg](https://user-images.githubusercontent.com/23485114/199020954-e6c10d30-f433-4aee-a9ff-5dbfa9aab786.jpg)

**Comment by wolpi** [comment]
I'll have a look at it, when I find time

**Comment by wolpi** [comment]
Will be part of next version

**Comment by xmha97** [comment]
> Will be part of next version

Thanks. 🙏
