### ISSUE TITLE
primitive ftpd should use switches instead of checkboxes in the settings to adhere to Google Material Design Guidelines

### ISSUE THREAD

**Issue by wp9015362** [wolpi/prim-ftpd#29]
@wolpi :

Currently primitive ftpd is using checkboxes in the settings.

But the Google Material Design Guidelines clearly say:

> https://www.google.com/design/spec/components/selection-controls.html
> 
> [...] If you have a single option, avoid using a checkbox and use an on/off switch instead. [...]

So, could you please replace them with switches?

Regards

**Comment by wp9015362** [comment]
@wolpi :

The discussion over there might be helpful (regarding compatibility with older Android versions), see:

https://github.com/connectbot/connectbot/pull/205

Regards

**Comment by wolpi** [comment]
Actually android4 provides already SwitchPreferences, they just look different. So it was a no-brainer to change it.
