### ISSUE TITLE
error while reading: received a short buffer from FXP_READ, but not at EOF

### ISSUE THREAD

**Issue by dave0003** [wolpi/prim-ftpd#290]
In super user mode, I've found that often when I'm transferring files, I receive this error:

error while reading: received a short buffer from FXP_READ, but not at EOF

And the file that is transferred is cut-off and corrupted.

I'm not sure it's strictly a bug for primitive-ftpd, but it is unusual.  I found a note here:

https://www.chiark.greenend.org.uk/~sgtatham/putty/wishlist/fxp-short-reads.html

Most servers don't present this error, though.  The only other report they've had is OpenVMS server.

**Comment by wolpi** [comment]
Do you use setting to copy files to temp dir before transferring in super-user-mode?

Background:
Java code cannot be run as root. Java code needs to run linux commands as root and read their output. To transfer files tool `dd` is used. Input/output streams of dd process are connected to Java IO-Streams. That is fragile and might cause the behavior you see. When switching of "copy to temp first" that fragile stuff is avoided. But of course temp files need space and time to be created.

**Comment by dave0003** [comment]
I hadn't been using that setting.  I just tried it, and it seems to fix the issue.  Thank you!

Is there a way to set the temp file storage to the sd card, so large files aren't as much of a problem, and to avoid wearing out the phone's flash storage?  I have a large high endurance sd card, so it should be fine there.

**Comment by wolpi** [comment]
Well, usually accessing sd-card is not possible via filesystem API but with SAF-API. That requires additional user interaction, it is slow (at least for listing files) and cumbersome to work with.
Currently that "temp-for-root-files" mechanism is implemented with filesystem-API and app-private-storage-area. These app-specific folde structure might be present on sd-card, too. I'll have to check if that can be used. Will take some time until I find time.

**Comment by dave0003** [comment]
Thank you.
