### ISSUE TITLE
"IP to bind to" field rejects `:` characters required for IPv6

### ISSUE THREAD

**Issue by rustybird** [wolpi/prim-ftpd#291]
The "IP to bind to" field does not allow entering `:` characters as part of an IPv6 address. Copying and pasting in a string also filters them out.

**Comment by wolpi** [comment]
Oh, yes. Currently it is desigend for IPv4 only. Needs to be changed.

**Comment by wolpi** [comment]
As you can see by linked commit, it should work in next version
