### ISSUE TITLE
Where to put authorized_keys file?

### ISSUE THREAD

**Issue by Offerel** [wolpi/prim-ftpd#292]
I want to try to use this app to sync Music from within Strawberry Media Player to my phone. For this to make work, I have created the following line in my /etc/fstab on my Laptop:

`user@92.168.188.10:1234/	/media/phone	fuse.sshfs IdentityFile=/root/.ssh/id_rsa,users,noauto,allow_other,gid=1000,uid=1000 0 0`

I have a similar line for my webserver (with other user). For test purpose, i have copied other the authorized_keys from this webserver, to not struggle with the keys and the format. On the phone with your app, i cant access /storage/emulated/0/Android and its subdirs. Thats why i have created /storage/emulated/0/.ssh/ and put the file here, because both paths are somewhere described as path for this file.

Do i try to mount, i get: `Connection reset by peer`
When i try it manually with: `sshfs -p 1234 user@192.168.188.10:/ /media/phone/` it asks for a password, instead using the keyfile. Entering the password gives again: `Connection reset by peer`

Laptop uses actual Manjaro/Arch Linux. Any ideas?

**Comment by Offerel** [comment]
OK, have some news. Using the option "Good old filesystem", it mounts the phone after entering the password (it doesnt use the keyfile for some reason). But listing isnt possible: `ls -lha /media/phone/ `-> `no privileges...`

Using SAF its mounting again only via password. And... i can list the files on the phone. But i cant copy files to the mount, since it seems to unmounted after a short time. touch a file is also not possible

**Comment by wolpi** [comment]
In your fstab you have this path to your private key file:
`/root/.ssh/id_rsa`
Do you work as root user?
Usually you have another user account and thus another path to private key file.

**Comment by Offerel** [comment]
No, this is only a example. Usually I'm logged in as standard user. Some minutes ago, I could make a successful connection via keyfile, when I put `authorized_keys` in `/storage/emulated/0/.ssh/` on the phone. Additionally, I had to enable rsa key format format in `/etc/ssh/ssh_config` on the client. It was disabled for security reasons on Manjaro Linux.

I will try to use this connection now to sync Strawberry media player directly to my phone. Using MTP is a real mess. If this is successful, I can tey to write a small detailed HowTo. Maybe this helps others to.

**Comment by wolpi** [comment]
>I had to enable rsa key format format in /etc/ssh/ssh_config

That is necessary only if you use `.ssh/id_rsa`. As filename says: that is a RSA key.
You can use other key formats, too. E.g. `.ssh/id_ed25519`.
If not present you have to generate it of course:
`ssh-keygen -t ed25519`
