### ISSUE TITLE
Problem with FileZilla

### ISSUE THREAD

**Issue by tikitaka007** [wolpi/prim-ftpd#293]
Hello,

Primitive ftpd does not work well with the FileZilla client. It does not go down to the previous level/folder when you click on ... it always puts you at /

Other ftp servers do not have this behavior.

Best regards.

**Comment by wolpi** [comment]
that depends on which storage type you use

**Comment by tikitaka007** [comment]
I use internal storage and do not specify the default remote directory.

**Comment by wolpi** [comment]
That is weird. It works for me. Can you share more detail about your directory structure and setup? Maybe share logs?

**Comment by Shallrath** [comment]
I also have some weird behavior with Filezilla jumping to the / directory when doing a 'cd ..'. This happens sometimes and sometimes it doesn't.

I also tried lftp and there it never jumped to / but instead directories seemed empty that definitely should not be empty. There seems to be a problem that the server loses track where you are. Another FTP server app didn't show this behavior on my phone.

**Comment by Shallrath** [comment]
I enabled logging to text file but there is no file created at the location that is stated in the settings menu.

**Comment by Hikari-no-Tenshi** [comment]
Have same issue.
In FileZilla can't go back to previous derictory, always switching to device root directory.
I have root type of access. My root directory is /storage/emulated/0.

[prim-ftpd-log-2023-07-15-12-20-33.csv](https://github.com/wolpi/prim-ftpd/files/12061053/prim-ftpd-log-2023-07-15-12-20-33.csv)

**Comment by wolpi** [comment]
I need to find some time to dig deeper here. These things work better with SFTP as keeping track of working dir is done client side in that protocol.

**Comment by Hikari-no-Tenshi** [comment]
> I need to find some time to dig deeper here. These things work better with SFTP as keeping track of working dir is done client side in that protocol.

Hoping for fix.
SFTP working fine with paths tracking, but it is very slow compared to FTP.
On my local network from PC to Mobile phone:
FTP up to 50 MB/s
SFTP up to 500 KB/s

**Comment by anonymous5555522222** [comment]
WinSCP is also affected by this issue.
