### ISSUE TITLE
Ability to specify directory without exploring the file system

### ISSUE THREAD

**Issue by creeper451** [wolpi/prim-ftpd#295]
Hello, so the other day I was trying primitive ftpd on Android 10 and I made an interesting discovery if I made the os give the app full permission I would be able to access my SD card with full r,w access , so if I specify the remote directory on Filezilla to be "/storage/V181-1Y3D" it's going to list the directory in the program without any issues but I cannot access "/storage" (in Android 9 and below this was possible) so if I wanted to use the "Server Start Directory" in the app settings to specify my SD card I can't, even though it's has the correct permission, so I need the ability to specify the "V181-1Y3D" directory without using the built in file explorer just like on Filezilla (by typing the full directory path).
P.S thanks for this amazing app 👍

**Comment by wolpi** [comment]
Funny thing. Some years ago there was no file-explorer. "Server Start Directory" needed to be specified just as text. People didn't like it. Now it is the other way around :smile:.

Not sure how this would look like :shrug: 


>P.S thanks for this amazing app +1
Happy that you like it :smiley:

**Comment by creeper451** [comment]
We could have a dialogue box to select either the file explorer or to specify the directory ourselves.

**Comment by wolpi** [comment]
As you can see by linked commit, there is a new possibility in next version
