### ISSUE TITLE
'Tasker plugin' does not work out-of-box after upgraded to 6.16

### ISSUE THREAD

**Issue by Tamas-Toth-ebola** [wolpi/prim-ftpd#296]
Hi!

I have used your FTP server for years on my Android phones and absolutely love it, really lot of thanks for it! I also configured auto-start/stop options on my 'home' and 'work' WiFi connections through its embedded 'Tasker' plugin which also worked perfectly. Sadly after the fresh 6.16 upgrade, 'Tasker' started to throw permission errors about the 'Primitive FTPD'.

After the upgrade, I get the following in 'Tasker', in case it tries to start/stop the FTP server...
```
23.29.00/Plugin receiver org.primftpd.remotecontrol.TaskerReceiverFire requires permission org.primftpd.permission.WRITE_SERVER_STATUS which we don't have
23.29.00/E result: stop task (error)
23.29.00/E Error: 1
23.29.00/E receiver org.primftpd.remotecontrol.TaskerReceiverFire requires permission org.primftpd.permission.WRITE_SERVER_STATUS which we don't have
23.29.00/MacroEdit action finished exeID 1 action no 0 code 1665143267 status: Err next 0
```
...so I tried to give the required permission with...
```
adb shell pm grant net.dinglisch.android.taskerm org.primftpd.permission.WRITE_SERVER_STATUS
```
...but got unsuccessful result as:
```
Security exception: Package net.dinglisch.android.taskerm has not requested permission org.primftpd.permission.WRITE_SERVER_STATUS

java.lang.SecurityException: Package net.dinglisch.android.taskerm has not requested permission org.primftpd.permission.WRITE_SERVER_STATUS
	...
	..
	.
```
Could you please help me with the problem?

**Comment by wolpi** [comment]
Happy that you like the app :smile: 

Interesting that tasker plugin worked for you. There are reports of it wouldn't work.

In 16.6 there have been changes in tasker plugin as seen in #82.

According Android documentation it is now necessary for apps to declare own permissions. It is even more interesting that it worked for you.

**Comment by CypherMK** [comment]
I'm also experiencing the same issue as OP. No solution for this?

**Comment by wolpi** [comment]
Let's see what people report in #82. I might revert those changes.

**Comment by wolpi** [comment]
As you can see in linked commits the old situation as before 6.16 has been restored.
