### ISSUE TITLE
Header UI Colors Seem Wrong

### ISSUE THREAD

**Issue by hl2guide** [wolpi/prim-ftpd#298]
![example](https://user-images.githubusercontent.com/17044982/235334498-1a0ea0a4-7e17-4e78-87a3-1d89ce2cb5d2.jpg)

Tested on Android 12 on a Samsung phone.

**Comment by wolpi** [comment]
That looks bad, yes. What are your settings? Which app version do you have? There have been changes regarding themes in last version.

**Comment by hl2guide** [comment]
> That looks bad, yes. What are your settings? Which app version do you have? There have been changes regarding themes in last version.

Settings: Default, then started one server using SAF storage type
App version: 6.16 (code: 62)

**Comment by wolpi** [comment]
You can try to switch to a different theme.

**Comment by hl2guide** [comment]
> 

Switching the dark mode on fixed it.

"System Default" is bugged, at least on my device.
