### ISSUE TITLE
Support for SSH public key authentication

### ISSUE THREAD

**Issue by chrysn** [wolpi/prim-ftpd#30]
SSH keyboard-interactive authentication is inconvenient when using SFTP in automounting situations. Please consider adding support for public key authentication against the server. An authorized_keys file could be placed in .ssh/authorized_keys in the home directory, explicitly loaded into the application, or copy-pasted into a text area there. (For starters, any of these would do; I'm not sure which gives the most Android-like user experience).

**Comment by wolpi** [comment]
> I'm not sure which gives the most Android-like user experience

I guess dealing with keys is not android-like at all :wink: 

Currently I think I will use the file .ssh/authorized_keys along with a boolean preference to enable it and tell users that it is possible. As my hobby time is limited it will take some weeks.

**Comment by wolpi** [comment]
I chose to load the key from .ssh/authorized_key.pub. I changed the filename as just one key is supported. The .ssh folder must be located in the default server start dir.
