### ISSUE TITLE
Spanish translation out-of-date

### ISSUE THREAD

**Issue by trikaphundo** [wolpi/prim-ftpd#309]
The [Spanish translation](https://github.com/wolpi/prim-ftpd/blob/master/primitiveFTPd/res/values-es/strings.xml) is out-of-date. It lacks many strings present in the [master strings.xml](https://github.com/wolpi/prim-ftpd/blob/master/primitiveFTPd/res/values/strings.xml) file.

I am working on updating it. Will file a PR soon.

**Comment by wolpi** [comment]
Looking forward to it :smile: 
You could create the PR already now and push a commit later.
