### ISSUE TITLE
String in UI not translatable

### ISSUE THREAD

**Issue by trikaphundo** [wolpi/prim-ftpd#312]
While translating the application's user interface, I realized that there are two strings which are not translatable, the two highlighted in the image. These two strings do not show in the [strings.xml](https://github.com/wolpi/prim-ftpd/blob/master/primitiveFTPd/res/values/strings.xml) file, hence they cannot be translated.

![Screenshot_20230723-221525_1](https://github.com/wolpi/prim-ftpd/assets/24832650/81814006-f90a-4d7e-acba-08a872acfa72)

**Comment by wolpi** [comment]
Has been changed
