### ISSUE TITLE
Add option to automatically kill server after idling time X

### ISSUE THREAD

**Issue by pby5u** [wolpi/prim-ftpd#318]
Hello,

I use ftpd a lot, and I tend to forget that it is running in the background a lot too. I am missing a feature/option that that automatically kills the server after time X. Could this be implemented additionally to the idle timeout feature?

**Comment by wolpi** [comment]
I'll check how this could be implemented, probably #146 would be removed then. Will take some months until I find time.

**Comment by wolpi** [comment]
Has been added
