### ISSUE TITLE
Got trouble in generating Android apk

### ISSUE THREAD

**Issue by DA21S321D** [wolpi/prim-ftpd#319]
I installed java8 and use gradlew.bat to build an android apk.
Here is what console shows me :
![image](https://github.com/wolpi/prim-ftpd/assets/56549016/819debd2-d2cc-4cbc-bc53-4058735c0b75)
But i can't find where the apk situated at, i just make a little change on sort file. Make it sort by date rather than alphabet. (i need this function beacuse i just open it in web and the alphabet sort is not useful when i have 100+ files)

**Comment by wolpi** [comment]
That is just default output by gradle, no build has been done.

try:
`./gradlew build`
or (if tests fail on your machine)
`./gradlew assemble`

You might need to setup Android SDK first.

**Comment by lmagyar** [comment]
Build is successful with java 11. :)

**Comment by lmagyar** [comment]
I think this issue can be closed.

**Comment by wolpi** [comment]
Agreed
