### ISSUE TITLE
No connection to Filezilla possible

### ISSUE THREAD

**Issue by TJFOE** [wolpi/prim-ftpd#324]
Version 6.17 Snapshot (code:63)
Android 6.0

I cannot connect to Filezilla. Access rights to the storage is activated in the system settings. "Has (normal) memory access then switches to false". Connection with user and password, unencrypted.
![primitive_FTPD_6_17](https://github.com/wolpi/prim-ftpd/assets/10260152/0be29a63-2978-4bbc-a8b9-6898c33f30e4)

Filezilla behaves in the same way as if primitive FTPD had not been started:

Connect to 192.168.0.201:12345...
Status: Connection attempt failed with "ECONNREFUSED - Connection denied by server".
Error: Failed to connect to the server

**Comment by wolpi** [comment]
> Could this have something to do with the fact that these two apps query the SSID, i.e. the specific WLAN?

This app does not query SSID.

The screenshot of this app above looks good. Seems like everything is setup properly.
Screenshots of clients would be helpful now, to see if something is missconfigured there.

**Comment by TJFOE** [comment]
FileZilla 3.66.1 (Linux)

![Filezilla_1](https://github.com/wolpi/prim-ftpd/assets/10260152/9ec35d19-0e49-4618-ad67-e677cde4b321)
![Filezilla_2](https://github.com/wolpi/prim-ftpd/assets/10260152/376366e2-0335-4996-a6fa-722aee1cae2c)
![Filezilla_3](https://github.com/wolpi/prim-ftpd/assets/10260152/d3089023-9c16-4551-b1f0-492111386f8f)
![Filezilla_4](https://github.com/wolpi/prim-ftpd/assets/10260152/ba958f7c-4bfb-42d9-aedf-c8aada3f55db)
![Filezilla_5](https://github.com/wolpi/prim-ftpd/assets/10260152/40d9ed71-903a-4137-812a-ed4c4dc9f5df)
![Filezilla_6](https://github.com/wolpi/prim-ftpd/assets/10260152/5a6b7216-4ca5-4a7b-bbef-9f6416ddabc3)

**Comment by wolpi** [comment]
Those screenshots look fine, too.

Is there a firewall?

You could use network debugging tools like netcat or telnet to verify that server port is really open and reachable.

**Comment by TJFOE** [comment]
There is no special firewall. Only the router. I get  - also from the smartphone with simple netcat the same message as from Filezilla: "ECONNREFUSED - Connection denied by server". See my first post. I tried ports which are working with the other 2 FTP-Server: Not working...

**Comment by wolpi** [comment]
ok, then we have to look into logs. Can you share server logs?

**Comment by TJFOE** [comment]
[prim-ftpd-log-2023-11-26-17-31-37.csv](https://github.com/wolpi/prim-ftpd/files/13484270/prim-ftpd-log-2023-11-26-17-31-37.csv)

**Comment by wolpi** [comment]
This log contains no relevant information. It is just about UI related things. Interesting would be server startup, connection attempts and hopefully some indication why server is not reachable.

**Comment by TJFOE** [comment]
In the meantime, I have a new phone with Android 13 ... and the app works perfectly! But I also see some settings that I didn't see on Android 6...

**Comment by TJFOE** [comment]
...
