### ISSUE TITLE
Use Weblate for translations

### ISSUE THREAD

**Issue by Daviteusz** [wolpi/prim-ftpd#325]
I saw that in 2018 it was possible to translate pFTPd through Weblate, now there is no such possibility.

I suggest integrating your project with hosted.weblate.org
Translators will be happy.
😃

**Comment by wolpi** [comment]
Sounds like a good idea. I'll look at this as soon as I find time.

**Comment by wolpi** [comment]
For now there is  a setup in testmode on hosted weblate. They told me they cannot decide yet if this app gets free hosting due to personal reasons.

**Comment by wolpi** [comment]
In meantime this project has been accepted by hosted weblate
