### ISSUE TITLE
Menu bar almost unusable in V7.0 and design option missing

### ISSUE THREAD

**Issue by enteiser** [wolpi/prim-ftpd#330]
In V7.0, there is a new menu bar instead of the 3 dot Hamburger menu The menu bar is almost unusable because the labels are cut to one or two letters. The better alternative would be the old UI.
I am missing the convenient option for a dark design independent from system design.
Unfortunately, both issues are no improvements over the older version.

**Comment by wolpi** [comment]
I see this different.

> The menu bar is almost unusable

You can swipe through tabs. It's not necessary to use the tabbar.


>I am missing the convenient option for a dark design independent from system design.

To support theming dependent on system and iindependent from system caused a maintenance nightmare. New code is better maintanable.

**Comment by OmlineEditor** [comment]
I completely agree. The new menu is just terrible. bring back the old menu.

**Comment by wolpi** [comment]
It's funny how different opinions can be in regard of UI.

**Comment by OmlineEditor** [comment]
Do you really think this is a good menu?
Bring back the old menu. on small screens it is impossible to look at this crooked menu without tears
![g](https://github.com/wolpi/prim-ftpd/assets/13348933/cbf7cc63-6ad6-403c-9f8b-3c3fcea46d0f)

**Comment by wolpi** [comment]
>it is impossible to look at this crooked menu without tears


:joy: :joy: :joy: 



I could imagine to provide a preference to remove texts from tab titles. Only emoji would be left then.

**Comment by OmlineEditor** [comment]
> I could imagine to provide a preference to remove texts from tab titles. Only emoji would be left then.

you can do that, but it's not very clear if you run the program rarely or for the first time

**Comment by wolpi** [comment]
The preference is now there. Per default it shows emoji only.
