### ISSUE TITLE
[Feature Request] Multiple storage devices 

### ISSUE THREAD

**Issue by webepg** [wolpi/prim-ftpd#334]
FIRST OF ALL: I LOVE YOUR SOFTWARE!!!!

Hi,

could you make it possible to use multiple storage devices at the same time? I can use the internal storage or the external storage which works fine but I always have to change the settings to switch.

It would be fine for me if I had to set a second user and password for the other storage.

thx in advance

**Comment by wolpi** [comment]
Your case should be covered by virtual folders. Have a try with them.

**Comment by lmagyar** [comment]
I think this issue can be closed.
