### ISSUE TITLE
dns-sd: should be _sftp-ssh._tcp

### ISSUE THREAD

**Issue by chrysn** [wolpi/prim-ftpd#34]
prim-ftpd announces its sftp server as _sftp._tcp on dns-sd (zeroconf/bonjour), while it should use _sftp-ssh._tcp according to http://www.dns-sd.org/servicetypes.html ; that would make the server show up in the "network neighborhood" of gvfs (used by gnome, xfce and others).

please consider changing the announced service type, or (if there are good reasons to use _sftp._tcp) announcing both.

**Comment by wolpi** [comment]
Thanks for the hint.
There was no reason for the old name, I just didn't know better :stuck_out_tongue_closed_eyes:
