### ISSUE TITLE
PrimitiveFtpdActivity - fragment class should be public

### ISSUE THREAD

**Issue by lenisko** [wolpi/prim-ftpd#35]
Can't compile, I'm getting weird problem
```
prim-ftpd\primitiveFTPd\src\org\primftpd\PrimitiveFtpdActivity.java
Error:Error: This fragment class should be public (org.primftpd.PrimitiveFtpdActivity.GenKeysAskDialogFragment) [ValidFragment]
```

**Comment by wolpi** [comment]
I added another library recently (issue#30) which broke a full build for me too. Doing incremental builds in android studio still worked. Will fix it in some days/weeks.

**Comment by lenisko** [comment]
@wolpi 
hmm, but still I can't generate signed app, or I don't know how :)

**Comment by wolpi** [comment]
Never built it with gradle. So currently I don't know all the details. Basically you must create your own keystore which contains the signing key.

Then I guess you have to create a gradle.properties file and reference your key in there.

**Comment by wolpi** [comment]
Building should work again.

To sign the apk the keystore must not be referenced in a properties file but in gradle script. As I don't want to commit my keystore to GH I prefer to create signed builds through the android studio GUI, see:

https://developer.android.com/tools/publishing/app-signing.html

**Comment by lenisko** [comment]
@wolpi thanks for information, didn't know about it.

**Comment by wolpi** [comment]
I'm going to close this now
