### ISSUE TITLE
"%1$s" permission is required for this app to work

### ISSUE THREAD

**Issue by themightyoarfish** [wolpi/prim-ftpd#363]
I have 7.1 installed via F-Droid, on a lineageos Moto g7+ (android 13). When I go to settings and try to change the server start directory, it shows a toast

> "%1$s" permission is required for this app to work

and does not prompt for any permissions. My previous version did not have this issue, but all versions I see on F-Droid do. Thus unfortunately I can not use this app.

![photo_5208926733498178208_y](https://github.com/wolpi/prim-ftpd/assets/11613312/af986eef-fac8-426d-874d-b660b45e6862)

**Comment by themightyoarfish** [comment]
What does work is first selecting "Android Storage Access Framework" and then selecting the startup directory.

**Comment by themightyoarfish** [comment]
No, actually that only gives read-only access via FTP.

**Comment by wolpi** [comment]
Seems like a defect when trying to show what permission is missing. I will investigate that as soon as I find time.

Probably it is about permission to access filesystem. See README of this github repo for details.
