### ISSUE TITLE
QR code options duplicate on app change

### ISSUE THREAD

**Issue by Headedbranch225** [wolpi/prim-ftpd#367]
When I have the app on the QR page and change apps back to the app, it creates another pair of buttons (samsung S9)
![Screenshot_20240804-001340_primitive ftpd](https://github.com/user-attachments/assets/e3621ef7-d452-4bb7-bb27-ad79473805df)

**Comment by wolpi** [comment]
Oh, funny behavior. Will be fixed in next version.

**Comment by lmagyar** [comment]
Seems that #382 will fix this also.
