### ISSUE TITLE
fully passwordless operation

### ISSUE THREAD

**Issue by chrysn** [wolpi/prim-ftpd#38]
since #30, login with rsa keys works fine. i just tried to disable password authentication by setting an empty user password, but without, primftpd refuses to start at all ("You have to set a password first"), while technically, the sftp server could just run without one and not offer the password and keyboard-interactive methods. please consider adding that mode of operation.

thanks a lot for writing and maintaining prim-ftpd!

**Comment by wolpi** [comment]
Yeah, that change sounds reasonable and was also easy to implement. So I just published a new version.

> thanks a lot for writing and maintaining prim-ftpd!

:grinning:
