### ISSUE TITLE
Back arrow icon in titlebar

### ISSUE THREAD

**Issue by licaon-kter** [wolpi/prim-ftpd#39]
Any reason for it?

Now it just sends the app in background, not sure why that is needed.

**Comment by wolpi** [comment]
It "finishes" the app. When it is brought back to top it is actually restarted. There are 2 preferences that require an app restart:
* switching theme
* switching logging

So that back arrow is a short cut for a restart.

**Comment by licaon-kter** [comment]
Given the *language* Android design has that back arrow only means *you are not on the FIRST page of the app press arrow to get BACK to it* and once pressed you're out... not sure it's a good thing to do something else than what the user is expecting.

As for restart, do move it to a menu option where the user will know what that action will actually do.

**Comment by wolpi** [comment]
contributions are welcome :wink:

**Comment by licaon-kter** [comment]
I guess...

Lines 165 and 169 set to `false`: https://github.com/wolpi/prim-ftpd/blob/master/primitiveFTPd/src/org/primftpd/PrimitiveFtpdActivity.java#L165

Also maybe this `case` needs to be removed/refactored: https://github.com/wolpi/prim-ftpd/blob/0c6f80a8833a3df90908ceca8ada50153a3ee2e8/primitiveFTPd/src/org/primftpd/PrimitiveFtpdActivity.java#L617

I don't have a build environment to test with though.

**Comment by wolpi** [comment]
The arrow is now gone. As mentioned in the PR: I added more statusbar icons which are not visible by default.
