### ISSUE TITLE
Add metadata to make F-Droid and Google Play pages translatable

### ISSUE THREAD

**Issue by trikaphundo** [wolpi/prim-ftpd#390]
## The problem
Your [application's page](https://f-droid.org/es/packages/org.primftpd/) in F-Droid is not translated, nor is [Google Play's](https://play.google.com/store/apps/details?id=org.primftpd&hl=es); the latter only provides an automatic translation.

A translated page (i.e. description of the application, changes in new version) signals users the application itself is translated, hence they will be more likely to find, understand and download it when searching in their own tongue; both, in the website and the client application F-droid / Google Play.

## Solution
According to [F-Droid information page](https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/#ways-of-providing-metadata), in order to have your app's page translated, application's metadata should be provided in the app's repo. F-Droid supports two formats, both of them compatible with Google Play; thus, you get two for the price of one. See the previous link for more details.

I can make a PR with the changes for you to check later on.

## Example
You can check BinaryEye application as a model to make your changes
 - F-Droid page in multiple languages: https://f-droid.org/es/packages/de.markusfisch.android.binaryeye
 - Metadata structure in the repo: https://github.com/markusfisch/BinaryEye/tree/master/fastlane/metadata/android

## Caveats
 - I do not know whether you can make the metadata translatable via Weblate, just as with `res/values/strings.xml`, though I guess it is probably possible.
 - Screenshots of the application translated will **do** have to be added manually to the repository. But you can just copy the English' if there is none.

**Comment by trikaphundo** [comment]
@wolpi The translated metadata added to your repo is [not yet shown in F-Droid](https://f-droid.org/es/packages/org.primftpd/). Remember that you must notify the F-Droid repositories [fdroiddata-localizations](https://gitlab.com/fdroid/fdroiddata-localizations/) and [fdroiddata](https://gitlab.com/fdroid/fdroiddata/) in order to have the translated metadata in this repo shown for each language; otherwise F-Droid will still use the information they already have in their repositories, not yours.

> For the official F-Droid repository, it is strongly encouraged to add metadata in the application’s source repo for for the following reasons:
> - The application’s metadata is under direct control of the repository owners
> - Metadata from the repository is copied to the F-Droid repo automatically (thus no merge requests are needed)

Summarizing, file an issue or pull request to have *[description](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/org.primftpd.yml#L8)* and *[summary](https://gitlab.com/fdroid/fdroiddata-localizations/-/blob/master/localizations/es.xliff?ref_type=heads#L5653)* of your app removed from their repos. Thus they will take metadata directly from your repo.

> Please be aware that texts in the app’s metadata file will override all other descriptive texts provided through the structures explained below. This affects [Name](https://f-droid.org/en/docs/Build_Metadata_Reference/#Name), [Summary](https://f-droid.org/en/docs/Build_Metadata_Reference/#Summary), and [Description](https://f-droid.org/en/docs/Build_Metadata_Reference/#Description). Once metadata fields that were previously in the metadata file have been moved to the app’s source repo, please file a [merge request](https://gitlab.com/fdroid/fdroiddata/merge_requests) or [issue](https://gitlab.com/fdroid/fdroiddata/issues) to remove Summary and Description from the app’s metadata file.

-----

Source: [F-Droid metadata information](https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/#ways-of-providing-metadata)

**Comment by wolpi** [comment]
Last time i did not read it carefully enough.

Seems like files from sub-folder of that folder need to be removed?

https://gitlab.com/fdroid/fdroiddata/-/tree/master/metadata/org.primftpd?ref_type=heads

The other repo (https://gitlab.com/fdroid/fdroiddata-localizations/) would hopefully be updated automatically then.

Seems like I cannot login to GitLab right now, have to try again some other day.

**Comment by wolpi** [comment]
The GitLab login problem was spam filter.
Now there is a PR to remove the summary files:
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/17030

**Comment by trikaphundo** [comment]
Changes are already visible on [F-Droid website](https://f-droid.org/es/packages/org.primftpd/) and client app.
Thanks.

**Comment by wolpi** [comment]
Happy that it works now :smiley:
