### ISSUE TITLE
Any plans to update FDroid package? 3.2 ,latest is 4.2

### ISSUE THREAD

**Issue by timofonic** [wolpi/prim-ftpd#40]
Hello. 

I find your program quite interesting. I avoid cloud services as much a possible and prefer FOSS, and so I use FDroid a lot. I even uninstalled Google Play and any other Google service on my Android systems. 

Are there plans to upgrade FDroid package to 4.2? Current one is 3.2, quite outdated. 

Please consider it. Thanks in advance. 

Kind regards.

**Comment by licaon-kter** [comment]
It's 4.1 already.

**Comment by wolpi** [comment]
I published 4.2 just a few minutes ago :wink: 

For one thing: version 3.2 is not that old, you can see these two pages for a version history:

* https://github.com/wolpi/prim-ftpd/releases
* https://f-droid.org/repository/browse/?fdfilter=ftpd&fdid=org.primftpd

And actually 4.1 is available in fdroid, as you can see by the above link. It should take some hours or maybe days until 4.2 becomes available. fdroid monitors the git repository. When a new tag is created the fdroid servers download source code and to their own builds. So each new version is published automatically in fdroid.

Probably you need to refresh the frdoid app on your device.
