### ISSUE TITLE
Removal from Google Play and Amazon App-Store

### ISSUE THREAD

**Issue by wolpi** [wolpi/prim-ftpd#405]
Here is a blog post from someone else which comes close to my thoughts:
https://frozenfractal.com/blog/2024/9/6/why-my-apps-will-soon-be-gone-from-google-play/

See #396 for current issues in this regard.

**Comment by lmagyar** [comment]
Wow. As an outsider after reading the blog post, it seems to be the regular "increasing the entry barrier disguised as security theatre", but his conclusion was nearly the same: "attempt to reduce spam and malicious stuff". Anybody who has malicious intents will publish stuff even after this security measures. :(

**Comment by wolpi** [comment]
Release 7.3 has been built with target SDK 33. It cannot be published on Google Play.


![grafik](https://github.com/user-attachments/assets/683a88e1-ce30-4b1b-b45e-6efd62456864)

**Comment by wolpi** [comment]
In meantime the app has been removed from both stores.
