### ISSUE TITLE
Problem with FTP file upload on KDE

### ISSUE THREAD

**Issue by sniperle** [wolpi/prim-ftpd#41]
When I use KDE and upload a file, the default setting is to add ".part" at the end of the file and when the transfer is finished the file is renamed to it's original file name. This isn't working for whatever reason and the final rename fails, so the file transfer finishes with the ".part" extension. Hopefully this can be fixed.

My actual (disliked) workaround is: http://www.krusader.org/documentation/faq_usage.html#id2672746
> ###### How do not add .part suffix when copying files via FTP?
> When uploading files a .part suffix is added to the filename, once the upload is complete the filename is renamed automagically to remove the .part suffix. This works great but sometimes some FTP servers do not allow a rename operation. You can solve this by unchecking the checkbox Mark partially uploaded files in KDE's System Settings. The check box is located at Network Settings → Connection Preferences.

**Comment by wolpi** [comment]
Which version of the app do you have?
There was a bug in the 3.x series which caused rename to fail. It should be fixed in 4.x.

**Comment by sniperle** [comment]
I'm using the F-Droid version 4.2

**Comment by wolpi** [comment]
It seems that Krusader sends a `cwd` command with the new file as parameter after upload is finished. That might cause the error. It will take a while until I find time to handle that.

I noticed that this behavior does not happen with sftp, so you might use that in the mean time.

**Comment by sniperle** [comment]
Thank you for looking into it.  :-)
AFAIK it's not Krusader who does the ftp access, it's die KIO API of KDE, take a look at this page: 
http://api.kde.org/frameworks-api/frameworks5-apidocs/kio/html/index.html

**Comment by wolpi** [comment]
Seems to work now. When changing working direcotry there is a check if new path is a directory which did not work. That caused the weird behavior.
