### ISSUE TITLE
Google Play(tm) app name

### ISSUE THREAD

**Issue by licaon-kter** [wolpi/prim-ftpd#48]
Was intentional? It's hard to change?

*Primitve FTPd* vs *Primit*_**i**_*ve FTPd*

**Comment by wolpi** [comment]
> Was intentional?

Yes. This app is a small hobby project. Some years ago I got an android phone and wanted to do some development for it, without spending too much time. I see this project as education for myself, to learn how android development works.

> It's hard to change?

Yes it is. The app name is spread all over the code. E.g. in Java packge and class names, in manifest and build script entries, ...

And it is used in a bunch of online services like here on github, fdroid, travisci, google play, amazon, ...

**Comment by licaon-kter** [comment]
So it's no mistake that the name used in the Google Play app is DIFFERENT than the name the app shows inside and that the word `primitve` ( with only two `i` instead of three) is [NOT actually in code anywhere on Github](https://github.com/wolpi/prim-ftpd/search?utf8=✓&q=primitve&type=Code) and [NOT actually mentioned on F-Droid](https://f-droid.org/repository/browse/?fdfilter=ftpd&fdid=org.primftpd)?

![tvtiv](https://i.imgur.com/2Wy5IvE.jpg)

I don't get it but whatever.

**Comment by wolpi** [comment]
Oh, there is a `i` missing. That is a typo. Or better: was a typo.

I thought you wanted to rename the app.

**Comment by licaon-kter** [comment]
No :)

**Comment by finefoot** [comment]
@wolpi So I guess you weren't able to rectify the name in the Google Play Store? Because I just noticed the typo (which is still there) and stumbled upon this closed issue.

**Comment by wolpi** [comment]
For me it looks like this in play store:
![grafik](https://user-images.githubusercontent.com/1812560/60761224-80c31680-a044-11e9-95c5-391c1c8b52b5.png)
Can you share a screenshot, too?

**Comment by finefoot** [comment]
@wolpi For the English page (with `hl=en`) it looks like the screenshot you provided. Yet, the typo persists for the German page: https://play.google.com/store/apps/details?id=org.primftpd&hl=de

![2019-07-07-152227_1280x800_scrot](https://user-images.githubusercontent.com/33361833/60769019-55373f00-a0cb-11e9-9d2f-e67705c783d4.png)

**Comment by wolpi** [comment]
This time it was easy to change it. Google has updated their processes :)
