### ISSUE TITLE
directory listing error with FileZilla

### ISSUE THREAD

**Issue by skx7** [wolpi/prim-ftpd#49]
latest version on F-droid, version 4.3, doesn't allow to open directories while connected. i downgraded back to version 4.2 and all works fine. let me know if you need more information

**Comment by licaon-kter** [comment]
Can't confirm, working ok here.

**Comment by skx7** [comment]
Did you use FileZilla? I use FileZilla on Debian Jessie from the default repositories. downgrading and all worked fine. I can reproduce...

On January 12, 2016 10:47:08 PM CET, licaon-kter <notifications@github.com> wrote:
>Can't confirm, working ok here.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/wolpi/prim-ftpd/issues/49#issuecomment-171068444

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by licaon-kter** [comment]
Debian Sid, F-Droid, yep.

**Comment by skx7** [comment]
Well, that's not the same, I use Debian Stable, Jessie, repositories. Not Sid...

On January 12, 2016 10:53:08 PM CET, licaon-kter <notifications@github.com> wrote:
>Debian Sid, F-Droid, yep.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/wolpi/prim-ftpd/issues/49#issuecomment-171070035

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by wolpi** [comment]
I created issue #50 myself for that. Just uploaded a new version (fdroid build should happen within hours or days).

The bug only occurrs for FTP (not SFTP) and only for relative paths.

**Comment by licaon-kter** [comment]
I use only SFTP, yeah.
The distro won't matter, rather FileZilla version.

**Comment by wolpi** [comment]
This should be done, I'm closing it
