### ISSUE TITLE
FTP does not show dotfiles

### ISSUE THREAD

**Issue by licaon-kter** [wolpi/prim-ftpd#53]
Yet SFTP shows [dotfiles](https://en.wikipedia.org/wiki/Hidden_file_and_hidden_directory).

**Comment by wolpi** [comment]
Oh, I did not notice so far. Will have a look at it.

**Comment by wolpi** [comment]
Seems like a client issue. E.g. Filezilla behaves as you described. But other FTP clients do show dotfiles. The server code inclueds them in the response in both cases.

**Comment by licaon-kter** [comment]
Ok, I got it, basically SFTP uses `ls` to list them but on FTP it uses `MLST/MLSD` which is kinda [the new standard](https://tools.ietf.org/html/rfc3659#page-23), if an 'older' app works it does so by using `LIST`.

An workaround [here (last question)](http://www.proftpd.org/docs/modules/mod_facts.html)

**Comment by wolpi** [comment]
I use apache mina to implement the protocols. Dealing with those commands is mina's business. I will have a look if they provide API to influence this.

**Comment by wolpi** [comment]
Finally this has been found
