### ISSUE TITLE
[Req] Power Toggles and/or Tasker plugin

### ISSUE THREAD

**Issue by Gotolei** [wolpi/prim-ftpd#54]
Since the main functionality of this is controlled by a single start/stop switch, a notification-style toggle could streamline things quite a bit.

Power toggles [GPlay,](https://play.google.com/store/apps/details?id=com.painless.pc) [relevant git](https://github.com/sunnygoyal/power-toggle-plugin)
Tasker [GPlay,](https://play.google.com/store/apps/details?id=net.dinglisch.android.taskerm) [relevant docs](http://tasker.dinglisch.net/plugins.html)

**Comment by wolpi** [comment]
Sounds interesting, it will probably take some months until I find time for this.

**Comment by wolpi** [comment]
For now I implemented the tasker plugin as toggle to start/stop server. wdyt?

**Comment by wolpi** [comment]
as you can see by commit comments I did not leave the simple toggle
