### ISSUE TITLE
Android ICS version support

### ISSUE THREAD

**Issue by licaon-kter** [wolpi/prim-ftpd#56]
Any reason for the app to not work on ICS (android:minSdkVersion="1**5**") ?

/LE: One build later...
It generated the keys ok, all the other things looked right, except that it crashes on server start: https://gist.github.com/licaon-kter/4c2af6dc1f950e8a1530

**Comment by wolpi** [comment]
Two reasons:
- google changed the API to create notifications in sdk version 16
- the API to announce servers via bonjour/avahi is also affected. Not sure if it was completely new in sdk version 16 or changed as well

So it would be necessary to do code changes to support sdk version 15.

**Comment by wolpi** [comment]
Due to #58 the app has already specialized handling for different android versions. More of that was added to support ICS. Two features are not available there:

- announcing of servers
- stop icon in notification

**Comment by licaon-kter** [comment]
Thanks.

**Comment by licaon-kter** [comment]
Any chance for a `release` tag/push? 4.4 was 4 months ago ;)

**Comment by wolpi** [comment]
I plan to do some more stuff on #54 and then release. Probably a few Weeks.

**Comment by licaon-kter** [comment]
I would incline for a `Release early, release often`, but as you wish. ;)
