### ISSUE TITLE
The connection is closed (the underlying SSH process exited)

### ISSUE THREAD

**Issue by JasperWeiss** [wolpi/prim-ftpd#57]
Everytime I try to connect to my phone's SFTP server (ssh://ip:port or sftp://ip:port) I get an error message on my computer saying:

Oops! Something went wrong.
Uhandled error message: The connection is closed (the underlying SSH process exited)

**Comment by licaon-kter** [comment]
-vvvv verbose output?

**Comment by JasperWeiss** [comment]
`jasper@SVE15:~$ sftp Jasper@192.168.2.11:1234 -vvvv
ssh: connect to host 192.168.2.11 port 22: Connection refused
Couldn't read packet: Connection reset by peer`

I could send the log of primitive ftp, it's quite big though

**Comment by licaon-kter** [comment]
use https://gist.github.com to paste

**Comment by JasperWeiss** [comment]
https://gist.github.com/JasperWeiss/08eec40cbea227f68de4

**Comment by wolpi** [comment]
You have hit a bug.
Your log shows that you want to access the root directory. That invokes a call to the method `readSymbolicLink()` which is not implemented. I wonder how your root directory looks like that this happens. Can you connect to your device with `adb shell` and post the output of `ls -lah`, please?

**Comment by JasperWeiss** [comment]
There you go


total 496K
drwxr-xr-x  22 root   root      0 2016-02-04 19:53 .
drwxr-xr-x  22 root   root      0 2016-02-04 19:53 ..
drwxr-xr-x  65 root   root      0 2016-02-04 19:53 acct
drwxrwx---   5 system cache  4.0K 2016-01-25 20:02 cache
drwxrwx---   2 system root      0 2016-02-04 19:53 carrier
lrwxrwxrwx   1 root   root     13 1970-01-01 01:00 charger -> /sbin/healthd
dr-x------   2 root   root      0 2016-02-04 19:53 config
drwxrwx--x   2 system system    0 2016-02-04 19:53 custdata
lrwxrwxrwx   1 root   root     17 2016-02-04 19:53 d -> /sys/kernel/debug
drwxrwx--x  32 system system 4.0K 2016-02-05 07:33 data
-rw-r--r--   1 root   root    542 1970-01-01 01:00 default.prop
drwxr-xr-x  14 root   root    16K 2016-02-04 19:59 dev
drwx------   2 root   root      0 2016-02-04 19:53 devlog
lrwxrwxrwx   1 root   root     11 2016-02-04 19:53 etc -> /system/etc
drwx------   2 root   root      0 2016-02-04 19:53 fataldevlog
-rw-r--r--   1 root   root    50K 1970-01-01 01:00 file_contexts
drwxrwx--x   4 system system    0 2016-02-04 19:53 firmware
-rw-r-----   1 root   root   2.6K 1970-01-01 01:00 fstab.qcom
-rwxr-x---   1 root   root   8.2K 1970-01-01 01:00 init.cm.rc
-rwxr-x---   1 root   root    978 1970-01-01 01:00 init.environ.rc
-rwxr-x---   1 root   root   4.6K 1970-01-01 01:00 init.qcom.power.rc
-rwxr-x---   1 root   root    16K 1970-01-01 01:00 init.qcom.rc
-rwxr-x---   1 root   root   4.9K 1970-01-01 01:00 init.qcom.usb.rc
-rwxr-x---   1 root   root    26K 1970-01-01 01:00 init.rc
-rwxr-x---   1 root   root    319 1970-01-01 01:00 init.superuser.rc
-rwxr-x---   1 root   root    137 1970-01-01 01:00 init.target.rc
-rwxr-x---   1 root   root   1.8K 1970-01-01 01:00 init.trace.rc
-rwxr-x---   1 root   root   9.0K 1970-01-01 01:00 init.usb.configfs.rc
-rwxr-x---   1 root   root   5.2K 1970-01-01 01:00 init.usb.rc
-rwxr-x---   1 root   root    342 1970-01-01 01:00 init.zygote32.rc
drwxr-xr-x   9 root   system  200 2016-02-04 19:53 mnt
drwxr-xr-x   2 root   root      0 1970-01-01 01:00 oem
drwxrwx--x   2 system system    0 2016-02-04 19:53 persist
dr-xr-xr-x 326 root   root      0 1970-01-01 01:00 proc
-rw-r--r--   1 root   root   6.6K 1970-01-01 01:00 property_contexts
drwx------   2 root   root      0 2016-02-04 19:53 ramdump
drwx------   2 root   root      0 2016-02-04 14:14 root
drwxr-x---   2 root   root      0 1970-01-01 01:00 sbin
lrwxrwxrwx   1 root   root     21 2016-02-04 19:53 sdcard -> /storage/self/primary
-rw-r--r--   1 root   root   2.1K 1970-01-01 01:00 seapp_contexts
-rw-r--r--   1 root   root     56 1970-01-01 01:00 selinux_version
-rw-r--r--   1 root   root   247K 1970-01-01 01:00 sepolicy
-rw-r--r--   1 root   root    14K 1970-01-01 01:00 service_contexts
drwxr-xr-x   4 root   root     80 2016-02-04 19:58 storage
dr-xr-xr-x  25 root   root      0 2016-02-04 19:53 sys
drwxr-xr-x  17 root   root   4.0K 1970-01-01 01:00 system
-rw-r--r--   1 root   root    10K 1970-01-01 01:00 ueventd.qcom.rc
-rw-r--r--   1 root   root   7.4K 1970-01-01 01:00 ueventd.rc
lrwxrwxrwx   1 root   root     14 2016-02-04 19:53 vendor -> /system/vendor

**Comment by licaon-kter** [comment]
Please use gist

**Comment by wolpi** [comment]
Well, I did not implement sym links as Java6 (the one used by android) does not support it. But the android root directory usually contains a sym link. Obviously I never tried to access it myself before.

I can probably find a workaround but that will take some weeks.

**Comment by JasperWeiss** [comment]
Sorry I haven't replied yet. Is there anything else I can help with to resolve this issue?

**Comment by wolpi** [comment]
> Is there anything else I can help with to resolve this issue?

Nope. I got all info I need. Now it is just lack of time :disappointed:

**Comment by wolpi** [comment]
There is a way to deal with sym links in java6: `File.getCanonicalPath()`. So this has been fixed for the next release.
