### ISSUE TITLE
Support for pull-requests for new features?

### ISSUE THREAD

**Issue by codebymikey** [wolpi/prim-ftpd#58]
I found your project while looking to implement my own FTP client and thought it was interesting enough to expand on.

I ended up playing around with it and adding small features here and there. But I wasn't sure if you were interested in merging features/pull-requests.

The features I implemented include:
+ Anonymous FTP user support - it's a hassle to force a password unto the user. Toggle-able of-course.
+ Expanded notification layout - so that you can expand it to stop/pause the server(s) without having to go to the activity screen.
+ Included state-specific background colours (green and red) on the home screen widget as the current transparent background and white text makes it difficult to view on the homescreen.

If you're open to pull-requests, where do you stand on additional libraries?
Also, do you prefer including the raw jar libraries over the standard gradle dependency block:

```
dependencies {
    //compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'org.apache.ftpserver:ftpserver-core:1.0.6'
    compile 'org.apache.ftpserver:ftplet-api:1.0.6'
    compile 'org.slf4j:slf4j-api:1.7.13'
    compile 'org.slf4j:slf4j-simple:1.7.13'
    compile 'org.apache.mina:mina-core:2.0.10'
    compile 'org.apache.sshd:sshd-core:0.13.0'
    compile 'com.sshtools:j2ssh-maverick:1.5.2'
    compile 'org.slf4j:slf4j-android:1.6.1-RC1'
}
```
If so, why? I'd really like to know.

The library I propose to include is the lightweight [eventbus](https://github.com/greenrobot/EventBus) library to make updating the launcher widget and activity screen state easier rather than making using the static method call.
I'd also like to include the LeakCanary library to help fix any potential memory leaks.

Regards.

**Comment by wolpi** [comment]
> But I wasn't sure if you were interested in merging features/pull-requests.

I love PRs :wink: 

> Anonymous FTP user support - it's a hassle to force a password unto the user.
> Toggle-able of-course.

So far I considered it important to enforce a password. But with toggle it is alright for me to accept.

> Expanded notification layout - so that you can expand it to stop/pause the server(s)
> without having to go to the activity screen.

This sound interesting, please send it in!

> Included state-specific background colours (green and red) on the home screen widget 
> as the current transparent background and white text makes it difficult to view on the
>  homescreen.

Sounds interessting, too. Eager to see it.

> where do you stand on additional libraries?

I want to avoid a much bigger download size. More libraries are ok as long as they are not too big.

> Also, do you prefer including the raw jar libraries over the standard gradle dependency block
> If so, why? I'd really like to know.

I'm sure you noticed that the whole directory structure of this project is not gradle-like. As I started it there were just eclipse and ant. As I switched to android-studio and gradle I left most files where they were. Libraries too. As this project does not have a big dependency tree there is not much benefit to use dependency management. So i did not bother to switch to it.

Another thing is that I need a customized version of slf4j for my logging preference to work. So at least that one cannot be taken from a public repository.

> The library I propose to include is the lightweight eventbus library
> I'd also like to include the LeakCanary library to help fix any potential memory leaks.

I don't know these two. If you like you can prepare two PRs to show their usage. If I like it I might add it. But no promise :wink: 


Please note that it might take some weeks until I find time to review PRs.

**Comment by codebymikey** [comment]
Ok sure, I'll try putting in some pull-requests sometime this week.

The libraries are quite small as can be seen [here](http://www.methodscount.com/?lib=com.squareup.leakcanary%3Aleakcanary-android%3A1.3.1) and [here](http://www.methodscount.com/?lib=de.greenrobot%3Aeventbus%3A2.4.0).

LeakCanary will really only be used in the debug builds. The release candidates would only include a "noop" version of it.
And EventBuses are typically useful for publishing global events for multiple objects to react to.

**Comment by codebymikey** [comment]
Also do you mind if I update to gradle 2.0 so that we can utilize some of the instant-run features?

**Comment by wolpi** [comment]
> gradle 2.0

You mean the gradle plugin for android studio 2.0?
Yes, throw it in.

And pull new libs with dependency management, please.
In the meantime there have been new versions of apache mina and I'm going to pull them as well.

**Comment by wolpi** [comment]
As your changes have been merged (or applied manually) I'm closing this now.
