### ISSUE TITLE
Add ECDSA support?

### ISSUE THREAD

**Issue by defkev** [wolpi/prim-ftpd#61]
For public key authentication.

I currently get:
```
29.02.2016 11:05	ERROR	org.primftpd.util.KeyInfoProvider	could not read key auth key	"java.io.IOException: Unable to parse key, format could not be identified
	com.sshtools.publickey.SshPublicKeyFileFactory.parse() line: 153
	com.sshtools.publickey.SshPublicKeyFileFactory.parse() line: 179
	org.primftpd.util.KeyInfoProvider.readKeyAuthKey() line: 127
	org.primftpd.services.SshServerService.launchServer() line: 123
	org.primftpd.services.ServerServiceHandler.handleStart() line: 69
	org.primftpd.services.ServerServiceHandler.handleMessage() line: 53
	android.os.Handler.dispatchMessage() line: 102
	android.os.Looper.loop() line: 148
	android.os.HandlerThread.run() line: 61"
```

will trying to load a ecdsa-sha2-nistp521 public key.

**Comment by wolpi** [comment]
I'll have a look at it. Will take some weeks.

**Comment by wolpi** [comment]
Currently I'm using the library j2ssh-maverick to read public keys used for authentication. That library does not support ECDSA in it's open source version. So this will take some time longer to be resolved.

**Comment by wolpi** [comment]
Library j2ssh-maverick has been removed, key parsing has been implemented manually.

**Comment by defkev** [comment]
Almost there :)

Your implementation currently "only" supports 256 bit long keys (not 384 and 521)

Trying to use a ecdsa-sha2-nistp384 or ecdsa-sha2-nistp521 FIP will load 0 keys and throw a 
`UserAuthFactories not set` instead.

It looks like you currently hard-coded the FIP to always be P-256 regardless of what elliptic curve the user has in authorized_keys:
https://github.com/wolpi/prim-ftpd/commit/54385597595560af65167a43f94e43914903f2a6#diff-c5cd490bcd48ead66f80d02eb3cbe5b0R146

**Comment by wolpi** [comment]
yeah, I took the easy road :wink: 

Will continue this for next version

**Comment by wolpi** [comment]
support for the other 2 key sizes has been added
