### ISSUE TITLE
SD card is not writable

### ISSUE THREAD

**Issue by kuanyui** [wolpi/prim-ftpd#65]
I can read the file in SD card, but have no permission to write SD card. I don't understand Android development, maybe this issue is related to #31 ?

Tested on Acer A3-A30 (Android 5.0.2)

**Comment by wolpi** [comment]
Yes, it is exactly #31 and #51 is the same, too

**Comment by kuanyui** [comment]
This issue still exists on ASUS ZenFone 3 (Android 6.0.1)

**Comment by GhettoGirl** [comment]
A workaround for rooted phones http://zidroid.com/how-to-fix-extsdcard-mount-issue-on-kitkat-and-lollipop/

Personally I find the default settings too *paranoid*, so I applied this little tweak.

**Comment by katzenpapst** [comment]
Amaze (the file manager) has some really hacky way of asking for extSdCard write permission. Maybe primitive ftpd could do something similar?

**Comment by wolpi** [comment]
as #31 is closed this should be done as well
