### ISSUE TITLE
Connection by device name

### ISSUE THREAD

**Issue by Paviluf** [wolpi/prim-ftpd#69]
Hello,

It will be great if we can give a name to Android device. That way we can connect to it with its name instead of its ip. With something like that in nautilus :
```
ssh://Motorola.local
```
Thanks

**Comment by wolpi** [comment]
Giving a device a name is nothing an app can do. That is rather something to setup in the OS or in the network.

For example you can edit the file `/etc/hosts` on your desktop to assign your device a name.

**Comment by Paviluf** [comment]
I meant something like that : 

[SSHelper](http://arachnoid.com/android/SSHelper/#The_details)
> Enable Zeroconf broadcast : This option allows SSHelper to announce its services on your local network using Zeroconf/Bonjour, an efficient way to communicate information within a local network. It also allows you to access your device on the local network using "(device name).local" instead of needing to remember the device's IP address.

I just found that we already have the feature in the app ! It's the feature "announce the service". With this enabled we can connect more easily than with the ip in 2 ways :

1. Connect with ssh://android.local:1234
2. Connect in Nautilus / Other locations / primitive ftpd

It's awesome ! If I may, a little improvement would be to make the name "android" customizable.

**Comment by wolpi** [comment]
The hostname cannot be changed within an app. Search the web for how to change the hostname of an android device.

**Comment by Paviluf** [comment]
Ok no big deal. Thanks !
