### ISSUE TITLE
Public Key Authentication work only in a particular order

### ISSUE THREAD

**Issue by Paviluf** [wolpi/prim-ftpd#70]
Hello,

I found that the Public Key Authentication work only in a particular order sometimes. I have 2 PC, one desktop and one laptop. The connection to the laptop work only if its public key is the first one in .ssh/authorized_key.pub. The connection to the desktop always work, regardless the order.

I had a hard time figuring out why my laptop didn't want to connect whereas my desktop, set up the same way, worked perfectly.

Is it something that can be fixed in the app ? Or it's a "problem" on my side ?

Thanks !

**Comment by wolpi** [comment]
Well, the file is named `authorized_key` because just one key is supported. It is not supposed to work with two keys. As key handling is about to be changed for #61 this could be changed as well.

**Comment by Paviluf** [comment]
> Well, the file is named authorized_key because just one key is supported. It is not supposed to work with two keys. 

Oh I didn't know that. That explain why it didn't worked well. It's weird that work with the 2 keys in this particular order so :D

> As key handling is about to be changed for #61 this could be changed as well.

Great ! Thanks !

**Comment by Paviluf** [comment]
Hello wolpi,
Any news about this feature ?
Thanks.

**Comment by wolpi** [comment]
I intend to do a release with pub key auth improvements only. And after I didn't have much time for this project for some month I plan to continue next few days.

-> it should not take that long anymore :wink:

**Comment by Paviluf** [comment]
> it should not take that long anymore

Awesome !
