### ISSUE TITLE
Path of authorized_key.pub

### ISSUE THREAD

**Issue by Paviluf** [wolpi/prim-ftpd#71]
Hello,

I made some research but didn't find where I should put the authorized_key.pub file. It's only by analyzing the logs that I found the path where the app look :
```
/storage/emulated/0/.ssh/authorized_key.pub
```
A little more infos on this should be great ;)

Thanks !

**Comment by wolpi** [comment]
The part `/storage/emulated/0/` is not always the same. Depends on device and andorid version.

**Comment by Paviluf** [comment]
Yeah I know that but what I meant is, for example, to display the path where the app will look in the settings.

**Comment by wolpi** [comment]
Yes, of course.
I didn't as that requires to mix java and xml. In this case the android api isn't that great.

Anyway, I will look into it for next version.

**Comment by Paviluf** [comment]
Thank you ! That will ease things for some people :)

**Comment by Arkanosis** [comment]
That would be great, I was having the same question myself.

Anyway, thanks @Paviluf for the answer and obviously thanks @wolpi for this awesome app :-)

**Comment by wolpi** [comment]
> thanks @wolpi for this awesome app :-)

:beers: :tada:

**Comment by wolpi** [comment]
For issue #70 key handling has been changed to support more than one key. Therefore the filename was changed from `authorized_key.pub` to `authorized_keys`. But to avoid migration problems the old filename is still supported, it is just not shown.

**Comment by Arkanosis** [comment]
Hi @wolpi :)

Thanks a lot, it's perfect!
