### ISSUE TITLE
slow sFTP

### ISSUE THREAD

**Issue by Ano24** [wolpi/prim-ftpd#72]
Hi,

is it possible to speed up the sFTP transfere rate? The ftp server is 10 times faster then the sftp server.

**Comment by wolpi** [comment]
Sorry there is nothing this app can do about.

For one thing sftp requires lots of crypto operations. That may slow down some devices significantly.

And the other thing, this app does not implement the protocols and crypto itself but uses libraries from [apache mina](https://mina.apache.org). You might ask there for improvements.
