### ISSUE TITLE
Add support for Android M runtime Permissions

### ISSUE THREAD

**Issue by codebymikey** [wolpi/prim-ftpd#75]
The app doesn't work on Android M and up because we don't request the WRITE_EXTERNAL_STORAGE permission at run time. So all the user is shown is a blank directory.

I've implemented the code on my local machine. But waiting for #74 to be merged in first.

**Comment by licaon-kter** [comment]
Works fine here, both SFTP and FTP.

You mean for a specific case, eg. SD cards?

**Comment by codebymikey** [comment]
No, that's a much bigger job.
Looking at current state of the repo, it seems to be working for now because the code is currently set to `targetSdk 22`.
My previous [pull-request](https://github.com/wolpi/prim-ftpd/pull/63/files) was targetting 23. But I think since his [previous history change](https://github.com/wolpi/prim-ftpd/pull/62#issuecomment-204606390), it must've been overwritten or skipped. The version of the app which had this issue must've been targetting v23.

Nonetheless, the addition of this code should allow us to target and use the latest android versions and API functionality e.g. #74 (Quick settings tiles), Java 8 code styles.

**Comment by wolpi** [comment]
Thanks! :tada:
