### ISSUE TITLE
Show SHA256 fingerprint base64 encoded

### ISSUE THREAD

**Issue by tyll** [wolpi/prim-ftpd#76]
OpenSSH shows SHA256 fingerprints in this format: ```SHA256:x4xld/tPdeOhbyJcTOxd+IbSZ4OpnBzh/IskocyrOM``` but prim-ftpd uses hexadecimal. Please allow to show the SHA256 fingerprint in the OpenSSH format.

**Comment by wolpi** [comment]
Yes, makes sense to add this as well.

I have to figure out how OpenSSH generates that string.

**Comment by tyll** [comment]
On Mon, Oct 10, 2016 at 02:43:28PM -0700, wolpi wrote:
> Yes, makes sense to add this as well.
> 
> I have to figure out how OpenSSH generates that string.

AFAICS it is the hash value base64 encoded without the padding (instead
of hexadecimal) prefixed by the algorithm.

**Comment by wolpi** [comment]
Has been added. As you said: just base64 encoding without padding of fingerprint bytes.
