### ISSUE TITLE
Primitive > Complete FTPD

### ISSUE THREAD

**Issue by AlphaOmega3** [wolpi/prim-ftpd#81]
(I hope it is not a idiotic thing) you might not develop the app as "Primitive", but as "Complete" FTPD ??

**Comment by wolpi** [comment]
Well, the app got bigger than I expected when it was started. The name might not be appropriate anymore. But I'm not going to rename it.

**Comment by AlphaOmega3** [comment]
I understand. Thank you the same for the answer.
