### ISSUE TITLE
Error with public key

### ISSUE THREAD

**Issue by edo44** [wolpi/prim-ftpd#83]
I get this error every time I try to use a custom public key. I tried with 2048 and 1024 ssh2.

![screenshot_20161113-193046](https://cloud.githubusercontent.com/assets/13797216/20248751/f537a7b8-a9ea-11e6-997e-58002245f317.png)

**Comment by wolpi** [comment]
This is weird.

Can you share your `authorized_keys` file, please?
And how did you generate the keys?

**Comment by edo44** [comment]
I used puttygen to generate the key, I just copied the file e renamed.

**Comment by wolpi** [comment]
It should generate 2 files, one for the public key and another for the private key. It is the public key that needs to be placed on your android device. You need the private key to access it without password. Public key must be in format "public-openssh".

Which one did you copy?

**Comment by edo44** [comment]
I placed the public key in the .ssh fokder,  named authenticated_keys. The file starts with ---- BEGIN SSH2 PUBLIC KEY ----

**Comment by sm4rk0** [comment]
You should place one line generated by puttygen per key. This article explains the procedure:
https://www.howtoforge.com/ssh_key_based_logins_putty_p2
You can reuse your existing key using the "Load" button, or generate a new one.

**Comment by sm4rk0** [comment]
Just noticed that article uses "authorized_keys2" as a file name. Please use "authorized_keys" instead.
More detailed instructions can be found here:
http://the.earth.li/~sgtatham/putty/0.58/htmldoc/Chapter8.html

**Comment by edo44** [comment]
thank you, but now I don't understand why filezilla still uses the old RSA (the automatic one) instead of my new public one.

**Comment by wolpi** [comment]
> The file starts with ---- BEGIN SSH2 PUBLIC KEY ----


That is the wrong format. In the linked article the screenshots show that the public key starts with `ssh-rsa`. That is the right format.

> but now I don't understand why Filezilla still uses the old RSA to connect (the automatic one) instead of my new public one.

In Filezilla you must choose the private key. Of course you have to open the path where it is saved.

There are again several formats for private keys. Putty has it's own format which is called `.ppk` (putty private key). Not sure if Filezilla can read that. Those keys should work with WinSCP.

Filezilla can use keys generated with openssh. That is a commandline tool widley used under linux and macOS. Not sure how to install it under windows.

**Comment by sm4rk0** [comment]
You can use "Conversions" menu in `puttygen` to convert from .ppk to OpenSSH
http://stackoverflow.com/a/2224204/1990878

**Comment by wolpi** [comment]
no update in nearly 2 month: I'm closing this now.
