### ISSUE TITLE
Files shown als Symlinks/Folders

### ISSUE THREAD

**Issue by MartinX3** [wolpi/prim-ftpd#86]
CM13.0 with latest December Snapshot
Nexus 6 & Nexus 7
Client Filezilla

If i want to open a file, first it thinks it is a symlink/folder and want to open it, after a ftp error happen, it will open it like a file.

After switching from "/sdcard/" to "/storage/emulated/0/", the files are shown as files, instead of be shown as symlinks/folders.

**Comment by wolpi** [comment]
This is probably related to all those sym link issues discussed in #68

**Comment by MartinX3** [comment]
Yes! I think you're right!
