### ISSUE TITLE
Folder Creation impossible

### ISSUE THREAD

**Issue by MartinX3** [wolpi/prim-ftpd#87]
CM13.0 with latest December Snapshot
Nexus 6 & Nexus 7
Client Filezilla

It is impossible to create new folders.

"
Error:	Directory /sdcard/0Installation/ROM/Lineage: no such file or directory
Error:	Verzeichnisinhalt konnte nicht empfangen werden
"

**Comment by licaon-kter** [comment]
Syncthing has "Permission: Storage" activated?

**Comment by MartinX3** [comment]
Syncthing?
https://github.com/syncthing/syncthing

Primitive fdpd is the app, i wrote this issue to.

**Comment by licaon-kter** [comment]
Mixed app name. my bad.

ok.

**Comment by MartinX3** [comment]
Your "ok." means, that i gave the app the correct permission?

**Comment by licaon-kter** [comment]
Yes, indeed.

Same issue in FTP and *S*FTP ?

The error is from the app log or logcat? See what the app log says too.

**Comment by MartinX3** [comment]
The error is from filezilla.

I'm searching though the log and will write the results in this answer, without its sensitive data.

**Comment by MartinX3** [comment]
Here's the log for this error:
Status:	Erstelle Verzeichnis '/sdcard/0Installation/ROM/h'...
Befehl:	mkdir "h"
Fehler:	mkdir /sdcard/0Installation/ROM/h: no such file or directory
Befehl:	mkdir "/sdcard/0Installation/ROM/h"
Fehler:	mkdir /sdcard/0Installation/ROM/h: no such file or directory

BTW, it tries to make a symlink.
And handle files as symlinks.

**Comment by licaon-kter** [comment]
Do test with *insecure FTP) too, it's important to see that case.

What about other folder say `/sdcard/X` ?

**Comment by MartinX3** [comment]
Aye aye, Sir!

/sdcard/X
Same Error
/storage/emulated/0/X
IS WORKING
/storage/sdcard0/X
"sdcard0 doesn't exist.

Do I still need to test FTP?
It sounds like the APP doesn't like the Symlink "/sdcard/".

I switched the standard folder from "/sdcard/" to "/storage/emulated/0/".
Now the bug #86 doesn't happen anymore, too.
Every file is now shown as file, instead of symlink.

**Comment by licaon-kter** [comment]
So close these issues ;)

The /sdcard path is a mix bag of things https://www.xda-developers.com/diving-into-sdcardfs-how-googles-fuse-replacement-will-reduce-io-overhead/

**Comment by MartinX3** [comment]
Could you implement a warning, to avoid the using of this folder? :)

And could you build in the android folderpicker, when i want to choose the homedirectory? :)

**Comment by licaon-kter** [comment]
I would love to, but I can't. Also it's not my app. ;)

#43 and #68 cover these issues

**Comment by MartinX3** [comment]
THANK YOU!
