### ISSUE TITLE
SSH-2 Public Key not Accepted?

### ISSUE THREAD

**Issue by Streep** [wolpi/prim-ftpd#92]
I tried generating an SSH-2 RSA key using Puttygen. However when I put the public key in `/storage/emulated/0/.ssh/authorized_keys` and start the server it gives me the message "Public key for key authentication could not be read. Check logs". 

Am I doing something wrong?

**Comment by wolpi** [comment]
Probably key is in wrong format. Try to save it as "open ssh" in puttygen. See #83 for a discussion with some tools to do this.

**Comment by Streep** [comment]
Thanks, it worked,  I didn't know it needed OpenSSH format. I just had to copy and paste the OpenSSH public key from Puttygen into a file "authorized_keys". Also, you have to have to path of the authorized_keys file exactly as stated at the coresponding setting. It seems it's not possible to change the location apparently.

Also when you delete the password, it disables password login (would be better if this was an explicit setting though).

Thanks a lot for the app BTW. It's the best out there. SSH is so much better than the extremely buggy USB connection with MTP.

**Comment by wolpi** [comment]
> Also, you have to have to path of the authorized_keys file exactly as stated at the coresponding setting. It seems it's not possible to change the location apparently.
>
>Also when you delete the password, it disables password login (would be better if this was an explicit setting though).

I did it like that to avoid having even more preferences. There so many of them 😭 .

> Thanks a lot for the app BTW. It's the best out there

Happy that you like it 😃
