### ISSUE TITLE
Announce server in lan doesn't work.

### ISSUE THREAD

**Issue by yuphorian6** [wolpi/prim-ftpd#95]
The announce server in lan feature, which used to work previously, is currently not working.

Version : 4.8.2 installed from fdroid.

**Comment by wolpi** [comment]
Do you have a new phone? It is known that it does not work on all devices. Mail part of that feature is implemented in android, the app just tells the OS which ports to announce.

**Comment by bharat226g** [comment]
Previously, when i turn this feature on, and open desktop linux file manager on the same lan, the primitive ftp used to appear in network folder. But now it doesnt appear. I need to enter the ip address and port manually.

Ohh. I recently switched to stock rom on my device. But also checked on another device with cyanogenmod 10.1 and while it used to work previously, it doesnt work now.

Wish i had access to older apk versions. fdroid only lists last 3 versions.

**Comment by wolpi** [comment]
> Wish i had access to older apk versions. fdroid only lists last 3 versions.

I've just uploaded apks of 4.x:
https://github.com/wolpi/prim-ftpd/releases

Note that those apks are signed with a different key than f-droid ones. Android will delete app settings (and private key) when you switch to them.

**Comment by bharat226g** [comment]
I tried all of the 4.x releases and they don't work with the said feature. Will try other configurations and see if i find anything.

**Comment by wolpi** [comment]
> I tried all of the 4.x releases and they don't work with the said feature.

Yes, as it's an issue of android and not of the app 😉

**Comment by yuphorian6** [comment]
I think this issue is more linked to the PC side. 

Not working with openbox-session in linux . 
Not working in windows.

Working in mate-session in linux.
Probably works with most popular linux desktop environments (gnome, kde, xfce ... )

Why is it not working in openbox-session?
What packages / services should be present on desktop side?

**Comment by wolpi** [comment]
Probably you need `avahi`. See this article in Arch Wiki:

https://wiki.archlinux.org/index.php/Avahi
