### ISSUE TITLE
Can't change server start directory after setting it to root

### ISSUE THREAD

**Issue by throwaway7** [wolpi/prim-ftpd#96]
I changed the server start directory to / however the app does not have root permissions, I can no longer navigate to the phone storage.

Please add a way to manually specify the path of the server start directory.
Thank you.

**Comment by wolpi** [comment]
Probably I can add a reset-button.

For now you can reset app settings in system settings. Or re-install the app.

**Comment by katzenpapst** [comment]
I'd like a reset button, too. My default start directory is /storage/emulated/0, though for some reason (I suspect the reason is google and/or samsung being a**holes) I can not see the "0" directory, so I can't select it again...

**Comment by wolpi** [comment]
reset button has been added
