### ISSUE TITLE
Support for directory as target

### ISSUE THREAD

**Issue by Neui** [wolpi/prim-ftpd#97]
With an normal SSH/SCP server, you can specify an directory as the target and the files are then uploaded to that directory. It makes it really easy to upload many files.

Example from the client:  `scp -P myport * mydevice:/mypath/`. Currently it outputs `File is a directory: org.primftpd.filesystem.SshFile@41982810` and no files are uploaded.

**Comment by wolpi** [comment]
Seems like an issue of apache mina sshd library. I intend to upgrade it anyway (see #100), but you have to wait some time longer 😭 .

Just for record: the important thing is NOT to upload `*`. The same error occurs when uploading a single file to a directory.

**Comment by wolpi** [comment]
Ok, found it. Has been fixed.
