### ISSUE TITLE
Allow anonymous login (option) reseting itself to ON

### ISSUE THREAD

**Issue by Tony-il-Capo** [wolpi/prim-ftpd#98]
Hi
When I open settings, scroll down and then back up. the option for allowing anonymous logins toggles itself to ON.
You might wanna check that out. I'm using latest version from F-Droid (4.8.2)

**Comment by licaon-kter** [comment]
Toggles on and changes colour?
If it stays grey then it's just an Android bug: https://code.google.com/p/android/issues/detail?id=26194

**Comment by Tony-il-Capo** [comment]
I don't see any change in color (not greyed out), it just changes itself to ON. 
The value only stays 'OFF' when I manually set it and don't swipe screen up ('to scroll down') and then exit settings (with back button).

**Comment by licaon-kter** [comment]
I mean: do all toggles to ON havo the same colour?

Some pics with the toggles help.

**Comment by Tony-il-Capo** [comment]
**First screen when I open preferences**

![1](https://user-images.githubusercontent.com/15948151/27184351-d068608e-51d9-11e7-965a-514bea8ddcbe.jpg)
Swipe up the see them all

![2](https://user-images.githubusercontent.com/15948151/27184402-ef9ef5a8-51d9-11e7-8771-4ea124e9dee3.jpg)

**Swipe back down and 'Anonymous Login' toggle changed itself to ON**

![3](https://user-images.githubusercontent.com/15948151/27184507-460f46c2-51da-11e7-8cb6-1c55bf0155ca.jpg)

**Also, I just noticed that "Start on boot" has the same behavior.**

**Comment by licaon-kter** [comment]
Interesting, the bug I've mentioned was on Android 5 and later, if I recall corectly. You are on Android 4 I guess?

**Comment by Tony-il-Capo** [comment]
Yes, Android 4.1.2.

Didn't try to log as anonymous but I can confirm that the values also change in the config file, so, probably the server will allow anonymous logins, it always starts on boot as well, because opening preferences page somehow will always set this to 'ON', only after editing config file manually it stopped loading at boot.
Looks that something is wrong when writing settings.

What's that Android bug you've mentioned about? I can use that link, it asks me to login, no g$$gle account!

**Comment by licaon-kter** [comment]
A graphics error, the toggles look as toggled on but they are not, also the colour does not change (as toggled ones are coloured and untoggled ones are grey)

**Comment by wolpi** [comment]
The app shows in it's main screen whether anonymous login is enabled.

**Comment by Tony-il-Capo** [comment]
After opening the Preferences page > swipe up/down as described above and the options toggle itself to 'ON', I can clearly see on the main screen "Anonymous Login: True", tough, I did not manually allowed this, also as I said before the value also changes in the configuration file.

**Comment by wolpi** [comment]
I've created a version of the app with checkboxes as preferences instead of switches:

https://github.com/wolpi/prim-ftpd/releases/download/prim-ftpd-4.9/primitiveFTPd-4.9-checkboxesapk

Would you mind testing whether it happens with that, too?

Note that that apk is not signed with f-droid key. When installing it android will remove your existing preferences and server sftp key.

**Comment by Tony-il-Capo** [comment]
I've tested that version and it runs okay, settings persist and no more 'self' changes. That problem seems fixed to me.
____

Btw, I noticed that prim-ftpd gets almost instantly killed when I close the app main screen, notification is still active but the service seems dead as client connection close at the same time I leave the app, maybe should it run with a higher priority?

Many thanks for taking the time.

**Comment by wolpi** [comment]
Of course server(s) should continue running when UI is not shown. I get the impression your android version is quite broken 😭

**Comment by Tony-il-Capo** [comment]
No, system kills all apps with background status... Orbot, Afwall+, OpenVPN, ConnectBot, Notification Toggle, etc, always run fine for days, never get killed because of higher priority (run as "service, perceptible or foreground"). I've observed that sometimes prim-ftpd gets background priority instead of service.

Anyway, not a big deal for me as I don't need it to be always running.

**Comment by wolpi** [comment]
Whether service is killed by OS is a matter of available resources, so it seems your device is under heavy load 😉. There are ways to increase priority for services, i'm going to look into it.

**Comment by Tony-il-Capo** [comment]
Lol. Certainly not, lots of resources available (free ram/cpu)

OS kills any app with background status (priority) because no background processes allowed...
This because custom ROM... but I have some reports from people running trying to keep prim-ftpd always running but have the same problem,  Android (v >6) kills the app to 'save battery' they say.

I can't personally verify this, but this might show that maybe the server should run at higher priority.

**Comment by wolpi** [comment]
> OS kills any app with background status (priority) because no background processes allowed

Now there is a preference to run services in foreground, which should solve this

**Comment by Tony-il-Capo** [comment]
Thanks.
Did you changed something to fix this?
> When I open settings, scroll down and then back up. the option for allowing anonymous logins toggles itself to ON.

I've re-tested this again with last version from F-Droid and I couldn't reproduce the problem anymore, just wondering what changed.

**Comment by wolpi** [comment]
> just wondering what changed.

hmm, no changes I am aware of.

`compileSdkVersion`, `targetSdkVersion` (both to 26) and `buildToolsVersion` (to 25.0.3) have been updated, I could imagine that caused this change

**Comment by Tony-il-Capo** [comment]
> OS kills any app with background status (priority) because no background processes allowed
>> Now there is a preference to run services in foreground, which should solve this

Sorry for the late feedback, F-Droid had some [problems](https://github.com/wolpi/prim-ftpd/commit/7d408a9fa886be4bd70f898b557540f87dc07678) building the app as you know, about the issue mentioned above, indeed, having that setting enabled solved the problem.
Thanks again.
